### ISSUE TITLE
Support for neural net regression models 

### ISSUE THREAD

**Issue by beniz** [beniz/deepdetect#1]
Regression tasks need to be supported in addition to supervised tasks with a finite number of labels.

Applications range from multi-target prediction to image rescaling with deep learning.

Subtasks:
- [x] Image and CSV connectors handling of regression target
- [x] MLP template support for regression
- [x] Unit tests in ut-caffeapi
- [ ] Example and documentation

**Comment by beniz** [comment]
Note: support for float 'labels' for regression requires modifying the Datum protobuf format from Caffe as it defines an `int32` as the reference value.

**Comment by beniz** [comment]
FTR, turning Caffe label into a float is related to https://github.com/BVLC/caffe/issues/881 and https://github.com/BVLC/caffe/issues/2139

**Comment by revilokeb** [comment]
Changing label in Datum to float allows for regressing a single float. A more general approach is also described in https://github.com/BVLC/caffe/issues/881by Evan Shelhamer, i.e. storing any number of floats in a second lmdb by using data in Datum, later slice the data in the train_val.prototxt. Are there plans to incorporate multi-regression in dede, too?

**Comment by beniz** [comment]
Yes, I had definitely well noted the comment by Evan! My rational at the time was, like many things involving Caffe, that the amount of work for getting the full and clean functionality working was too much to be done properly immediately vs the quick hack that seemed not too awful in the end.

Multi-regression is a real need that I do believe requires its own ticket and focus. The plan is definitely there, though it will not be immediate. Ticket to come then, and some discussion in it as well.
