### ISSUE TITLE
unexpected quit of server

### ISSUE THREAD

**Issue by anguoyang** [beniz/deepdetect#101]
hi, @beniz , 
I http/put all 12 services on the server one by one, all successfully.
But when I predict images, the server will quit unexpectedly. In my case:

1.post/predict a image on age model,  successfully
2.post/predict a image on gender model, successfully
3.post/predict a image on google net model, server quit unexpectedly, I supposed the server crashed!!! when I "docker ps", there is no image running.

Then I run the docker image again, and http/put all services on the server, and then  post/predict a image on google net model, it works; but if I post/predict more images, it will also crashed!!!

my server has 4gb memory, no GPU, but the CPU is powerful

**Comment by beniz** [comment]
You are very certainly running out of memory.

**Comment by beniz** [comment]
Confirmed memory issue.
