### ISSUE TITLE
Can access API from browser in LAN address like : http://192.169.1.3:8080/info ?

### ISSUE THREAD

**Issue by ken-talkingsource** [beniz/deepdetect#109]
Can access API from browser in LAN address like : http://192.169.1.3:8080/info ?
As I saw example using curl curl -X GET "http://localhost:8080/info"
but can't get access from another lan PC using browser(chrome) ?
(192.168.1.3 is the dd server static address and server firewall is off)

**Comment by beniz** [comment]
Have you looked at http://www.deepdetect.com/overview/usage/ ? You can change the default listening address and port, see the help:
```
./dede --help
```
For an in-browser front-end to image classification, see https://github.com/beniz/deepdetect/tree/master/demo/imgdetect
