### ISSUE TITLE
Core dump during CSV example execution

### ISSUE THREAD

**Issue by fzoll** [beniz/deepdetect#113]
I received Core dump during executing the MLP CSV example.
Checked the core dump and the code and i think there is a typo in caffelib.cc:1651:  _net should be changed to net in my opinion.

**Comment by beniz** [comment]
Thanks for catching this @fzoll. Very nasty one, that was introduced by previous commit. Somehow our unit tests did not run over the build, or something happened since they did crash due to this typo. Will investigate.
