### ISSUE TITLE
Python client unicode decoding error at prediction time

### ISSUE THREAD

**Issue by Isaacpm** [beniz/deepdetect#114]
Hi,

I'm getting the following error when predicting from txt files:
```
Traceback (most recent call last):
  File "/var/models/dboard/dd_client.py", line 230, in post
    return self.__return_format(data)
  File "/var/models/dboard/dd_client.py", line 140, in __return_format
    return json.loads(js.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 86-87: invalid continuation byte

Traceback (most recent call last):
  File "/var/models/dboard/dd_client.py", line 230, in post
    return self.__return_format(data)
  File "/var/models/dboard/dd_client.py", line 140, in __return_format
    return json.loads(js.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 86-87: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/models/dboard/dd_client.py", line 372, in post_predict
    return self.post(self.__urls["predict"],json.dumps(body))
  File "/var/models/dboard/dd_client.py", line 235, in post
    raise DDDataError(u,"POST",headers,body,data)
```

It seems to be random, and not sure if it's because of the content of the text file passed to the prediction.
I'm running a script that predicts based on a pool of 7 models, it predicts each text file with model 1, then model 2, etc....
It does it one after the other and all the data is the same for all seven models at each prediction iteration.
The same file works fine some times but fails others and the same file will work on some of the models before failing.
Any ideas of where should I check that encoding?

Thanks,
Isaac

**Comment by beniz** [comment]
No server output I suppose if this is using a docker container (#110 still needed) ? The `DDDataError` suggest a problem at prediction time. The other errors could be studied by printing out the `js` variable before trying to decode it, this would help.

**Comment by Isaacpm** [comment]
Using local run, no docker this time.
No server output, and the next time you run the predict command with the same data, it works.
I'm going to try to replicate it again and get that js printed, I tried before but I guess was doing something wrong because it didn't print it, just showed the line print(js).
Only problem is that now it's working, it may take a while to get that error again, it's quite random.

**Comment by beniz** [comment]
Are you predicting from URLs ? Because timing out on when fetching the data would get you a 400 Bad Param error.

**Comment by Isaacpm** [comment]
Predicting from txt file

**Comment by beniz** [comment]
Have you been able to reproduce ?

**Comment by Isaacpm** [comment]
No I haven't, I spent a whole morning trying to get rid of the error and I haven't been able to reproduce it again.
I'll have to do more test which may cause it, if it happens I'll post here, if in a couple or three weeks I don't get the error again I'll close this if that's ok with you.

**Comment by Isaacpm** [comment]
It doesn't look like I can reproduce it, I'm closing the issue and if it happens again in the future I'll open it back
