### ISSUE TITLE
Wrong URI when inputting multiple base64 images

### ISSUE THREAD

**Issue by yhenon** [beniz/deepdetect#115]
When multiple images in base64 are passed as an input, deepdetect returns an integer for the URI, as such: `{'classes': {'last': True, 'prob': 0.6079443693161011, 'cat': 'n02123045 tabby, tabby cat'}, 'uri': '0'}`

But when multiple images are passed as base64 at once, it seems like the URI no longer matches the input image.
Here's a small example (full code at the bottom). Populate a python list with alternating base64 cat and dog image:

	imgs = []
	for i in xrange(0,10):
		if i%2:
			imgs.append(dog_base64)
		else:
			imgs.append(cat_base64)

Make the request:

    params = {"service":"imgnet","parameters":{"input":{"width":224,"height":224},"output":{"best":1}},"data":imgs}
    my_json_data = json.dumps(params)
    req = requests.post(url,data=my_json_data)

And then print out the results:

	for idx in xrange(0,10):
		category = req.json()['body']['predictions'][idx]['classes']['cat']
		prob = req.json()['body']['predictions'][idx]['classes']['prob']
		uri = req.json()['body']['predictions'][idx]['uri']

		print(uri + ': ' + category + ' ' + str(prob))

I get:

	0: n02123045 tabby, tabby cat 0.607944369316
	1: n02123045 tabby, tabby cat 0.607944369316
	2: n02123045 tabby, tabby cat 0.607944369316
	3: n02123045 tabby, tabby cat 0.607944369316
	4: n02123045 tabby, tabby cat 0.607944369316
	5: n02110806 basenji 0.279419124126
	6: n02110806 basenji 0.279419124126
	7: n02110806 basenji 0.279419124126
	8: n02110806 basenji 0.279419124126
	9: n02110806 basenji 0.279419124126

I've lost the ordering of the images and can no longer match the image to the prediction (this doesn't only happen if the images are the same, I'm only doing this for demonstration purposes).

Here's a gist with a full example: https://gist.github.com/yhenon/42aab66ea60c61fae6fe8b89ece170e9
You'll need a 'cat.jpg' and 'dog.jpg' image in the folder, and to point url to a valid deepdetect instance.

**Comment by beniz** [comment]
Thanks for reporting this, it should not happen. Can you confirm you are using last master ?

**Comment by beniz** [comment]
OK I see it. Unfortunately I'm so far from a computer for possibly a few days (one of these out of control moments in life) that I am giving you potential fixes below, it'd be great if you could report on them.

- fix 1: comment out all `pragma` in `imginputconnector.h`. This would be temporary

- fix 2: on line 285 in `imginputconnector.h`, beniz/deepdetect/blob/master/src/imginputfileconn.h#L285 and replace with:

```
uris.push_back(i);
```

Thanks again for your time and apologies for the delay, special times...

**Comment by beniz** [comment]
@yhenon Thanks again for the report and the script that made it very easy to check, reproduce and fix. Got a quick access to a machine, and the last commit appears to fix your issue. Let me know how this goes.

**Comment by yhenon** [comment]
Thanks for all your assistance with this - the issue is indeed fixed in the last commit. I hope all is well on your side.
