### ISSUE TITLE
ERROR - service creation mllib bad param: using template while network weights exist, remove 'template' from 'mllib' or would you like to 'finetune' instead ?

### ISSUE THREAD

**Issue by ajkl** [beniz/deepdetect#116]
I am running CUDA 7.5
I get this error on the server when i try to index using 
`python imgsearch.py --index /path/to/your/images --index-batch-size 64`
 (Using this tutorial https://github.com/beniz/deepdetect/tree/imgsearch/demo/imgsearch)

I see this on the client
`{"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}`

The info call works fine though `curl http://localhost:8080/info`

**Comment by ajkl** [comment]
I get the same error when I try to create a image classification service
`curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"template\":\"googlenet\",\"nclasses\":1000}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"../../models/imgnet\"}}"`

**Comment by yarcyarc** [comment]
Seems I also have this problem. I followed http://www.deepdetect.com/tutorials/imagenet-classifier/

My first time with deepdetect, so I might obviously have screwed up somewhere during the tutorial steps. 

See below for details. 

-----------------info-----------
The http://localhost:8080/info: 
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"4d56d42e523d68af7c7198a77a5093baca7a6788","services":[]}}

-------------curl call-------------
<..>/deepdetect/build/main $ curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"template\":\"googlenet\",\"nclasses\":1000}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"../../models/imgnet\"}}"
{"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}

----server side-------
<..>/deepdetect/build/main $ ./dede
DeepDetect [ commit 4d56d42e523d68af7c7198a77a5093baca7a6788 ]
Running DeepDetect HTTP server on localhost:8080

ERROR - 10:04:41 - service creation mllib bad param: using template while network weights exist, remove 'template' from 'mllib' or would you like to 'finetune' instead ?

**Comment by beniz** [comment]
Thanks for reporting this. This is a protection that was recently added to avoid overriding a trained model net definition in production systems.

Putting `imgsearch` aside, current workaround could be do to the `PUT services` and add the weights file afterward to the model repository. Could you report on this by any chance ? Thanks and apologies for the inconvenience, this was a fix with an obvious regression.

**Comment by yarcyarc** [comment]
> Could you report on this by any chance ?

I'd love to but I'm too clueless and the permutation space, given my utter lack of insight, is too large. E.g. - is the weightfile the corresp.txt mentioned? do I need to change the put call accordingly, given this fist assumption is right? Do I change the template arg in the json? The templates? The reposotitory? How do I add a file afterwards to a repo? I tried doing the tutorial with simply skipping the corresp.txt step. That fails.  

I'll come back, hopefully, when the tutorial works. Nice work btw. Looks interesting!

**Comment by beniz** [comment]
@yarcyarc thanks, try out with last commit, I'm severely constrained for a few days, with limited net access, thus my suggestion instead of a fix earlier today. This should also fix the initial report by @ajkl .

**Comment by ajkl** [comment]
Thanks @beniz for the fix, it works!

**Comment by ajkl** [comment]
@beniz Once you index, you have to delete the model files before you run search `rm deploy.prototxt googlenet* model.json` else you get the same error because of the override check.

**Comment by yarcyarc** [comment]
Beautiful. Works now. Thanks so far. 

:-)

**Comment by yarcyarc** [comment]
Hi again, 

I did a pull and rebuilt. Now the same error seems to be there again. Or perhaps I'm doing silly mistakes. Please see below for details. 

-------------build--------

<..>/deepdetect/build $ make clean
<..>/deepdetect/build $ cmake clean ..
-- Boost version: 1.54.0
<..>
<..>/deepdetect/build $ cmake ..
-- Boost version: 1.54.0
<..>
<..>/deepdetect/build $ make 
<..>
<..>/deepdetect/build $ cd caffe_dd/src/caffe_dd<..>/deepdetect/build/caffe_dd/src/caffe_dd $ ./scripts/download_model_binary.py models/bvlc_googlenet/
...100%, 51 MB, 3924 KB/s, 13 seconds passed
<..>/deepdetect $ cp build/caffe_dd/src/caffe_dd/models/bvlc_googlenet/bvlc_googlenet.caffemodel models/imgnet
<..>/deepdetect $ cp datasets/imagenet/corresp_ilsvrc12.txt models/imgnet/corresp.txt

-------------client---------------

<..>/deepdetect/build/main $ curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"template\":\"googlenet\",\"nclasses\":1000}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"../../models/imgnet\"}}"
{"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}

-------------server----------

<..>/deepdetect/build/main $ ./dede 
DeepDetect [ commit 1ca5ec1926527bd386f51fcb3175d6fbae9a0d9c ]
Running DeepDetect HTTP server on localhost:8080

ERROR - 10:40:25 - service creation mllib bad param: using template while network weights exist, remove 'template' from 'mllib' or would you like to 'finetune' instead ?


-------------info---------

http://localhost:8080/info
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"1ca5ec1926527bd386f51fcb3175d6fbae9a0d9c","services":[]}}

**Comment by beniz** [comment]
See whether the [FAQ[(http://www.deepdetect.com/overview/faq/) is useful to you. You probably already have the `prototxt` files in your model repository and need to remove the `template` argument from the call, or to first empty the `models/imgnet` directory.

**Comment by apjansing** [comment]
@beniz Thanks!

An update for people who might still be having problems, remove the **\"template\":\"googlenet\",** from **parameters.mllib**

_Change your directories to **templates** and **repository** to your respective **paths_**

`curl -X PUT http://localhost:8080/services/imageserv -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"nclasses\":1000}},\"model\":{\"templates\":\"/path/to/deepdetect/build/templates/caffe/\",\"repository\":\"/path/to/deepdetect/models/imgnet\"}}"`

**Comment by neo01124** [comment]
I wonder why the service is being deleted [here](https://github.com/beniz/deepdetect/blob/master/demo/imgsearch/imgsearch.py#L112) ? 

I was having this issue - I commented the service creation part in imgsearch.py and created the service with cURL. This issue went away after that.

**Comment by beniz** [comment]
This is a demo you need to accommodate to your application. Even remote, you can see the service as an object, and thus delete it after use. Note that the empty `clear` parameter means that the model data are not deleted, only the logical service on the server.

**Comment by dgtlmoon** [comment]
I'de like to reopen this issue, it seems that the issue stil occurs however I think this is because of #188 . For me when I run the deepdetect `imgsearch.py` from inside the docker container it allows me to index but I see the same `ERROR - 00:11:38 - service creation mllib bad param: using template while network weights exist, remove 'template' from 'mllib' or would you like to 'finetune' instead ?` error when I run it with `--search

**Comment by beniz** [comment]
See the FAQ.

**Comment by abhiguru** [comment]
I checked the FAQ for clearing a service but the clear call fails too 

step 1) Train 
curl -X PUT "http://localhost:8080/services/imageserv" -d '{
       "mllib":"caffe",
       "description":"image classification service",
       "type":"supervised",
       "parameters":{
         "input":{
           "connector":"image"
         },
         "mllib":{
           "template":"resnet_50",
           "nclasses":1000
         }
       },
       "model":{
         "templates":"/home/zzzz/ws/deepdetect/templates/caffe",
         "repository":"../../models/resnet"
       }
}'

LOG For Step 1:
ERROR - 12:59:40 - service creation mllib bad param: using template while network weights exist, remove 'template' from 'mllib' or would you like to 'finetune' instead ?
ERROR - 12:59:40 - 127.0.0.1 "PUT /services/imageserv" 400 0

Step 2:
curl -X DELETE "http://localhost:8080/services/imageserv?clear=full"
Log for Step 2:
ERROR - 13:04: - cannot find service imageserv for removal
ERROR - 13:04: - 127.0.0.1 "DELETE /services/imageserv?clear=full" 404 0

It wont let me train the same with a different service name either

**Comment by beniz** [comment]
You need to re-create your service first since it appears to have been removed (DELETE cannot find it). Don't use `template` in `mllib` when doing so, then call on the DELETE with `clear=full` or `clear=lib` as per what your requirement is.
