### ISSUE TITLE
multi gpu support for search indexing

### ISSUE THREAD

**Issue by ajkl** [beniz/deepdetect#117]
Is there an easy way to utilize multiple GPUs for the imgsearch indexing ?

**Comment by beniz** [comment]
The script uses `predict` calls, you can modify it and use the `gpuid`  API parameter to select which gpu to send to. Or do you mean multi GPU via SLI, in which case this is only supported in training mode by Caffe, see https://github.com/BVLC/caffe/blob/master/docs/multigpu.md

**Comment by ajkl** [comment]
I meant during indexing it uses only 1 gpu right now. Is there a way to use multi-GPUs to speedup indexing. I guess not as it uses Annoy correct ?

**Comment by beniz** [comment]
It's all in my previous message I believe. You can use as many GPUs as you have for the task then index into annoy. Modify the script as needed. Indexing with annoy uses trees and thus has a complexity you cannot avoid. Lower precision with annoy and maybe ssd can speed this up a bit. Another way to speed things up is to use a smaller output layer. You can finetune a net with a smaller intermediary layer or binary codes on your own dataset for this for instance.
