### ISSUE TITLE
Resnet model generates same similarity score with all top images in imgsearch

### ISSUE THREAD

**Issue by ajkl** [beniz/deepdetect#118]
The Resnet model does not seem to work well with the imgsearch example. Has anyone tried it before ?
I am getting same similarity score for all the images when I try to search using imgsearch.

**Comment by beniz** [comment]
Make sure you have modified the output layer name accordingly to match the one in resnet.

**Comment by ajkl** [comment]
I did, I still see `ERROR - 16:40:43 - service imgserv prediction call failed`

These are my changes 

```
host = 'localhost'
sname = 'imgserv'
description = 'image classification'
mllib = 'caffe'
mltype = 'unsupervised'
extract_layer = 'res5c'#'loss3/classifier'
#extract_layer = 'pool5/7x7_s1'
nclasses = 1000
layer_size = 1000 # default output code size
width = height = 224
binarized = False
dd = DD(host)
dd.set_return_format(dd.RETURN_PYTHON)
ntrees = 100
metric = 'angular'  # or 'euclidean'

# creating ML service
model_repo = os.getcwd() + '/model'
model = {'repository':model_repo,'templates':'../templates/caffe/'}
parameters_input = {'connector':'image','width':width,'height':height}
parameters_mllib = {'nclasses':nclasses,'template':'resnet_50'}
parameters_output = {}
dd.put_service(sname,model,description,mllib,
               parameters_input,parameters_mllib,parameters_output,mltype)
```

Apart from these I downlaoded `ResNet-50-model.caffemodel` to `imgsearch/model`

**Comment by beniz** [comment]
Your predict calls are failing. What does the server output says (if you're not using a docker image) ?

**Comment by ajkl** [comment]
It says initialization done and after that i see the above error on the server

**Comment by ajkl** [comment]
This is what I see on the server
```
I0511 16:40:43.353292  5579 caffelib.cc:1202] Using pre-trained weights from /home/ajinkya/deepdetect/demo/imgsearch/model/ResNet-50-model.caffemodel
INFO - 16:40:43 - Network initialization done.
ERROR - 16:40:43 - service imgserv prediction call failed
```

**Comment by beniz** [comment]
Thanks. Are you using a GPU ? If yes, can you try with CPU only by setting `gpu` to False ?

**Comment by ajkl** [comment]
Your suspicion was right! It works with CPU (i was using GPU before). Any suggestions to make it work with GPU ?

**Comment by beniz** [comment]
Open the `deploy.txt` file and set the `barch_size` to 1, this will limit the initial memory allocation to mininum. So not use the `template` argument in the script, and still in the script, lower the `batch_size` value of the predict calls until it works.
