### ISSUE TITLE
CentOS 7 cannot run image prediction example

### ISSUE THREAD

**Issue by chaos2008** [beniz/deepdetect#119]
Hi Beniz,

Thanks for doing this great work of making a docker file. 

I am new to this deepdetect package. I am facing a problem running this docker image under CentOS 7, specifically version 3.10.0-327.el7.x86_64.

I successfully ran the docker image "deepdetect_cpu" in Ubuntu 14.04, and had no problem with the following example lines.

`docker run -d -p 8080:8080 beniz/deepdetect_cpu`

`curl http://localhost:8080/info`

`curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"nclasses\":1000,\"template\":\"googlenet\"}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"/opt/models/ggnet/\"}}"`

`curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3},\"mllib\":{\"gpu\":false}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"`

But in CentOS 7, the service is created successfully. It returns the following as in the example.

`{"status":{"code":201,"msg":"Created"}}`

But if I go on to do the prediction line, I will get

`{"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}`

Could you take a look at this? It seems I am missing something obvious, but I cannot tell where.

Thanks.

**Comment by beniz** [comment]
Weird. Double check the json of your POST call for a start.

To debug further and more easily we d need the server logs but there still is an open issue about this.

What's your familiarity with docker, would you be able to get a bash shell inside the container ? If yes one way would be restart dede from shell, then issue the calls, this would let you see the server logs.

This looks like a benign problem though, and I can't really understand yet how centos would play a role here. Maybe the docker version, but that'd be a wild guess...

**Comment by chaos2008** [comment]
Thanks for replying me. Could you point me how to get inside the container? 

So far my understanding is that the docker image "beniz/deepdetect_cpu" already issues a running dede inside, and meanwhile put the running to "background".

Is there any simple way, i.e. given a running "deepdetect_cpu" image, some docker command can let me get inside?

Or, I need to rebuild a new docker image file without issuing the deepdetect call in the end?

**Comment by chaos2008** [comment]
Thanks for replying me. Could you point me how to get inside the container?

So far my understanding is that the docker image "beniz/deepdetect_cpu" already issues a running dede inside, and meanwhile put the running to "background".

Is there any simple way, i.e. given a running "deepdetect_cpu" image, some docker command can let me get inside?

Or, I need to rebuild a new docker image file without issuing the deepdetect call in the end?

**Comment by beniz** [comment]
See below for investigating further but first verify you have enough RAM, apologies for not thinking of this one before.

See http://stackoverflow.com/a/26496875 and google around for similar cases. 

Then go into `/opt/deep detect/main` and execute `./dede`, the output will the log. You can then issue your calls and see what it says.

**Comment by beniz** [comment]
15 days without update, closing for now, you can reopen with some new activity or information.

**Comment by chaos2008** [comment]
Hi, Beniz,

Sorry for not responding for a while. I got back and started to pick up what I left on this.

Yeah, thanks for your guide. I successfully "attached" to inside.

I got this error message.

------------------------
[04:05:07] /opt/deepdetect/src/caffelib.cc:1738: Error creating model for prediction

ERROR - 04:05:07 - service imageserv mllib bad param: no deploy file in /opt/models/ggnet/ for initializing the net
------------------------

What do you think that is wrong?

I also plugged in another 8Gb RAM, but even with 16Gb memory, the error still occurs.

**Comment by beniz** [comment]
I believe you may have the wrong docker container, they have been updated with a change that would fit your last reported error. If you haven't downloaded the container within the last week or so, please update it and let me know how it goes. Also, make sure to try the exact calls as in the doc as they have been updated as well.

**Comment by beniz** [comment]
Hi @chaos2008, thanks for your perserverance. I've just tried again (docker running on a Ubuntu 14.04 host though), and it works fine, as you are reporting yourself. So I guess we should better investigate whether this is CentOS only, and maybe this is a related issue, https://github.com/beniz/deepdetect/issues/138

Here is the docker version that runs on my Ubuntu host at the moment:
```
docker --version
Docker version 1.11.2, build b9f10c9
```

Could you check yours ?

**Comment by chaos2008** [comment]
It is as follows.

`docker --version`
`Docker version 1.11.1, build 5604cbe`

My Cent OS version is

`CentOS Linux release 7.2.1511 (Core)`

**Comment by beniz** [comment]
OK, do you believe you can share an access to that CentOS + dd docker machine ? If so, could you join us on Gitter at https://gitter.im/beniz/deepdetect so that we can chat about this, and see whether we can get to the bottom of it ? Thanks.

**Comment by cemsaz** [comment]
I have the exact same problem on a AWS linux machine.

**Comment by akshaypai** [comment]
Me too , exact same problem on AWS AMI which I believe is Cent OS.

**Comment by beniz** [comment]
Are you both getting a `no deploy file` error message from the server logs ?

**Comment by akshaypai** [comment]
@beniz  , yes, a no deploy file error. Here is the error message : 

`libdc1394 error: Failed to initialize libdc1394
DeepDetect [ commit 7c70016424f340c20d0a2d5e3717600af6fb8397 ]
Running DeepDetect HTTP server on 0.0.0.0:8080
[06:28:51] /opt/deepdetect/src/caffelib.cc:1817: Error creating model for prediction

ERROR - 06:28:51 - service footwear mllib bad param: no deploy file in /opt/models/footwear for initializing the net
[06:30:22] /opt/deepdetect/src/caffelib.cc:1817: Error creating model for prediction

ERROR - 06:30:22 - service footwear mllib bad param: no deploy file in /opt/models/footwear for initializing the net

ERROR - 08:02:35 - empty resource

ERROR - 09:01:33 - Unknown Service=manager`

**Comment by beniz** [comment]
Please include all API calls, in order etc... Otherwise we can only guess. Obviously the last two errors from the server point to a wrongly crafted call on your side. Also, use the bash login to the docker container and check your `/opt/models/footwear`. You appear to be trying to create a model inside the docker container, and for this you need the `footwear` repository to exist, have you created it ? I'd recommend you create the models outside the container, by mounting a disk location for it.

**Comment by akshaypai** [comment]
I have created a Dockerfile that i used to build the image on my local machine (Ubuntu 14.04) and its working fine. I used the same docker to build the image on Azure cloud server instance ( Ubuntu 14.04)  and there too its running fine. Its only in AWS AMI that I get error :   

here are the steps I used : 

```
Building container :

cd cpu
docker build -t beniz/deepdetect_cpu --no-cache .

run the docker continer

docker run -v /home/akshyap/testDir:/opt/testDir -v /home/akshyap/queryImages:/opt/queryImages -d -p 8080:8080 beniz/deepdetect_cpu
```

following are the curl commands used to test, create service and test service : 


```
curl http://localhost:8080/info

curl -X PUT "http://localhost:8080/services/footwear" -d "{\"mllib\":\"caffe\",\"description\":\"footware classification\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\",\"height\":224,\"width\":224},\"mllib\":{\"nclasses\":50}},\"model\":{\"repository\":\"/opt/models/footwear\"}}"

curl -X PUT "http://localhost:8080/services/clothing" -d "{\"mllib\":\"caffe\",\"description\":\"clothing classification\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\",\"height\":224,\"width\":224},\"mllib\":{\"nclasses\":304}},\"model\":{\"repository\":\"/opt/models/clothing\"}}"

 curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"footwear\",\"parameters\":{\"output\":{\"best\":5}},\"data\":[\"http://www.rockfrocks.com/images/50s-style-rockabilly-shoes/secret-satin-pinup-high-heel-girl-clothing-50s-shoes-for-wedding.jpg\"]}"
```


apart from the AWS the same steps and same Dockerfiel is working without any errors

**Comment by akshaypai** [comment]
Here is the dockerfile  i used. Modified the original one to run only the models I need 

```

FROM ubuntu:14.04

RUN echo 'building CPU DeepDetect image'

MAINTAINER Emmanuel Benazera "beniz@droidnik.fr"
LABEL description="DeepDetect deep learning server & API / CPU version"

RUN ln -sf /dev/stdout /var/log/deepdetect.log
RUN ln -sf /dev/stderr /var/log/deepdetect.log

RUN useradd -ms /bin/bash dd

RUN apt-get update && apt-get install -y git cmake build-essential libgoogle-glog-dev libgflags-dev libeigen3-dev libopencv-dev libcppnetlib-dev libboost-dev libcurlpp-dev libcurl4-openssl-dev protobuf-compiler libopenblas-dev libhdf5-dev libprotobuf-dev libleveldb-dev libsnappy-dev liblmdb-dev libutfcpp-dev wget

WORKDIR /opt
RUN git clone https://github.com/beniz/deepdetect.git && cd deepdetect && mkdir build

WORKDIR /opt/deepdetect/build
RUN cmake .. -DUSE_XGBOOST=ON
RUN make

# external volume to be mapped, e.g. for models or training data
RUN mkdir /data
VOLUME ["/data"]

# include a few image models within the image
RUN mkdir /opt/models
WORKDIR /opt/models

RUN wget http://www.deepdetect.com/models/footwear.tar.bz2 && tar -xvf footwear.tar.bz2
RUN wget http://www.deepdetect.com/models/clothing.tar.bz2 && tar -xvf clothing.tar.bz2
# permissions
RUN chown -R dd:dd /opt/deepdetect
RUN chown -R dd:dd /opt/models

USER dd
WORKDIR /opt/deepdetect/build/main
CMD ./dede -host 0.0.0.0
EXPOSE 8080
```

**Comment by beniz** [comment]
OK thanks, so if you're AWS AMI is CentOS, this definitely appears like a CentOS issue. We do not support CentOS but since the purpose of the containers is to abstract away the OS, I agree that it'd be better if it were working properly on CentOS as well.

So, here is my proposition to nail this one down: can you share access to a CentOS machine running the docker image ? Also, could you join the conversation on [gitter](https://gitter.im/beniz/deepdetect) so that we can try to debug this ?

Have you tried having the model (e.g. footwear) outside the container, if only to check on whether it works that way ?

**Comment by akshaypai** [comment]
Sorry, the AWS AMI does not belong to me, so cannot share it. I guess I can just run a VM of Cent OS , but then again won't be able to share that with you. However, I can try to debug it locally following the things that we discuss. 

I haven't tried moving the model outside the container. I will try that as well and share what I get.

**Comment by manaligaikwad** [comment]
Hi guys,
Any success with this issue? I am also getting this issue on Cent OS.

ERROR - 05:00:08 - service imageserv mllib bad param: no deploy file in /opt/models/ggnet/ for initializing the net
[05:02:49] /opt/deepdetect/src/caffelib.cc:1738: Error creating model for prediction

ERROR - 05:02:49 - service imageserv mllib bad param: no deploy file in /opt/models/ggnet/ for initializing the net

ERROR - 05:03:38 - JSON parsing error on string: {"service":"imageserv","parameters":{"input":{"width":22127.0.0.1:8888":224},"output":{"best":3}},"data":["https://i.ytimg.com/vi/4sMQ9dEpuo8/maxresdefault.jpg","https://i.ytimg.com/vi/4sMQ9dEpuo8/maxresdefault.jpg"]}

Thanks,
Manali

**Comment by beniz** [comment]
Fastest way to understand this issue better would be that someone contributes a CentOS machine online, even temporarily, so that we can all sort it out.

**Comment by cchadowitz-pf** [comment]
This is related to #50 - CentOS 7 defaults to XFS.

A workaround is to configure Docker to use ext4 for the backing filesystem instead.

Starting with a standard CentOS 7 install (I used minimal):
1. Install docker (but don't run it). If it starts automatically, stop the service.
2. Add the arg `--storage-ops dm.fs=ext4` to the docker daemon startup configuration. I added it by editing the docker service file `/usr/lib/systemd/system/docker.service` and adding the arguments to `ExecStart=/usr/bin/dockerd`, which leaves it as `ExecStart=/usr/bin/dockerd --storage-opt dm.fs=ext4`. There may be a better way to do this with `daemon.json`, for example.
3. If you modified the docker service file, do a `sudo systemctl daemon-reload`, or reboot the system to get the changes.
4. Start the docker service.

If you run `sudo docker info`, you should now see the backing filesystem is ext4 instead of xfs. Now when you pull and run the `beniz/deepdetect_cpu` image, it should be able to predict successfully.

This also works if you configure docker to use direct-lvm instead.

**Comment by beniz** [comment]
@cchadowitz-pf thanks for the solution. I'll leave the XFS issue open while closing this one.

**Comment by abhiguru** [comment]
[Ubuntu 16.10] I am getting a similar error with imageserv prediction call failed after successfully creating a network, checked get service/imageserv response showed the service but the standard predict call fails with 500

Logs :
/deepdetect/src/caffelib.cc:1379] Error creating network
/deepdetect/src/services.h:502] service imageserv prediction call failed
/deepdetect/src/httpjsonapi.cc:357] 192.168.10.132 "POST /predict" 500 0

curl -X POST "http://192.168.10.132:8080/predict" -d '{
       "service":"imageserv",
       "parameters":{
         "input":{
   "connector":"image",
           "width":224,
           "height":224
         },
         "output":{
           "best":3
         }
       },
       "data":["ambulance.jpg"]
     }'

I have been able to load and run other pre built models okay the resnet_50 is having a few issues.

**Comment by beniz** [comment]
List the files in your model repository and share your `deploy.prototxt`. Are you using the standard pre-trained resnet 50 model or a custom one ?

**Comment by abhiguru** [comment]
deploy.prototxt form models dir - https://gist.github.com/abhiguru/83aa11ed94617333036fac14a5661ca5

Content of models folder
![res_net_modelrepo](https://cloud.githubusercontent.com/assets/317647/21778601/1c082d98-d6ca-11e6-937e-5e220cb81326.png)

Following the steps as in tut
