### ISSUE TITLE
Error 1007 python client

### ISSUE THREAD

**Issue by youngsol** [beniz/deepdetect#120]
**I have DD server running and I have a client.
I can run following code from the client and I can successfully receive the result**

curl -X POST "http://MYIP:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3}},\"data\":[\"http://deepdetect.com/img/ambulance.jpg\"]}"

**However, I cannot run if I use python script like shown below** 

url = 'http://deepdetect.com/img/ambulance.jpg'
dd = DD('myip') #listening to my IP
dd.set_return_format(dd.RETURN_PYTHON)
sname = 'imageserv'
parameters_input = {'width':'224','height':'224'}
parameters_mllib = {}
parameters_output = {'best':5}
data = [url]
classif = dd.post_predict(sname,data,parameters_input,parameters_mllib,parameters_output)
print classif

**The error message is shown as follow
{u'status': {u'msg': u'InternalError', u'dd_msg': u'in get()', u'code': 500, u'dd_code': 1007}}**

**Comment by beniz** [comment]
`height` and `width` should be numbers, not string

**Comment by youngsol** [comment]
Thanks beniz. You can close this issue.
