### ISSUE TITLE
Example on using custom trained models with deepdetect

### ISSUE THREAD

**Issue by ajkl** [beniz/deepdetect#121]
Is there any documentation on using your own trained models in the imgsearch application ? What all needs to be configured.

**Comment by beniz** [comment]
Hi, most models are finetuned Googlenet, so there should be no difficulties in using them for similarity search. You can look the layer names up in the `prototxt` files.

**Comment by ajkl** [comment]
I tried using the a custom trained Resnet model but the initialization fails. How do you enable more logs for the  imgserv mllib errors ?

**Comment by beniz** [comment]
I seem to have misunderstood your initial question, believing you were referring to the custom models we did release months ago.  Thus the reference to googlenet.

There's only one level of logs at the moment, better state your error instead, as well as exact steps and whether you are using a finetuned model.

**Comment by ajkl** [comment]
Yes I am trying a finetuned resnet model. 
Steps - 
1. Added caffe model to imgsearch/model
2. Added deploy.prototxt to templates/caffe/custom_model_dir
3. Changed the imgsearch script `extract_layer` and `template` params. 

Side question - does it derive layer_size if I dont specify that ?

**Comment by ajkl** [comment]
..and this is the error I get

```
INFO - 10:43:27 - Initializing net from parameters:

ERROR - 10:43:27 - service imgserv prediction call failed
```

**Comment by beniz** [comment]
Your step 2 looks weird. Why not copy the deploy in the model repo and not use the template argument, as specified elsewhere? A template is auto filled by the server, this doesn't look like this is what you are looking for...

**Comment by beniz** [comment]
BTW you should make the predict call work via API for your custom model then have it work with search.

**Comment by ajkl** [comment]
Sure I will try to get that working first

**Comment by beniz** [comment]
No activitity for 15 days, I guess this is solved.

**Comment by albertyou2** [comment]
HI @beniz 
is there any instructions about use custom models for objects detection with deepdetect.
The tutorial only give a instructions of how to setup  objects detect server with pretrained voc07 models.

I build and run  deepdetect successful .And my model was trained by using VGG16 network.
I don't know how to use this model with deepdetect now.

Thankyou !

**Comment by beniz** [comment]
@albertyou2 True we have a separate tooling for training the detection models, and eventually it'll make it to the public version. So at the moment, simply train with SSD https://github.com/weiliu89/caffe/tree/ssd and modify the `.prototxt` according to our FAQ. It should work without difficulty.
