### ISSUE TITLE
Make command failed in /deepdetect/build/ with error 'make: *** [all] Error 2'

### ISSUE THREAD

**Issue by sudoawesomeness** [beniz/deepdetect#122]
Hi,

While installing DeepDetect following "http://www.deepdetect.com/overview/installing/", I'm getting this error at the last step of building deepdetect:

> (caffe2) user@I build (master) $ make

[  4%] Performing configure step for 'caffe_dd'
CXX src/caffe/blob.cpp
CXX src/caffe/common.cpp
CXX src/caffe/data_reader.cpp
CXX src/caffe/data_transformer.cpp
In file included from src/caffe/blob.cpp:4:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:7:
./include/caffe/llogging.h:153:63: error: dynamic_cast from rvalue to reference type 'std::ostringstream &' (aka 'basic_ostringstream<char> &')
      throw CaffeErrorException(std::string(__FILE__) + ":" + SSTR(__LINE__) + " / Fatal Caffe error"); // XXX: cannot report the exact location of the trigger...
                                                              ^~~~~~~~~~~~~~
./include/caffe/llogging.h:70:19: note: expanded from macro 'SSTR'
#define SSTR( x ) dynamic_cast< std::ostringstream & >( \
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/caffe/blob.cpp:4:
In file included from ./include/caffe/blob.hpp:10:
./include/caffe/syncedmem.hpp:26:3: error: dynamic_cast from rvalue to reference type 'std::ostringstream &' (aka 'basic_ostringstream<char> &')
  CHECK(*ptr) << "host allocation of size " << size << " failed";
  ^~~~~~~~~~~
./include/caffe/llogging.h:97:61: note: expanded from macro 'CHECK'
    throw CaffeErrorException(std::string(__FILE__) + ":" + SSTR(__LINE__) + " / Check failed (custom): " #condition ""); \
                                                            ^~~~~~~~~~~~~~
./include/caffe/llogging.h:70:19: note: expanded from macro 'SSTR'
#define SSTR( x ) dynamic_cast< std::ostringstream & >( \
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/caffe/blob.cpp:4:
./include/caffe/blob.hpp:86:5: error: dynamic_cast from rvalue to reference type 'std::ostringstream &' (aka 'basic_ostringstream<char> &')
    CHECK_LE(start_axis, end_axis);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/caffe/llogging.h:103:24: note: expanded from macro 'CHECK_LE'
#define CHECK_LE(x, y) CHECK((x) <= (y))
                       ^~~~~~~~~~~~~~~~~
./include/caffe/llogging.h:97:61: note: expanded from macro 'CHECK'
    throw CaffeErrorException(std::string(__FILE__) + ":" + SSTR(__LINE__) + " / Check failed (custom): " #condition ""); \
                                                            ^~~~~~~~~~~~~~
./include/caffe/llogging.h:70:19: note: expanded from macro 'SSTR'
#define SSTR( x ) dynamic_cast< std::ostringstream & >( \
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/caffe/blob.cpp:4:
./include/caffe/blob.hpp:87:5: error: dynamic_cast from rvalue to reference type 'std::ostringstream &' (aka 'basic_ostringstream<char> &')
    CHECK_GE(start_axis, 0);
    ^~~~~~~~~~~~~~~~~~~~~~~
./include/caffe/llogging.h:104:24: note: expanded from macro 'CHECK_GE'
#define CHECK_GE(x, y) CHECK((x) >= (y))
                       ^~~~~~~~~~~~~~~~~

> 
> Many such similar lines
> 

In file included from src/caffe/data_reader.cpp:8:
In file included from ./include/caffe/layers/data_layer.hpp:6:
./include/caffe/blob.hpp:161:5: error: dynamic_cast from rvalue to reference type 'std::ostringstream &' (aka 'basic_ostringstream<char> &')
    CHECK_GE(width(), 0);
    ^~~~~~~~~~~~~~~~~~~~
./include/caffe/llogging.h:104:24: note: expanded from macro 'CHECK_GE'
#define CHECK_GE(x, y) CHECK((x) >= (y))
                       ^~~~~~~~~~~~~~~~~
./include/caffe/llogging.h:97:61: note: expanded from macro 'CHECK'
    throw CaffeErrorException(std::string(__FILE__) + ":" + SSTR(__LINE__) + " / Check failed (custom): " #condition ""); \
                                                            ^~~~~~~~~~~~~~
./include/caffe/llogging.h:70:19: note: expanded from macro 'SSTR'
#define SSTR( x ) dynamic_cast< std::ostringstream & >( \
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [.build_release/src/caffe/data_reader.o] Error 1
make[2]: *** [caffe_dd/src/caffe_dd-stamp/caffe_dd-configure] Error 2
make[1]: *** [CMakeFiles/caffe_dd.dir/all] Error 2
make: *** [all] Error 2

**Comment by beniz** [comment]
Hi, could you state your platform, OS, compiler and compiler version please ?

**Comment by sudoawesomeness** [comment]
I installed it from Mac (OS X El Capitan - 10.11.4) terminal by cloning from git and building as suggested in "Installing from source" of the tutorial: 
http://www.deepdetect.com/overview/installing/
Installed all the prerequisites using brew.

**Comment by beniz** [comment]
Unfortunately there's no support nor plan to support OSX outside of what community can provide, take a look at #70 in any case. Caffe itself is a pain under OSX, see http://caffe.berkeleyvision.org/install_osx.html

We recommend using a docker version, if that works on OSX (untested and unsupported).

**Comment by beniz** [comment]
Over 15 days without activity on an unsupported OS, I am closing it. Feel free to reopen if you need advice moving forward with OSX.
