### ISSUE TITLE
DeepDetect Configuration (port, log-file)

### ISSUE THREAD

**Issue by santhosh-kumar** [beniz/deepdetect#123]
Is there a way to configure the deep-detect service with a config file. It would be handy to configure:

1) server port and ip
2) log file location

I went through the code and documentation. I couldn't find it. Please let me know if I missed something.

Thank you.

**Comment by beniz** [comment]
Hi, there isn't at the moment. There's a plan for a slightly enhanced version of what you are asking, and that would allow to preset a series of services at startup.

But at the moment configuration needs to be scripted from the outside, or through an alias to `dede` with options.

**Comment by santhosh-kumar** [comment]
>./dede --help
Thanks for the suggestion. This is sufficient for my current use-case. 

[I will close this issue].
