### ISSUE TITLE
Culblas handle

### ISSUE THREAD

**Issue by vladkarnauch** [beniz/deepdetect#124]
I've set up a deepdetect AMI image on AWS as described in:
https://github.com/beniz/deepdetect/issues/5#issuecomment-199952341

However, when I try to classify an image, I get:

```
INFO - source=../templates/caffe/resnet_152/

INFO - dest=../../models/imgnet_resnet152/resnet_152.prototxt
ERROR - Cannot create Cublas handle. Cublas won't be available.
ERROR - Cannot create Curand generator. Curand won't be available.
INFO - Initializing net from parameters:

INFO - Creating layer resnet_152
INFO - Creating Layer resnet_152
INFO - resnet_152 -> data
INFO - resnet_152 -> label
INFO - Setting up resnet_152
INFO - Top shape: 4 3 224 224 (602112)
INFO - Top shape: 4 (4)
INFO - Memory required for data: 2408464
INFO - Creating layer conv1
INFO - Creating Layer conv1
INFO - conv1 <- data
INFO - conv1 -> conv1
ERROR - service imageserv prediction call failed
```

The two errors are:
**ERROR - Cannot create Cublas handle. Cublas won't be available.
ERROR - Cannot create Curand generator. Curand won't be available.**

I'm _very_ new to this, but it seems to me this is because this i've set it up on a non-gpu image. could you please suggest how to deal with it.

Best regards.
Vlad.

**Comment by beniz** [comment]
Hi, cublas and curand may not be the culprits here. Resnet-152 requires more memory than other neural net architectures. This looks more like a memory error as the net creation does not complete. Have you tried first with a simpler model such as `googlenet` ? Make sure you have several GB of available memory.

**Comment by beniz** [comment]
15 days without activity, closing. You can reopen is some new info / test has occured.
