### ISSUE TITLE
mllib bad param: failed to locate model template templates/caffe/googlenet/.prototxt

### ISSUE THREAD

**Issue by ken-talkingsource** [beniz/deepdetect#128]
I am trying to fallow tutorual step by step from installing to here : http://www.deepdetect.com/tutorials/imagenet-classifier/
and I input as 
`$ curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"template\":\"googlenet\",\"nclasses\":1000}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"../../models/imgnet\"}}"`

It returns : 
`{"status":{"code":400,"msg":"BadRequest","dd_code"1006,"dd_msg":"Service Bad Request Error"}}`

and server message as : 
`instantiating model template googlenet`
`I0517 21:26:44.423583 22133 caffelib.cc:90] source=templates/caffee/googlenet/`
`I0517 21:26:44.423609 22133 caffelib.cc:91] dest=../../models/imgnet/googlenet.prototxt`
`ERROR - 21:26:44 - service creation mllib  bad param: failed to locate model template templates/caffe/googlenet/.prototxt`

May I ask where to start checking if I input something incorrect ?

Thank you ~

**Comment by beniz** [comment]
I've just tried it by hand, just in case, and you must be doing something wrong. Typically, modify `templates` so that it points to `/path/to/deepdetect/templates/caffe`, this should accomodate any change, customization or missplacement of repositories you may have come up with.

**Comment by beniz** [comment]
Over 15 days without activity, closing.

**Comment by abhiguru** [comment]
I am getting the same error, on Server side 
"failed to locate model template /home/zzzz/ws/deepdetect/templates/caffe/restnet_50/.prototxt"

I tried all permutations of paths double and triple checked the files for templates and model exists but keep getting the failed to located model template... Why does it look for .prototxt instead of the modelfilename.prototxt ?

curl -X PUT "http://localhost:8080/services/imageserv" -d '{
       "mllib":"caffe",
       "description":"image classification service",
       "type":"supervised",
       "parameters":{
         "input":{
           "connector":"image"
         },
         "mllib":{
           "template":"restnet_50",
           "nclasses":1000
         }
       },
       "model":{
         "templates":"/home/zzzz/ws/deepdetect/templates/caffe",
         "repository":"/home/zzzz/ws/deepdetect/models/resnet"
       }
     }'

**Comment by beniz** [comment]
check on #50 and #119, make sure your filesystem is not XFS.

**Comment by abhiguru** [comment]
typo "template":"resnet_50" instead of "template":"restnet_50" too much rest api dev recently :/
