### ISSUE TITLE
Limiting according to batch_size during prediction phase in order to prevent GPU memory issues

### ISSUE THREAD

**Issue by tmeroniown** [beniz/deepdetect#129]
as part of discussing #127 we came up with the idea of limiting the number of images that are allowed to be fed-forward into the network based on some batchSize limit. This will prevent CUDA memory errors and will improve production robustness. 
This batchSize limit can be set as a part of the parameters:mllib object for Caffe, and that would instantiate the corresponding array/tensor across the model at service creation.
If the user then passes in more images in the image data array during prediction, it would be great if dede would automatically queue these and feed into the network in batches that are smaller than batch size

**Comment by beniz** [comment]
PR #196 addresses this very useful issue, with much delay unfortunately. If everything is well on all fronts, this should be merged soon. Feedback appreciated.

**Comment by beniz** [comment]
Merged.
