### ISSUE TITLE
[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:625] CHECK failed: (index) < (size()):

### ISSUE THREAD

**Issue by jthrelfall777** [beniz/deepdetect#133]
Hi,

I keep getting this error when trying to setup CSV training:

[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:625] CHECK failed: (index) < (size()):

Full Error:

ERROR - 16:17:33 - service regserv training call failed
I0522 16:17:40.582913  3684 csvinputfileconn.cc:239] fname=/data/1.csv / open=1
label size=1 / label_pos size=1
CSV columns:
id field1 field2 field3 regression
I0522 16:17:40.583108  3684 csvinputfileconn.cc:342] read 7 lines from /data/1.csv
I0522 16:17:40.583605  3684 csvinputfileconn.cc:385] data split test size=1 / remaining data size=6
[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:625] CHECK failed: (index) < (size()):

Please could someone help me, I am new to deep detect.

Kind Regards,

John

**Comment by beniz** [comment]
hi @jthrelfall777 please state your platform, whether you are following the [CSV training tutorial](http://www.deepdetect.com/tutorials/csv-training/) or using your own data, and in the latter case, what your `PUT /services` and `POST /train` calls are. Also, in your model repository should be `.prototxt` files, and it is useful to share these as well in gist for instance. Thanks.

**Comment by jthrelfall777** [comment]
Hi @beniz 

Thanks for your quick reply. I have got a gist with everything in. No this is my own data I made up. The data is dummy data to test setting deepdetect up before looking at potential uses for it.

https://gist.github.com/jthrelfall777/f28a5475e95a4a6b1fa22ed9330e7926

Kind Regards

**Comment by beniz** [comment]
@jthrelfall777 thanks for the thorough report. It looks like a bug in our regression model template generator, that may confuse the protobuf reader.

To test this hypothesis, could you try to remove one of the `include: {phase: TRAIN}` statements at line https://gist.github.com/jthrelfall777/f28a5475e95a4a6b1fa22ed9330e7926#file-output-txt-L273 ? And then rerun your `PUT /services` without the `template:mlp` line. Then issue the `POST /train` call.

Please let me know how this goes.

**Comment by jthrelfall777** [comment]
@beniz Thanks that fixed that problem. Got a new one now. I am not sure if it's related so I included the output for you.

https://gist.github.com/jthrelfall777/7175bfd108971f430b99c4a8364145eb

Kind Regards

**Comment by beniz** [comment]
Great, let me clear the first one as it may affect the second one.

**Comment by beniz** [comment]
@jthrelfall777 thanks again for the thorough report, such a good example of a well-informed issue that can be tackled quickly!

The commit above fixes the original problem and another one I quickly found after that. Running your original commands should go through fine, at least it does on my side.

**Comment by jthrelfall777** [comment]
Awesome thank you so much I really appreciate your help :)

**Comment by beniz** [comment]
This appears to be fixed, right ?

**Comment by jthrelfall777** [comment]
Hi,

The original issue seems to be sorted now. It is stopping here and not moving on:

INFO - 17:46:58 - Memory required for data: 5416000
INFO - 17:46:58 - ip3 does not need backward computation.
INFO - 17:46:58 - drop2 does not need backward computation.
INFO - 17:46:58 - act2 does not need backward computation.
INFO - 17:46:58 - ip2 does not need backward computation.
INFO - 17:46:58 - drop1 does not need backward computation.
INFO - 17:46:58 - act1 does not need backward computation.
INFO - 17:46:58 - ip1 does not need backward computation.
INFO - 17:46:58 - drop0 does not need backward computation.
INFO - 17:46:58 - act0 does not need backward computation.
INFO - 17:46:58 - ip0 does not need backward computation.
INFO - 17:46:58 - inputlt does not need backward computation.
INFO - 17:46:58 - This network produces output ip3
INFO - 17:46:58 - This network produces output label
INFO - 17:46:58 - Network initialization done.
I0524 17:46:58.046888 18231 caffelib.cc:1410] filling up net prior to training

Not sure if related, but yes the original issue has gone.

Kind Regards.

**Comment by beniz** [comment]
Is this with the original data and script you shared ?

**Comment by jthrelfall777** [comment]
Ok really sorry, it's been a long day. I was running the wrong dataset. It works perfectly now. Thank you so much for your help.
