### ISSUE TITLE
Image similary search demo : for p in classif['body']['predictions']: KeyError: 'body'

### ISSUE THREAD

**Issue by deter3** [beniz/deepdetect#135]
I have run  
```
python imgsearch.py --index /home/ubuntu/deepdetect/image_search_model/image_2_index  --index-batch-size 64
```
according to the Image similary search  demo .  

in folder "/home/ubuntu/deepdetect/image_search_model" , i have 

model.json 
imgsearch.py
googlenet.prototxt
googlenet_solver.prototxt
deploy.prototxt
corresp_ilsvrc12.txt
bvlc_googlenet.caffemodel

i have created a service named ' imagesearch' and using  
```
curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imagesearch\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"
``` 
which is working . 

in imagesearch.py , I have the code below . 

```Python
 host = 'localhost'
  sname = 'imagesearch' 
 description = 'image searchservice '
 mllib = 'caffe'
 mltype = 'unsupervised'
extract_layer = 'loss3/classifier'
#extract_layer = 'pool5/7x7_s1'
nclasses = 1000
layer_size = 1000 
width = height = 224
binarized = False
dd = DD(host)
dd.set_return_format(dd.RETURN_PYTHON)
ntrees = 100
metric = 'angular'  


model_repo = os.getcwd() 
model = {'repository':model_repo,'templates':'../templates/caffe/'}
parameters_input = {'connector':'image','width':width,'height':height}
parameters_mllib = {'nclasses':nclasses}#,'template':'googlenet'}
parameters_output = {}
dd.put_service(sname,model,description,mllib,
               parameters_input,parameters_mllib,parameters_output,mltype)


parameters_input = {}
parameters_mllib = {'gpu':False,'extract_layer':extract_layer}
parameters_output = {'binarized':binarized}

if args.index:
    try:
        os.remove('names.bin')
    except:
        pass
    s = shelve.open('names.bin')

    c = 0
    onlyfiles = []
    for (dirpath, dirnames, filenames) in walk(args.index):
        nfilenames = []
        for f in filenames:
            nfilenames.append(dirpath + '/' + f)
        onlyfiles.extend(nfilenames)
    for x in batch(onlyfiles,args.index_batch_size):
        sys.stdout.write('\r'+str(c)+'/'+str(len(onlyfiles)))
        sys.stdout.flush()
        classif = dd.post_predict(sname,x,parameters_input,parameters_mllib,parameters_output)
        for p in classif['body']['predictions']:
            if c == 0:
                layer_size = len(p['vals'])
                s['layer_size'] = layer_size
                t = AnnoyIndex(layer_size,metric) # prepare index
            t.add_item(c,p['vals'])
            s[str(c)] = p['uri']
            c = c + 1
        #if c >= 10000:
        #    break
    print 'building index...\n'
    print 'layer_size=',layer_size
    t.build(ntrees)
    t.save('index.ann')
    s.close()
```

I got the error as below 

```
I0524 04:18:37.373163 21693 caffelib.cc:1202] Using pre-trained weights from ../../image_search_model//bvlc_googlenet.caffemodel
INFO - 04:18:37 - Network initialization done.
INFO - 04:18:37 - Attempting to upgrade input file specified using deprecated V1LayerParameter: ../../image_search_model//bvlc_googlenet.caffemodel
INFO - 04:18:37 - Successfully upgraded file specified using deprecated V1LayerParameter
INFO - 04:18:37 - Ignoring source layer data
INFO - 04:18:37 - Ignoring source layer label_data_1_split
INFO - 04:18:37 - Ignoring source layer loss1/ave_pool
INFO - 04:18:37 - Ignoring source layer loss1/conv
INFO - 04:18:37 - Ignoring source layer loss1/relu_conv
INFO - 04:18:37 - Ignoring source layer loss1/fc
INFO - 04:18:37 - Ignoring source layer loss1/relu_fc
INFO - 04:18:37 - Ignoring source layer loss1/drop_fc
INFO - 04:18:37 - Ignoring source layer loss1/classifier
INFO - 04:18:37 - Ignoring source layer loss1/loss
INFO - 04:18:37 - Ignoring source layer loss2/ave_pool
INFO - 04:18:37 - Ignoring source layer loss2/conv
INFO - 04:18:37 - Ignoring source layer loss2/relu_conv
INFO - 04:18:37 - Ignoring source layer loss2/fc
INFO - 04:18:37 - Ignoring source layer loss2/relu_fc
INFO - 04:18:37 - Ignoring source layer loss2/drop_fc
INFO - 04:18:37 - Ignoring source layer loss2/classifier
INFO - 04:18:37 - Ignoring source layer loss2/loss
INFO - 04:18:37 - Ignoring source layer pool5/drop_7x7_s1
INFO - 04:18:37 - Ignoring source layer loss3/loss3
ERROR - 04:18:37 - service imagesearch prediction call failed
```

Can you tell me what's wrong with the prediction ? I guess there is something with imagesearch.py file since curl calling prediction is working now .

**Comment by beniz** [comment]
Try a lower `batch_size` to start with.

**Comment by deter3** [comment]
@beniz  thanks for prompt reply . tried batch_size 2  , python imgsearch.py --index /home/ubuntu/deepdetect/image_search_model/image_2_index  --index-batch-size 2 , same error .

**Comment by beniz** [comment]
Your initial testing call is a supervised call, try making the exact same call that your Python script does then, and see if it gets through.

**Comment by deter3** [comment]
@beniz  I restart the server , started the service by "curl -X PUT "http://localhost:8080/services/imagesearch" -d "{\"mllib\":\"caffe\",\"description\":\"image searchservice\",\"type\":\"unsupervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"template\":\"googlenet\",\"nclasses\":1000}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"../../image_search_model/\"}}""

response is "{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"11566f639c1427b0bf72b4a06f9b99e548007b13","services":[{"mllib":"caffe","description":"image searchservice","name":"imagesearch"}]}}" 

I try prediction with "curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imagesearch\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"" , which is not working , 
response is "{"status":{"code":403,"msg":"Forbidden"}} "

try python imgsearch.py --index /home/ubuntu/deepdetect/image_search_model/image_2_index  --index-batch-size 1 , same error as before .

**Comment by beniz** [comment]
> I try prediction with

Please use the same parameters as your script does: 

```
mllib:{'gpu':false,'extract_layer':'loss3/classifier'}
output:{'binarized':false}
```

**Comment by deter3** [comment]
@beniz  I deleted the files below in model folder and re-created service "imagesearch" with unsupervised type . 

model.json 
googlenet.prototxt
googlenet_solver.prototxt
deploy.prototxt

I then used same imagesearch.py to run "python imgsearch.py --index /home/ubuntu/deepdetect/image_search_model/image_2_index  --index-batch-size 1 " , the response is 

raceback (most recent call last):
  File "imgsearch.py", line 83, in <module>
    layer_size = len(p['vals'])
TypeError: string indices must be integers

**Comment by beniz** [comment]
@deter3 you need to test the prediction with curl on the unsupervised service. This demo code does not include error handling, and obviously the prediction does not work in your setting somehow. Please follow the instructions above to make the prediction call with curl. Thanks.

**Comment by beniz** [comment]
Also, I suggest you come onto gitter at https://gitter.im/beniz/deepdetect to discuss your issue lively as this seems to be no bug (I've tested a few minutes ago just in case).

**Comment by deter3** [comment]
@beniz  I will join the chat room .  I can hardly figure out the curl call , I tried 

`curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imagesearch\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3,\"binarized\":false}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"] , \"mllib\":{\"gpu\":false,\"extract_layer\":\"loss3/classifier\"}}"`

got error 

`{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"in get()"}}`

**Comment by deter3** [comment]
finally got it working with the help of @beniz  .  

how to resolve this issue ? 

1. using the json call below to verify the service , I am using CPU , binarized false ,  extract_layer : loss3/classifier  , which is the same as my imagesearch.py predict call .  And I command out line "parameters_input = {} " . 

`curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imgserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"mllib\":{\"gpu\":false,\"extract_layer\":\"loss3/classifier\"},\"output\":{\"best\":3,\"binarized\":false}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"`

2. After making sure the service is up and running , then make sure all images to be indexed have no error during the  transform process  , and set batch size to 2  in both command line and deploy.prototxt , otherwise , will get error 

`Typre error for p["val"]`

I used command line as below .

`python imgsearch.py --index /home/ubuntu/deepdetect/image_search_model/image_2_index  --index-batch-size 2 `

After file index.ann being saved ,  start to search by 

`python imgsearch.py --search /home/ubuntu/deepdetect/image_search_model/image_2_index/49417121.jpg  --search-size 10`

**Comment by anguoyang** [comment]
Hi @deter3 ,I followed your steps, but it seems the index.ann file are broken, I got these errors:
Traceback (most recent call last):
  File "imgsearch.py", line 103, in <module>
    u = AnnoyIndex(s['layer_size'],metric)
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: 'layer_size'

**Comment by beniz** [comment]
See demo code here: https://github.com/jolibrain/deepdetect/tree/master/demo/imgsearch

**Comment by anguoyang** [comment]
hi @beniz I followed the steps, but still got this error:
NameError: name 't' is not defined
---------------------
          t = AnnoyIndex(layer_size,metric) # prepare index
            t.add_item(c,p['vals'])
            s[str(c)] = p['uri']
            c = c + 1
        #if c >= 10000:
        #    break
    print 'building index...\n'
    print 'layer_size=',layer_size
    t.build(ntrees)
    t.save('index.ann')
    s.close()
--------------------------------
do I need to predefine the t variable?

**Comment by beniz** [comment]
You don't need to write this in Python, it's all in DD now, see https://github.com/jolibrain/deepdetect/blob/master/demo/imgsearch/imgsearch_dd.py

If you are using your own build, don't forget the `-DUSE_SIMSEARCH=ON` cmake option.

**Comment by anguoyang** [comment]
Thank you:) it worked on imagesearch_dd.py
