### ISSUE TITLE
Image similarity search while the model need to be trained without Tags

### ISSUE THREAD

**Issue by anguoyang** [beniz/deepdetect#139]
Hi, @beniz ,

I have another question on image similarity search, from the description of imgsearch, it uses pre-trained models, such as ggnet or resnet, my question is, how to train a model if the images have no tags?

Please allow me to describe the requirement from my friend(here,"we" is my friend, not me):
"We have lots of photos/images, say 10 million or more, they are original photos/images from our customers which need to be protected(To prevent plagiarism), here we call it as dataset A. 
We also got lots of images by way of web crawler, from bloggers, websites, forum, etc.  some of these images are simply copied from dataset A, some added with additional watermark, we call it as dataset B. it currently contains about 300000 images, but it will still grows.
We will use 1 image or several images from dataset A, we call it as dataset C, we want to search images in B which is similar with C, list all similar images.
We want to use deep learning for similarity search, but most of the images in dataset A has no tag, could we train these images into a specific model, then we could get more accurate result while searching similar images?"

Thank a lot!

**Comment by beniz** [comment]
hi @anguoyang this is not an issue with the code. If your friend is working for customers I guess he should be seeking professional help. You can try to ask your question on gitter, caffe-users list etc...
