### ISSUE TITLE
ResNet-152 category texts

### ISSUE THREAD

**Issue by simirimia** [beniz/deepdetect#141]
Hi,

a simple beginners question:

I followed http://www.deepdetect.com/tutorials/imagenet-classifier and set up a service. Contrary to the tutorial I used the ResNet-152 model downloaded here: http://www.deepdetect.com/models/resnet/.

It seems to work, a predict call returns for example:
`"classes": [
        {
          "prob": 0.9998952150344849,
          "cat": "407"
        },
        {
          "prob": 0.0000722993427189067,
          "cat": "734"
        },
        {
          "last": true,
          "prob": 0.000027834061256726272,
          "cat": "654"
        }
      ]`

My question: where do I get the corresponding text of the category Id? I checkt some of the *.txt files in http://www.deepdetect.com/models, but there is nothing similar in the ResNet folder.

Thanks!

**Comment by beniz** [comment]
Hi, you must have missed a step in the tutorial that tells you how to get the `corresp.txt` file.

**Comment by simirimia** [comment]
Thanks a lot :+1: And especially for the very fast response
Totally missed that one, now it returns the category names.
