### ISSUE TITLE
Error in running alexnet for image similarity search

### ISSUE THREAD

**Issue by kyrs** [beniz/deepdetect#144]
Hi I am trying to run Alexnet for Image similarity search.  But I am getting an error of `{u'status': {u'msg': u'InternalError', u'dd_msg': u'src/caffe/data_transformer.cpp:169 / Check failed (custom): (height) <= (datum_height)', u'code': 500, u'dd_code': 1007}}`  Can you tell me what am I doing wrong ?

**Comment by beniz** [comment]
hi @kyrs the server is telling what is wrong: image size. The demo `imgsearch.py` uses 224x224 input size and quick look at the alexnet `prototxt` files (I let you do that) tells you that it uses a slightly different input size (and I let you find its value).

Contrary to `resnet` these networks are not fully convolutional, i.e. the input size is fixed.

**Comment by kyrs** [comment]
Ok.. got it working.  It was 227X227 for alexnet. Thanks for the help!!
