### ISSUE TITLE
Exception while filling up network for prediction with character-based model

### ISSUE THREAD

**Issue by aliabbasjp** [beniz/deepdetect#145]
Continuing with previous issue:
https://github.com/beniz/deepdetect/issues/143

I am now facing following error while doing prediction:

`curl -X POST 'http://localhost:8080/predict' -d '{"data": ["ewe", "alice"], "parameters": {"input": {}, "mllib": {"gpu": true}, "output": {}}, "service": "domal"}'`

I get following error:
vocab.dat file size is zero.

```
INFO - 12:26:23 - resphape0 does not need backward computation.
INFO - 12:26:23 - pool1 does not need backward computation.
INFO - 12:26:23 - act2 does not need backward computation.
INFO - 12:26:23 - conv2 does not need backward computation.
INFO - 12:26:23 - act1 does not need backward computation.
INFO - 12:26:23 - conv1 does not need backward computation.
INFO - 12:26:23 - pool0 does not need backward computation.
INFO - 12:26:23 - act0 does not need backward computation.
INFO - 12:26:23 - conv0 does not need backward computation.
INFO - 12:26:23 - data does not need backward computation.
INFO - 12:26:23 - This network produces output label
INFO - 12:26:23 - This network produces output loss
I0610 12:26:23.191118  2551 caffelib.cc:1203] Using pre-trained weights from /corpus/caffemodel/domal/model_iter_5000.caffemodel
INFO - 12:26:23 - Network initialization done.
INFO - 12:26:23 - Ignoring source layer reshape0
INFO - 12:26:23 - Ignoring source layer drop2loaded vocabulary of size=0
E0610 12:26:23.193681  2551 caffelib.cc:1840] exception while filling up network for prediction

ERROR - 12:26:23 - service domal prediction call failed
```

**Comment by beniz** [comment]
The error is `exception while filling up network for prediction`, the vocabulary size is 0 since you are using a character-based model, and there's no vocabulary (i.e. words) per se.

This exception frequently arises in cases where your system lacks RAM or GPU memory, so first try with `gpu:false`. Another culprit could be that the weights and network definition do not match.

**Comment by aliabbasjp** [comment]
@beniz I am using Titan X, 64 gb system RAM. And a small 1C32 convnet

**Comment by beniz** [comment]
Do the provided example and datasets work well ? If yes, you must be mixing something up somewhere, and this is difficult to assess.

**Comment by aliabbasjp** [comment]
`Another culprit could be that the weights and network definition do not match.`

What do you mean by that?
I tried gpu=false and same error

**Comment by beniz** [comment]
@aliabbasjp it means that you need to make sure the `prototxt` files are exactly those with which the model `.caffemodel` file was trained with.

Also, if you'd like to move forward, please try to answer the questions, like do the provided example and datasets work well ?

**Comment by aliabbasjp** [comment]
@beniz Yes they are same as they all are saved in a single folder.

I tried multiple times deleting all contents of the model repo and trained it and all files prototxt and caffemodel files are generated in that one folder.

Even the model is getting loaded , only problem is the error comes on prediction.

I have not tried the examples given but will try soon.

**Comment by beniz** [comment]
Try training one of the example models, like AG news, on just a few iterations and make a prediction out of it. If it still doesn't work, lay down all the steps in a gist and I'll try the exact same steps.

**Comment by aliabbasjp** [comment]
@beniz 

I tried agnews example exactly but got following error:
```
DeepDetect [ commit 3fff966c912dcf414455841fdb6540bcccc5a2fd ]
Running DeepDetect HTTP server on localhost:8080
instantiating model template convnet
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0614 12:10:31.988551 29691 caffelib.cc:90] source=../templates/caffe//convnet/
I0614 12:10:31.988692 29691 caffelib.cc:91] dest=/code/cafmodel//convnet.prototxt
loaded text samples=1data split test size=1 / remaining data size=0
vocab size=0

ERROR - 12:10:33 - service agnews3 training status call failed

ERROR - 12:10:33 - {"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error"}
```




client : 

Ignore the None.
```
 python drugagnewstrain.py --model-repo "/code/cafmodel/" --training-repo ./agnews_data/ --sname agnews3 --tsplit 0.1 --base-lr 0.01 --sequence 1014 --iterations 150000 --test-interval 1000 --nclasses 4
2016-06-14 12:10:31.986848 PUT /services/agnews3
{"model": {"templates": "../templates/caffe/", "repository": "/code/cafmodel/"}, "type": "supervised", "description": "character-based classifier", "parameters": {"input": {"connector": "txt", "sequence": 1014, "characters": true, "sentences": true}, "mllib": {"layers": ["1CR256", "1CR256", "4CR256", "1024", "1024"], "dropout": 0.5, "db": true, "nclasses": 4, "template": "convnet"}, "output": {}}, "mllib": "caffe"}
None
2016-06-14 12:10:32.005289 {"status":{"code":201,"msg":"Created"}}
None
2016-06-14 12:10:32.005519 curl -X POST 'http://localhost:8080/train' -d '{"async": true, "data": ["./agnews_data/"], "parameters": {"input": {"shuffle": true, "sequence": 1014, "test_split": 0.1, "db": true, "characters": true, "sentences": true}, "mllib": {"gpu": true, "net": {"test_batch_size": 128, "batch_size": 128}, "solver": {"test_initialization": true, "stepsize": 15000, "base_lr": 0.01, "iterations": 150000, "test_interval": 1000, "weight_decay": 1e-05, "snapshot": 150000, "lr_policy": "step", "solver_type": "SGD", "gamma": 0.5, "iter_size": 1}, "resume": false}, "output": {"measure": ["mcll", "f1"]}}, "service": "agnews3"}'
None
2016-06-14 12:10:33.008291 GET http://localhost:8080/train?service=agnews3&job=1&timeout=10
None
2016-06-14 12:10:33.011427 {"status":{"code":200,"msg":"OK"},"head":{"method":"/train","job":1,"status":"error"},"body":{}}
None
{u'status': {u'msg': u'OK', u'code': 200}, u'body': {}, u'head': {u'status': u'error', u'job': 1, u'method': u'/train'}}
2016-06-14 12:10:33.011656 DELETE /services/agnews3
None
2016-06-14 12:10:33.012555 {"status":{"code":200,"msg":"OK"}}
None
```

**Comment by aliabbasjp** [comment]
@beniz  O , On giving the full path to ./agnews_data/ it worked and started processing further ,so it means relative paths not being accepted.

**Comment by beniz** [comment]
Relative paths are supported but always relative to where `dede` was started from. They can't really be relative to anything else.

**Comment by beniz** [comment]
Also, don't train for more than a few hundreds iterations, then use the model for prediction and see whether you get an error.

**Comment by aliabbasjp** [comment]
@beniz 
` curl -X POST 'http://localhost:8080/predict' -d '{"data": ["My cat"], "parameters": {"input": {}, "mllib": {"gpu": true}, "output": {}}, "service": "agnews4"}'`



gives same error :
`{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"src/caffe/data_transformer.cpp:168 / Check failed (custom): (channels) == (datum_channels)"}}`

```

I0614 13:21:21.693574 26239 caffelib.cc:1203] Using pre-trained weights from /code/cafmodel//model_iter_150.caffemodel
INFO - 13:21:21 - Network initialization done.
INFO - 13:21:22 - Ignoring source layer reshape0
INFO - 13:21:22 - Ignoring source layer reshape0_reshape0_0_split
INFO - 13:21:22 - Ignoring source layer drop3
INFO - 13:21:22 - Ignoring source layer drop4loaded vocabulary of size=0
E0614 13:21:22.281898 26239 caffelib.cc:1840] exception while filling up network for prediction

ERROR - 13:21:22 - service agnews4 prediction call failed
```

**Comment by beniz** [comment]
It works fine for me. Your service creation call is certainly wrong, here is the one I use for agnews:
```
curl -X PUT 'http://localhost:8080/services/agnews' -d '{"mllib":"caffe","description":"classification","type":"supervised","parameters":{"input":{"connector":"txt","characters":true,"sequence":1014},"mllib":{"nclasses":4}},"model":{"repository":"/path/to/model"}}'
```

**Comment by aliabbasjp** [comment]
It worked 

after putting 

` parameters_input = {'connector':'txt',"characters":True,"sequence":1014}

`

while in the service creation code , I thought it should read these parameters from the trained model itself as I myself forgot which sequence:1014 I had trained it with.

So if I just remove "sequence":1014 from parameters_input  will it read the seq length setting from trained model?

**Comment by beniz** [comment]
No, it will use the default value for `sequence`. Some of these informations could be read from the model but this would be hacky and is not supported at the moment. And the connector needs to be initialized, the Caffe model has no view of whether it is dealing with text or raw data of any kind. The `model.json` file always contains the history of writing calls to the model and parameters are available in it.

**Comment by aliabbasjp** [comment]
So I returned backed to my original task but got this error:
`
{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"src/caffe/data_transformer.cpp:178 / Check failed (custom): (datum_width) == (width)"}}`

```
INFO - 14:47:41 - conv0 does not need backward computation.
INFO - 14:47:41 - data does not need backward computation.
INFO - 14:47:41 - This network produces output label
INFO - 14:47:41 - This network produces output loss
I0614 14:47:41.823631 25615 caffelib.cc:1203] Using pre-trained weights from /code/drgmodel//model_iter_150.caffemodel
INFO - 14:47:41 - Network initialization done.
INFO - 14:47:41 - Ignoring source layer reshape0
loaded text samples=1E0614 14:47:41.826155 25615 caffelib.cc:1840] exception while filling up network for prediction

ERROR - 14:47:41 - service newdrug prediction call failed
```


I am using sequence lenght  of 50 for both training at testing

**Comment by beniz** [comment]
if you are not using the default alphabet you need to specify it in your service creation call.

**Comment by aliabbasjp** [comment]
@beniz Yes that worked

**Comment by beniz** [comment]
OK, good, let me know what was missing in the doc to help you out so it can be improved.

**Comment by aliabbasjp** [comment]
@beniz the assumptions on specifying default values should be explicitly documented eg:code is not reading the trained parameters and to explicitly specify them.
