### ISSUE TITLE
Trainning is not working 

### ISSUE THREAD

**Issue by diepbang** [beniz/deepdetect#149]
I created service with : 
curl -X PUT "http://localhost:8080/services/imageserv" -d '{"mllib":"caffe","description":"image classification service","type":"supervised","parameters":{"input":{"connector":"image"},"mllib":{"template":"googlenet","nclasses":1000}},"model":{"templates":"../templates/caffe/","repository":"/media/imgnet"}}'
And i have follow this tutorial : http://www.deepdetect.com/tutorials/imagenet-classifier/
------------------------- and this respository -------------------------
https://www.dropbox.com/s/r7fz09nn2dajwju/imgnet.png?dl=0
---------------------------------------------------------------------------------------
Now the problem is when call tranining with 

curl -X POST "http://localhost:8080/train" -d '{"service":"imageserv","async":true,"parameters":{"mllib":{"gpu":true,"net":{"batch_size":32},"solver":{"test_interval":500,"iterations":30000,"base_lr":0.001,"stepsize":1000,"gamma":0.9}},"input":{"connector":"image","test_split":0.1,"shuffle":true,"width":224,"height":224},"output":{"measure":["acc","mcll","f1"]}},"data":["/media/img"]}'

It return "{"status":{"code":201,"msg":"Created"},"head":{"method":"/train","job":1,"status":"running"}}"

But i check the log of the server ... Its return "INFO - 12:55:00 - A total of 0 images."
But it doesn't run it just stay there forever until i do 

Then when i do : curl -X GET "http://localhost:8080/train?service=imageserv&job=1"

It return : {"status":{"code":200,"msg":"OK"},"head":{"method":"/train","job":1,"status":"error"},"body":{}}

And the server output 
ERROR - 12:56:40 - {"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error"}

. Whats going on ? I still have 3GB left on my laptop and the folder /media/img has images .  I have checked everything and i don't know what went wrong please help me ! thanks you

----- UPDATED ----

curl -X POST "http://localhost:8080/train" -d "{\"service\":\"imageserv\",\"async\":false,\"parameters\":{\"mllib\":{\"gpu\":true,\"net\":{\"batch_size\":32},\"solver\":{\"test_interval\":500,\"iterations\":30000,\"base_lr\":0.001,\"stepsize\":1000,\"gamma\":0.9}},\"input\":{\"connector\":\"image\",\"test_split\":0.1,\"shuffle\":true,\"width\":224,\"height\":224},\"output\":{\"measure\":[\"acc\",\"mcll\",\"f1\"]}},\"data\":[\"/media/img\"]}"

When i switch async from 'true' to 'false' then i be able to see the output from the server log ...

ERROR - 13:28:28 - service imageserv mllib bad param: no image data found in repository ...

But the problem is i have imagine in /media/img 

https://www.dropbox.com/s/waicowmpkkxumzr/img.png?dl=0

**Comment by beniz** [comment]
The server basically tells you it cannot see the images in the repository. Check the repository permissions for a start.

**Comment by diepbang** [comment]
@beniz But i have set 777 permission for the folder already ... 
https://www.dropbox.com/s/2szklzmruesllkv/permission.png?dl=0

**Comment by diepbang** [comment]
It keep saying "ERROR - 14:39:53 - service imageserv mllib bad param: no image data found in repository " 
But i have image in the folder /media/img ... and the permission is 777

**Comment by beniz** [comment]
What is the filesystem of your /media/img partition ? See if #50 is related.

**Comment by diepbang** [comment]
@beniz ext4 ! Ubuntu 16.04 . Nope not related

**Comment by diepbang** [comment]
@beniz what should i do :((

**Comment by beniz** [comment]
You need to create repositories for classes in your training directory... If you are trying to classify cats and dogs, you need to create dogs and cats directories with related images in each of them.

**Comment by diepbang** [comment]
So this is working right ?
https://www.dropbox.com/s/fuqlpl2j2foolzn/trainn.png?dl=0

**Comment by diepbang** [comment]
Thanks a lot by the way ... By the way i have a question ? Can i do real-time train with your framework ? Like different users can upload different picture to train ?

**Comment by beniz** [comment]
> Like different users can upload different picture to train ?

Different users can upload pictures to *predict*, not train.

**Comment by diepbang** [comment]
@beniz can i do like user A create service A and train his data ... user B create service B and train his data . And each users can use the data they have trained to predict ?  Is it possible ? I know the preformance problem .... but is it possible if i have good server ?

**Comment by beniz** [comment]
You can do all what the API lets you do, it's for you to build the multi-user layer on top of dd. All what you are describing is possible yes.

**Comment by diepbang** [comment]
@beniz if each person can train 1 image at the time .. and i have 1000 users ..  how many RAM and CPU minimum i need to have ? I really want to know cause i have a idea ..... and i want to spread this framework to more people for you lol :D

**Comment by diepbang** [comment]
@beniz i just bought this server ... http://www.softlayer.com/info/high-performance-computing?utm_source=google&utm_medium=cpc&utm_content=GPU_-_GPU&utm_campaign=AP_-_ASEAN_-_English_-_Vietnam_-_Search_-_Google_-_HPC&utm_term=%2Bgpu&matchtype=b&_bt=95794983362&_bk=%2Bgpu&_bm=b&adgroup=GPU_-_GPU
....
Just curious if this server can handle 1000 users ... each user upload 1 image to train at the same time .. 
 - Dual Intel Xeon E5-2620 v3
 - NVIDIA Tesla K80
 - $1,359/mo

**Comment by beniz** [comment]
You'd need to run your own tests. This is not a software issue nor a bug, so please use [gitter](https://gitter.im/beniz/deepdetect) for this type of conversation.
