### ISSUE TITLE
Issue with Demo of ImageClassifier 

### ISSUE THREAD

**Issue by shrikantsawant** [beniz/deepdetect#150]
Trying to use the UI demo at https://github.com/beniz/deepdetect/tree/master/demo/imgdetect 
For the sample ambulance image ; the curl version of prediction works from command line. However, when I try to use the same image via the above installed Demo, it does not work and I get following error in dede server window : 

E0623 15:52:48.877213 26952 caffelib.cc:1840] exception while filling up network for prediction
INFO - 15:52:48 - Ignoring source layer loss3/loss3
ERROR - 15:52:48 - service imageserv prediction call failed

Working call :  curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3}},\"data\":[\"ambulance.jpg\"]}"

The only difference between these 2 ways of calling the predict service is that the curl version specifies height and width parameters of 224.

I tried to specify the same at deepdetect/demo/imgdetect/js/main.js as follows but it did not help : 

    var post_url = "/api/predict";
    var post_data = {
      service: $('#service_select').val(),
      parameters: {
        mllib: {gpu: true},
        width: 224,
        height: 224,
        output: {best: 3}
      },
      data: [$('input#url').val()]
    };

Any inputs on how do I get  this resolved and what else to check for ? 

Kind Regards,
Shrikant

**Comment by beniz** [comment]
You'd need to specify the hight and width parameters in the `PUT /services` call, still in the input connector.

**Comment by shrikantsawant** [comment]
Hi;
I did try including both height and width in deepdetect/demo/imgdetect/js/main.js; is there some other location that needs to be updated too ? 

var post_url = "/api/predict";
var post_data = {
  service: $('#service_select').val(),
  parameters: {
    mllib: {gpu: true},
    width: 224,
    height: 224,
    output: {best: 3}
  },
  data: [$('input#url').val()]
};

**Comment by beniz** [comment]
Read the API doc carefully, 
`"parameters":{"input":{"connector":"image","width":224,"height":224}`

**Comment by shrikantsawant** [comment]
Thanks - worked perfectly !
