### ISSUE TITLE
Output format of confusion matrix (cmfull) is confusing

### ISSUE THREAD

**Issue by danielgollas** [beniz/deepdetect#157]
The cmfull output when training a network seems to have strange behavior. 
After discussing on gitter, a compact and simple proposal for the output format is as follows:
cmfull is an object with two properties: labels and data. 
Labels is a list of strings that determine the edges of the matrix, and data as a list of lists of numbers to represent the rows, where each entry in the row corresponds to the label in the same index. 

E.g. A simple CM with 4 labels and an identity diagonal.
```
{
	"labels": ["label0", "label1", "label2", "label3"],
	"data": [
		[1, 0, 0, 0],
		[0, 1, 0, 0],
		[0, 0, 1, 0],
		[0, 0, 0, 1]
	]
}
```

**Comment by beniz** [comment]
Due to internal data structure constraints, the final format cannot exactly fit the one proposed above and discussed earlier. The new proposed format looks like:
```
"cmfull":
{

}
```

**Comment by beniz** [comment]
Due to internal data structure constraints, the final format cannot exactly fit the one proposed above and discussed earlier. The new proposed format looks like:
```
"cmfull":
{

}
```

**Comment by beniz** [comment]
Due to internal data structure constraints, the final format cannot exactly fit the one proposed above and discussed earlier. The new proposed format looks like:
```
"cmfull": [
          "label1":[1,0,0,0],
          "label2":[0,1,0,0],
           ...
   ]
```
Note that the keys in the `cmfull` array should now always be correctly ordered.

**Comment by beniz** [comment]
I know that this issue is of importance to some users, so I've made PR #158 readily available, even before discussion resumes.

**Comment by beniz** [comment]
I know that this issue is of importance to some users, so I've made PR #158 readily available, even before discussion resumes.

**Comment by danielgollas** [comment]
Wait, can a JSON array have named items? I can't seem to get the example format to validate on jsonlint.

**Comment by danielgollas** [comment]
It's kind of hacky but how about this:
```
"cmfull": [
{"label1":[1,0,0,0]},
{"label2":[0,1,0,0]},
...
]
```
Preserve the order of rows through the array, and each row is a super simple object with label as the key and row data as value. Or, it could be even more explicit and be 

It's kind of hacky but how about this:
"cmfull": [
{
  "label": "label1",
  "data": [1,0,0,0]
},
{
   "label":"label2",
   "data":[0,1,0,0]
},
...
]

**Comment by beniz** [comment]
As discussed, updated my earlier comment, the format should be fine.

**Comment by beniz** [comment]
merged
