### ISSUE TITLE
"full" deletion of a service leads to core dump

### ISSUE THREAD

**Issue by ArdalanM** [beniz/deepdetect#164]
Hello,

I followed the tutorial "Training a model from text" (http://www.deepdetect.com/tutorials/txt-training/). Creating and training the model works however, it leads to core dump when I am looking to "full" delete the service.

Step to reproduce (assuming news20 dataset is downloaded and DeepDetect is running):

1. Create the service (just like the tutorial and specify the model repository):

```
curl -X PUT "http://localhost:8080/services/n20" -d "{\"mllib\":\"caffe\",\"description\":\"newsgroup classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"txt\"},\"mllib\":{\"template\":\"mlp\",\"nclasses\":20,\"layers\":[200,200],\"activation\":\"relu\"}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\".../data/dd_models\"}}"
```

2. Delete the service:

```
curl -X DELETE "http://localhost:8080/services/n20?clear=full"
```

Result:

ERROR - 11:52:40 - service n20 mllib internal error: Failed deleting all files in directory .../data/dd_models
terminate called after throwing an instance of 'dd::MLLibInternalException'
  what():  Failed deleting all files in directory 
.../data/dd_models
[1]    32215 abort (core dumped)  ./main/dede

This does not happen when deletion is made with "lib" or "mem"

**Comment by beniz** [comment]
Doesn't crash for me... Tried with both relative and absolute path to the directory. What are the permissions on the repository and what is possibly inside ? What filesystem are on you on ?

**Comment by ArdalanM** [comment]
After some tests I can be more specific.

The 'dd_models' folder contains the following files **and** folder:

- deploy.prototxt  
- mlp.prototxt
- mlp_solver.prototxt 
- model.json
- dd_model_folder (this is a folder containing another DD model)

When I try to delete model in 'dd_models' it lead to core dump only if there is sub folders containing other DD models.

I guess this not a best practice to have sub folders of DD models :)

**Comment by beniz** [comment]
OK thanks, I'll try to reproduce FTR and to provide a fix. But yes, model directories should be managed by DD, and they do not include subdirectories other than the training and testing databases when applicable.

**Comment by beniz** [comment]
Thanks for bug report. The commit above fixes the exception catches and thus the server shall not crash anymore. However, the deletion of sub-directories within sub-directories will report a 500 error as the deletion only operates over a single depth (i.e. no recursivity). This is because in all cases, there shouldn't be the need for a repository that follows the DD structure.
