### ISSUE TITLE
Finetuning resnet

### ISSUE THREAD

**Issue by neo01124** [beniz/deepdetect#166]
I'm following the finetuning googlenet example from [here](http://www.deepdetect.com/overview/examples/) but I want to finetune a resnet_152 using the deepdetect templates. 

For the mllib params what should be the value of `weights`? 
```
parameters_mllib = {'template':'resnet_152','nclasses':nclasses,'finetuning':True,'rotate':False,'mirror':True,'weights':?}
```
If I need to download it from [here](https://github.com/KaimingHe/deep-residual-networks) does it need some modification and where should it be located in the deepdetect folder ?

**Comment by beniz** [comment]
Hi, issues are for mostly for bugs, building difficulties etc... can you please join us on gitter, https://gitter.im/beniz/deepdetect and ask your question there ?

Regarding the current question, it is straightforward to replace the GoogLeNet weights with that of resnet 152, and yes everything is withing the model folder.

**Comment by neo01124** [comment]
Thanks for linking to gitter.
I copied the *.prototxts (from the deepdetect template) and the downloaded .caffemodel in a seperate folder and finetuned it without using the template.
