### ISSUE TITLE
HTTP Server doesn't bind to port

### ISSUE THREAD

**Issue by thexeos** [beniz/deepdetect#168]
I've just installed DeepDetect from source ([following the instructions](http://www.deepdetect.com/overview/installing/)) on Ubuntu 14.04.3 LTS

Upon running ./main/dede I get

> DeepDetect [ commit a421d81c44ed51e761c5689e9210cbce502b53b3 ]
> Running DeepDetect HTTP server on localhost:8080

However checking active ports shows that DeepDetect is not bound to :8080 or any other port. When I hit Ctrl+C after a couple of seconds I get

> INFO - 15:29:01 - stopping HTTP server
> ERROR - 15:29:01 - Bad file descriptor
> ERROR - 15:29:01 - No associated state

The API, of course, is not reachable at localhost:8080.

**Comment by beniz** [comment]
Try `127.0.0.1` instead of localhost. You may have a system misconfiguration or ipv6 settings that confuse the binding.

**Comment by beniz** [comment]
Inactive for > 15 days, closing.
