### ISSUE TITLE
Issue when setting layers:[2] with the svm connector

### ISSUE THREAD

**Issue by ArdalanM** [beniz/deepdetect#173]
Hi,

I am facing a bug with the `svm` connector (cannot reproduce the issue with `text` connector):

Those API calls works:
- curl-X PUT "http://localhost:8080/services/test" -d "{\"mllib\":\"caffe\",\"description\":\"classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"svm\"},\"mllib\":{\"db\":true,\"template\":\"mlp\",\"nclasses\":2,\"**_layers\":[3]**_,\"activation\":\"relu\",\"dropout\":0.2}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"/path/to/model/folder\"}}"
- curl -X POST "http://localhost:8080/train" -d "{\"service\":\"test\",\"async\":true,\"parameters\":{\"mllib\":{\"gpu\":false,\"solver\":{\"iterations\":1000,\"test_interval\":500,\"base_lr\":0.1,\"solver_type\":\"ADAM\"},\"net\":{\"batch_size\":512}},\"input\":{\"db\":true},\"output\":{\"measure\":[\"mcll\",\"f1\",\"auc\"]}},\"data\":[\"/path/to/svm/file.svm\"]}"

Changing `layers:[3]` to `layers:[2]` will lead to core dump with the following trace:

INFO - 17:38:45 - Snapshotting to binary proto file .../model_iter_1000.caffemodel
**\* Error in `./main/dede': double free or corruption (!prev): 0x00007f3cd50d0e30 ***
INFO - 17:38:45 - Snapshotting solver state to binary proto file .../model_iter_1000.solverstate[1]    20611 abort (core dumped)  ./main/dede --port 8080

**Comment by beniz** [comment]
I can't reproduce, setting layers to 2 and 3 works fine in my setup. One thing you can do is remove the `-O2` in `deepdetect/CMakeLists.txt`, rebuild, and run:
```
libtool --mode=execute gdb ./dede
```
Then execute your instructions. When the crash happens, execute `bt` in gdb to get the backtrace, and post it here.

**Comment by YaYaB** [comment]
Hi,

I obtained a core dump when I was trying to train with parameters ``layers`` equal to ``[50]``. I was then able to replicate @ArdalanM's issue using ``layers`` set to ``[2]``
Then I did as you said and compile after removing  ``-02`` in ``deepdetect/CMakeLists.txt``.

Here what I obtained using gdb.

```
#0  0x00007ffff3f2b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff3f2d02a in __GI_abort () at abort.c:89
#2  0x00007ffff3f6d7ea in __libc_message (do_abort=2, 
    fmt=fmt@entry=0x7ffff4086e98 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff3f749dc in malloc_printerr (ar_ptr=0x7fff6c000020, ptr=0x7fff6c00d9d0, 
    str=0x7ffff4083c35 "corrupted size vs. prev_size", action=<optimized out>) at malloc.c:5006
#4  malloc_consolidate (av=av@entry=0x7fff6c000020) at malloc.c:4183
#5  0x00007ffff3f76678 in _int_free (av=0x7fff6c000020, p=<optimized out>, have_lock=0) at malloc.c:4075
#6  0x00007ffff3f7a53c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#7  0x00007ffff60bd09d in caffe::CaffeFreeHost (use_cuda=<optimized out>, ptr=<optimized out>)
    at ./include/caffe/syncedmem.hpp:37
#8  caffe::SyncedMemory::~SyncedMemory (this=0x7fff6c010960, __in_chrg=<optimized out>) at src/caffe/syncedmem.cpp:9
#9  0x00007ffff5dfaef2 in boost::checked_delete<caffe::SyncedMemory> (x=0x7fff6c010960)
    at /usr/include/boost/core/checked_delete.hpp:34
#10 boost::detail::sp_counted_impl_p<caffe::SyncedMemory>::dispose (this=<optimized out>)
    at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:78
#11 0x00007ffff5eb5349 in boost::detail::sp_counted_base::release (this=0x7fff6c055a40)
    at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:146
#12 boost::detail::shared_count::~shared_count (this=0x7fff60d9aa58, __in_chrg=<optimized out>)
    at /usr/include/boost/smart_ptr/detail/shared_count.hpp:443
#13 boost::shared_ptr<caffe::SyncedMemory>::~shared_ptr (this=0x7fff60d9aa50, __in_chrg=<optimized out>)
    at /usr/include/boost/smart_ptr/shared_ptr.hpp:323
#14 caffe::SparseBlob<float>::~SparseBlob (this=0x7fff60d9a9f8, __in_chrg=<optimized out>)
    at ./include/caffe/sparse_blob.hpp:28
#15 caffe::MemorySparseDataLayer<float>::~MemorySparseDataLayer (this=0x7fff60d9a5e0, __in_chrg=<optimized out>)
    at ./include/caffe/layers/memory_sparse_data_layer.hpp:20
#16 caffe::MemorySparseDataLayer<float>::~MemorySparseDataLayer (this=0x7fff60d9a5e0, __in_chrg=<optimized out>)
    at ./include/caffe/layers/memory_sparse_data_layer.hpp:20
#17 0x00007ffff5f74462 in boost::detail::sp_counted_base::release (this=0x7fff60d53f60)
    at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:146
```

**Comment by YaYaB** [comment]
Hello,

Since the PR #339, the issue does not appear anymore. It seems to have corrected it.
