### ISSUE TITLE
Prediction fails for ResNet-50 - outputs the default class

### ISSUE THREAD

**Issue by alkamid** [beniz/deepdetect#178]
I'm running deepdetect on an AWS AMI shared by revikoleb, with source files updated to the current version (`git pull`) and rebuilt. Following the tutorial for setting up an image classifier, I'm starting dede and using the following Python script:

```
from dd_client import DD
dd = DD('localhost')
dd.set_return_format(dd.RETURN_PYTHON)
description = 'image classification service'
mllib = 'caffe'
model = {'templates':'../templates/caffe/','repository':'../../models/imgnet'}
parameters_input = {'connector':'image'}
parameters_mllib = {'weights':'resnet_50','nclasses':1000}
parameters_output = {}
dd.put_service('imageserv',model,description,mllib,
               parameters_input,parameters_mllib,parameters_output)
```
(I changed `template` to `weights` in `parameters_mllib` after reading #116)
Output:
```
{u'status': {u'code': 201, u'msg': u'Created'}}
```

```
#prediction:

data = ['http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg']
parameters_input = {'width':224,'height':224}
parameters_mllib = {'gpu':True}
parameters_output = {'best':3}
dd.post_predict('imageserv',data,parameters_input,parameters_mllib,parameters_output)
```

This is the output:
```
{u'body': {u'predictions': {u'classes': {u'cat': u'n01440764 tench, Tinca tinca',
    u'last': True,
    u'prob': 0.0010000000474974513},
   u'uri': u'http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg'}},
 u'head': {u'method': u'/predict', u'service': u'imageserv', u'time': 575.0},
 u'status': {u'code': 200, u'msg': u'OK'}}
```

It seems to be the same error as in #58 but @beniz said in #84:

> At the moment, doing a quick image classification test on a single image prediction task, the resnet_50 takes 302MB out of 12GB on a K40, as reported by `nvidia-smi`.

And since I'm running on the 4GB AWS GPUs (g2.8xlarge instance), memory shouldn't be a problem here.

**Comment by beniz** [comment]
Try with `gpu:false` and see whether it works.

**Comment by alkamid** [comment]
It doesn't. I'm getting exactly the same result, including the 'prob'.

**Comment by beniz** [comment]
what's the commit hash reported by the server on an `info` call ?

**Comment by alkamid** [comment]
`u'commit': u'9000ad8f01fb30fda191dd261b3e4ae64a0cefcf'`

**Comment by beniz** [comment]
Try to edit the `resnet_50.prototxt` and `deploy.prototxt` and set all `batch_size` to 1, then retry the whole sequence.

**Comment by alkamid** [comment]
Same thing, both with `gpu:True' and 'False`.

**Comment by alkamid** [comment]
By the way, when I execude `dd.post_predict()`, the server spits out these messages: https://gist.github.com/alkamid/e6087cdb862d991b0e90f3309df33edc. I don't know if it's relevant, but the use of `bvlc_googlenet.caffemodel` weights is somewhat confusing.

**Comment by beniz** [comment]
It works for me, just checked out of completness. So, let's review a few points:

- What's the exact name of the `weight` file in the model repository ? Obviously you are using GoogLeNet instead: `Using pre-trained weights from ../../models/imgnet/bvlc_googlenet.caffemodel`
Following http://deepdetect.com/tutorials/imagenet-classifier/ it should be something like `weights:ResNet-50-model.caffemodel`

- Use absolute path for `repository`, at the moment it seems you are not using the model you believe you are using

**Comment by alkamid** [comment]
Thanks, it's working now. Do you accept contributions to dd's docs? I think `weights` should be mentioned in the "Setup of an image classifier" section — I only learned about this parameter from other issues. Also, the files in `models/` seem to be misplaced: weights are in `imgnet_resnet50` folder, and `.prototxt` files are in `imgnet` folder. But I suppose this was the decision of the AMI's creator and is outside of dede's scope.

**Comment by beniz** [comment]
sure we do. we have on git but haven't got it public yet. So as for now if you can list modifications, we'll make the update. Thanks.

**Comment by beniz** [comment]
Keep in mind this AMI is unsupported. If you have an updated one, you can share it. We need our own but got sidetracked. It's gonna happen though.

**Comment by alkamid** [comment]
In terms of improving the docs, I think it would be sufficient to change:

```
         "mllib":{
           "template":"googlenet",
           "nclasses":1000
         }
```
to
```
         "mllib":{
           "template":"googlenet",
           "nclasses":1000,
           "weights":"bvlc_googlenet.caffemodel"
         }
```

and

```
parameters_mllib = {'template':'googlenet','nclasses':1000}
```
to
```
parameters_mllib = {'template':'googlenet','nclasses':1000,'weights':'bvlc_googlenet.caffemodel'}
```

in "Setup of an image classifier" -> "Setting up the DeepDetect service", in the curl and Python snippets respectively. Changing it in "Examples" -> "GoogleNet for image classification" would be nice, too.

It doesn't matter for `googlenet` because it seems the weights default to this model, but it's hard to see that you have to add "weights" if you're using another model.
