### ISSUE TITLE
Add support for a `best: all` output connector parameter

### ISSUE THREAD

**Issue by nrinaudo** [beniz/deepdetect#181]
In my current project, I always need to know the probability for all classes, regardless of the number of classes, during prediction.

It'd be nice to be able to write something like:

```json
"output": {
  "best": "all"
}
```

**Comment by beniz** [comment]
Let's use `best=-1`.

**Comment by marcreichman** [comment]
This seems to only work with caffe-based models. I have found it doesn't work (just returns no classes) with TF-based models.

**Comment by beniz** [comment]
@marcreichman  thanks, if it doesn't work with TF models, that's a bug, you can open a dedicated issue and it'll get fixed quickly.

**Comment by marcreichman** [comment]
Will do, building it now and will let you know shortly. Thanks for the quick turnaround!

**Comment by beniz** [comment]
#238 with an additional fix clears the problem, merged. @marcreichman thanks for catching it.

**Comment by marcreichman** [comment]
Actually getting this compile error now:
```

/opt/deepdetect/src/tflib.cc:412:5: error: 'class dd::UnsupervisedOutput' has no member named 'add'
     tout.add("nclasses",nclasses);
```

**Comment by marcreichman** [comment]
Fix is verified, thanks for the quick turnaround!
