### ISSUE TITLE
errors while running 'make'  caffe/proto/caffe_pretty_print.pb.h: No such file or directory

### ISSUE THREAD

**Issue by devareddy** [beniz/deepdetect#183]

**Comment by beniz** [comment]
Hi, you need to give more details, OS, sequence of calls, output of `cmake ..` and `make VERBOSE=1`. Thanks.

**Comment by devareddy** [comment]
Hi,
Have beeing trying to resolve build isues on Ubuntu 14.04, CUDA 6.5, g++-4.8.
After many errors, its ending with following out put.
Request your help.
make[3]: *** [.build_release/src/caffe/data_reader.o] Error 1
In file included from src/caffe/net.cpp:18:0:
/home/user/include/caffe/util/upgrade_proto.hpp:7:47: fatal error: caffe/proto/caffe_pretty_print.pb.h: No such file or directory
 #include "caffe/proto/caffe_pretty_print.pb.h"
                                               ^
compilation terminated.
make[3]: *** [.build_release/src/caffe/net.o] Error 1
make[2]: *** [caffe_dd/src/caffe_dd-stamp/caffe_dd-configure] Error 2
make[1]: *** [CMakeFiles/caffe_dd.dir/all] Error 2
make: *** [all] Error 2

make: *** [all] Error 2

**Comment by beniz** [comment]
Please include the full `cmake` output. You are very certainly missing the `protobuf-dev` and `protobuf-compiler` packagese.

**Comment by devareddy** [comment]
Please find the cmake output below for your reference
user@user-desktop:~/deepdetect/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/gcc-4.8
-- Check for working C compiler: /usr/bin/gcc-4.8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-4.8
-- Check for working CXX compiler: /usr/bin/g++-4.8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   iostreams
-- CUDA detected: 6.5
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50
-- OpenCV 2 (2.4.8) found (/usr/share/OpenCV)
-- Configuring customized caffe
-- Configuring XGBoost
-- Build Tests          : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/deepdetect/build

**Comment by beniz** [comment]
Check that you have the two `protobuf` libraries installed.

**Comment by devareddy** [comment]
-Ran following command from the deep detect website
sudo apt-get install build-essential libgoogle-glog-dev libgflags-dev libeigen3-dev libopencv-dev libcppnetlib-dev libboost-dev libboost-iostreams-dev libcurlpp-dev libcurl4-openssl-dev **protobuf-compiler** libopenblas-dev libhdf5-dev **libprotobuf-dev l**ibleveldb-dev libsnappy-dev liblmdb-dev libutfcpp-dev

Which one shall i remove? Any suggestion please!

**Comment by beniz** [comment]
@devareddy there's no `caffe/proto/caffe_pretty_print.pb.h` file in our Caffe repository nor in the original one. I don't know what you are doing exactly, but my guess is that you are using an unsupported version of Caffe, in your `/home/user/include/caffe/` repository. Caffe for DD is located into `build/caffe_dd/src/caffe_dd`.

**Comment by devareddy** [comment]
Caffe got after running make command.. 
downloading...
     src='https://github.com/beniz/caffe/archive/master.tar.gz'
     dst='/home/user/deepdetect/build/caffe_dd/src/master.tar.gz'
     timeout='none'

**Comment by devareddy** [comment]
Thanks beniz, progressed after restating server but with following error.
Any help!

canning dependencies of target ddetect
[ 40%] Building CXX object src/CMakeFiles/ddetect.dir/deepdetect.cc.o
In file included from /home/user/deepdetect/src/caffeinputconns.h:27:0,
                 from /home/user/deepdetect/src/imginputfileconn.h:343,
                 from /home/user/deepdetect/src/services.h:29,
                 from /home/user/deepdetect/src/apistrategy.h:26,
                 from /home/user/deepdetect/src/deepdetect.h:25,
                 from /home/user/deepdetect/src/deepdetect.cc:22:
/home/user/deepdetect/src/txtinputfileconn.h:28:18: fatal error: utf8.h: No such file or directory
 #include "utf8.h"
                  ^
compilation terminated.
make[2]: *** [src/CMakeFiles/ddetect.dir/deepdetect.cc.o] Error 1
make[1]: *** [src/CMakeFiles/ddetect.dir/all] Error 2
make: *** [all] Error 2

**Comment by beniz** [comment]
Maybe you need to install `libutfcpp-dev`. Usually it is automatically installed.

**Comment by devareddy** [comment]
Thanks a lot. I had to install libutfcpp-dev manually it proceeded further but stopped at 95%
[ 36%] Built target caffe_dd
[ 95%] Built target ddetect
Linking CXX executable dede
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libopenblas.so when searching for -lopenblas
/usr/bin/ld: warning: libopenblas.so.0, needed by /home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_sgemv'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_dgemm'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_sscal'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_dgemv'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_dasum'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_dscal'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_scopy'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_daxpy'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_dcopy'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_saxpy'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_ddot'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_sgemm'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_sasum'
/home/user/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cblas_sdot'
collect2: error: ld returned 1 exit status
make[2]: *** [main/dede] Error 1
make[1]: *** [main/CMakeFiles/dede.dir/all] Error 2
make: *** [all] Error 2
Openbals dev & base are installed.
Can you please help me in resolving this?
-Deva

**Comment by beniz** [comment]
You are not reading the docs obviously, nor installing the packages the README and Install page tell you to install. Take your time follow instructions and it will work flawlessly. Also carefully read the linker output above and you'll see the machine tells you what to do.

**Comment by devareddy** [comment]
Installation done , Thanks for the great support.

**Comment by beniz** [comment]
good :)
