### ISSUE TITLE
Running DeepDetect HTTP server on localhost:8080 but ERROR - 23:24:09 - Error opening socket.

### ISSUE THREAD

**Issue by devareddy** [beniz/deepdetect#185]
Hi beniz,
while running ./main/dede , am getting following error.
eepDetect [ commit 0942a80664fbaad446d8e894e4556832ab36e147 ]
Running DeepDetect HTTP server on localhost:8080

ERROR - 23:24:09 - Error opening socket.
terminate called recursively
Aborted (core dumped)

Request you to help me in resolving this issue.
-D

**Comment by dgtlmoon** [comment]
something else already running on 8080? how are you starting it exactly? with docker? compiled?

**Comment by devareddy** [comment]
Starting by running  ./main/dede from build directory.
it's compiled!

**Comment by beniz** [comment]
This type of questions should go to https://gitter.im/beniz/deepdetect please. Issues are for bugs, enhancements, etc...
