### ISSUE TITLE
SVM format error : "negative supervised discrete target"

### ISSUE THREAD

**Issue by EBazarov** [beniz/deepdetect#194]
When I try to use SVM file with format like this : [a1a.svm](http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a1a)

DeepDetect gives me error on training phase :  
```
ERROR - 11:39:58 - service a1a training status call failed

ERROR - 11:39:58 - {"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"negative supervised discrete target (e.g. wrong use of label_offset ?"}
```

As I understood it have something to deal with parsing labels like `-1` and `+1` 

Data was taken from site : [LIBSVM Data: Classification (Binary Class)](http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a1a) 

I can rename labels in SVM, for example to `0` and `1`, but I think DD should handle cases like that. 

EDIT: tried with renamed labels, it works.

**Comment by beniz** [comment]
You can't use negative discrete labels because the softmax would not work. You need to start from 0 and up. The `csv` connector has a `label_offset` parameter because of this. We could set the same for the `svm` connector, but you can solve uour issue immediately by starting the labels at 0.

**Comment by EBazarov** [comment]
Exactly, I have used `0` and `1` for predictions, maybe have a `label_offset` feature not a bad idea. I have solved my problem by loading and relabeling, but maybe for somebody it will be not so easy as for me. Thanks

**Comment by beniz** [comment]
But the `offset` would not allow to use +1/-1 as label, it needs to be a discrete numbering starting from 0 and with 1 as increment.

**Comment by beniz** [comment]
Added to FAQ. There's nothing more here to do I believe, labels must be between [0,N] with N the number of classes.
