### ISSUE TITLE
Compiling inside Vagrant: undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'

### ISSUE THREAD

**Issue by estebansiravegna** [beniz/deepdetect#198]
Hey, it's me again. Now, trying to do a make inside a Vagrant VM got this error:

```bash
make: *** Waiting for unfinished jobs....
.build_release/tools/compute_image_mean.o: In function `main':
compute_image_mean.cpp:(.text.startup+0x34e): undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
compute_image_mean.cpp:(.text.startup+0x4fa): undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
collect2: error: ld returned 1 exit status
```
I'm not using CuDNN, and obviously running the CPU-only scenario. The VM does run an Ubuntu 14.04, with gcc/g++/cpp 4.8.4

For what I've seen this error is related with an old devel branch of Caffe, so I'm totally puzzled.

**Comment by beniz** [comment]
Not familiar with Vagrant, but since this looks like a Caffe building error, please post the whole `cmake` output, then the `make VERBOSE=1` output, here or in a gist. Thanks.

**Comment by Esiravegna** [comment]
[Cmake](https://gist.github.com/estebansiravegna/34e618564030f5b15b864a0b6c21ffc2) and [Build log](https://gist.github.com/estebansiravegna/f10d7a4928527bce9dcf9bcebf8257dd) as requested, thanks a lot.

**Comment by estebansiravegna** [comment]
Tried OpenCV 2.4.11, and 3.1, same error. Completely in the dark here.

**Comment by beniz** [comment]
DD+Caffe builds daily on our machines and this error doesn't look familiar. This is a Caffe error, look at the pointed code. While this file is not needed for DD + Caffe, a Caffe build error somewhere is usually a bad omen.

**Comment by beniz** [comment]
I've looked at it closely and it doesn't make much sense, the `ReadImageToDatum` is not within the scope of any `#define`, so unlikely to be a build error there. Again, something in your VM is not like the reference platform.

Have you considered running a docker instance instead ?

**Comment by Esiravegna** [comment]
Will try, thanks so much for your response.

**Comment by MugahedEzzi** [comment]
Check if you already have caffe installed somewhere.
