### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by estebansiravegna** [beniz/deepdetect#199]
I got that response always when querying from the browser (for instance, localhost:8823/info) or the demo imgdetect (on the ajax query).

However, a curl -x works just fine.

**Comment by estebansiravegna** [comment]
OTOH, the errors message runs just fine:
```json
{
status: {
code: 404,
msg: "NotFound"
}
}
```

**Comment by estebansiravegna** [comment]
...and it seems that the headers are right. Really weird.
```bash
± |master U:1 ?:6 ✗| → curl -vX GET "http://localhost:8823/info"
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.124...
* Connected to valiant (192.168.1.124) port 8823 (#0)
> GET /info HTTP/1.1
> User-Agent: curl/7.35.0
> Host: valiant:8823
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Length: 160
< Content-Type: application/json
<
* Closing connection 0
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"8ce5c24b5b22879cebcddd9ade759b3835323277","services":[]}}

```

**Comment by estebansiravegna** [comment]
Definitely is related with the [PR 180](https://github.com/beniz/deepdetect/pull/180). On browsers on which I cannot disable the gzip accept encoding, i got that error. However, on firefox, works like a charm after disabling gzip.

**Comment by Esiravegna** [comment]
Commenting the blocks starting [here|https://github.com/beniz/deepdetect/blob/master/src/httpjsonapi.cc#L190] and [here|https://github.com/beniz/deepdetect/blob/master/src/httpjsonapi.cc#L202], and thus disabling the gzip encoding, solved the error. Obviously, not the solution, but it works now.

**Comment by beniz** [comment]
Thanks for the report, this is now fixed on `master`.
