### ISSUE TITLE
Help to decrease GPU RAM when predict images 

### ISSUE THREAD

**Issue by ntamvl** [beniz/deepdetect#201]
Hi @beniz
I have an issue when predict an image that GPU usually take about 1.2GB to 1.5GB RAM GPU. I have a question: Can I reduce to save GPU RAM when predict an image?
(I'm using EC2 g2.2xlarge)

Thanks!

**Comment by beniz** [comment]
GPU RAM usage is tied to the model in use and the number of images passed to the prediction at once. the `squeezenet` models are designed to be less memory hungry while still yielding good results.

**Comment by ntamvl** [comment]
Thank so much @beniz. I will try to train the squeezenet models 👍

**Comment by beniz** [comment]
Try to use [gitter](https://gitter.im/beniz/deepdetect) for questions.
