### ISSUE TITLE
Error: cannot find -lopencv_dep_cudart

### ISSUE THREAD

**Issue by vj-1988** [beniz/deepdetect#212]
I am getting this error while compiling deepdetect.

[100%] Linking CXX executable dede
/usr/bin/ld: cannot find -lopencv_dep_cudart
collect2: error: ld returned 1 exit status
main/CMakeFiles/dede.dir/build.make:132: recipe for target 'main/dede' failed
make[2]: *** [main/dede] Error 1
CMakeFiles/Makefile2:177: recipe for target 'main/CMakeFiles/dede.dir/all' failed
make[1]: *** [main/CMakeFiles/dede.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have installed opencv 2.4.13 with cuda enabled.

**Comment by beniz** [comment]
Hi, you need to give more information on the system your a building on, its version, etc...

**Comment by vj-1988** [comment]
I have Ubuntu 16.04 with cuda 8.0 and cudnn 5.1.

**Comment by beniz** [comment]
Thanks. I'm not aware of this problems and our machines are running the same software version as yours. However, a quick googling returns https://github.com/opencv/opencv/issues/6542#issuecomment-219363375 
Have you tried this potential solution ?

**Comment by vj-1988** [comment]
I tried your suggested solution. But strangely, this didn't work for me as well. So I have used docker image.
