### ISSUE TITLE
Docker Image installation

### ISSUE THREAD

**Issue by gtsoumis** [beniz/deepdetect#214]
Hello. I am trying to install a docker image but I have an issue. After running the example classification and getting proper results I do not know how to continue towards the image classification service set up as described on you website. Mainly I cannot find the proper directories.

**Comment by beniz** [comment]
Not sure what you mean by proper directories, but I suggest you read a tutorial about docker and the mini documentation here, https://github.com/beniz/deepdetect/tree/master/docker.
It is better to keep issues for bugs and functionalities, for common questions and difficulties, use the chat on gitter, https://gitter.im/beniz/deepdetect.
