### ISSUE TITLE
Error while building dd branch of Caffe

### ISSUE THREAD

**Issue by mrgloom** [beniz/deepdetect#217]
I try to build dd branch of Caffe https://github.com/beniz/caffe 

`cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 .. -DUSE_CUDNN=ON`

But get an error:
~~~
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adam_solver.cu.o
/home/myuser/Downloads/caffe-dd/caffe/include/caffe/llogging.h(29): error: identifier "snprintf" is undefined
~~~

`gcc --version`
~~~
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
~~~

**Comment by beniz** [comment]
This is not the right place. However, if for whatever reason you need a build of the Caffe backend, just follow dd build procedure and the Caffe build will be found in `build/caffe_dd/src/caffe_dd.

**Comment by mrgloom** [comment]
Sorry, but seems https://github.com/beniz/caffe have no issues tracker.

I was following this build instruction https://github.com/beniz/deepdetect#default-build-with-caffe

This works https://deepdetect.com/overview/installing/, seems it use not fresh master but some release\tag.
~~~
$ git clone https://github.com/beniz/deepdetect.git
$ cd deepdetect
$ mkdir build
$ cd build
$ cmake ..
$ make
~~~

**Comment by beniz** [comment]
It's an automated build, the instructions don't change that. I think you should not specify the cuda root dir, as it's automatically detected. Wasn't aware of the lack of issue tracker on the custom Caffe, apologies about that.
