### ISSUE TITLE
Best argument overwritten when predicting

### ISSUE THREAD

**Issue by Conchylicultor** [beniz/deepdetect#219]
This command will return predictions for every classes (1000 instead of 5) even if "best":5 has been set.
```
curl -X POST 'http://localhost:8080/predict' -d '{
       "service":"test_caffe_classification",
       "parameters":{
         "output":{
           "best":5
         }
       },
       "data":["http://www.dogbreedinfo.com/images26/LabradorRetrieverBlackPurebredDogSonny8YearsOldTim1.JPG"]
     }'
```
I think this is because of:
*  https://github.com/beniz/deepdetect/blob/master/src/caffelib.cc#L2272
*  https://github.com/beniz/deepdetect/blob/master/src/supervisedoutputconnector.h#L197
*  https://github.com/beniz/deepdetect/blob/master/src/supervisedoutputconnector.h#L154

**Comment by beniz** [comment]
Ha good catch, you can add a test for `bbox` before the `out.add` in Caffe lib.cc and PR, or I'll do it asap. Thanks!

**Comment by beniz** [comment]
Thanks, this should have been captured by the tests, bad coverage I guess :/
