### ISSUE TITLE
Yolo & GenerativePredictableVoxels

### ISSUE THREAD

**Issue by roscopecoltran** [beniz/deepdetect#222]
Hi,

Is Deepdetect able to import [YOLO](https://github.com/yjmade/YOLO_tensorflow) (TF import, https://github.com/yjmade/YOLO_tensorflow) or [GenerativePredictableVoxels](https://github.com/rohitgirdhar/GenerativePredictableVoxels) ?

Richard

**Comment by beniz** [comment]
DD supports SSD for object recognition. AFAIK this is better and faster than YOLO but I may be missing some new SSD development. Look at the object detector tutorial if you haven't already.

There is no anchor for generative model at the moment.
