### ISSUE TITLE
Problem using multiple GPUs on a pretrained model

### ISSUE THREAD

**Issue by supaggregator** [beniz/deepdetect#224]
Hello, I have tried to set the gpuid parameter but it looks like not accepting array (pass a array parameter) :
`curl -XPUT "$DD_URL/services/buildings" -d "{\"mllib\":\"caffe\",\"description\":\"buildiings classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"gpu\":$GPU,\"gpuid\":[1, 2],\"template\":\"buildings\",\"nclasses\":185}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"../../models/buildings\"}}"`

Error message : 
`{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"in get()"}}`

Then I tried a specific gpuid number to create the prediction service(from pretrained model) : 
`curl -w -XPUT "$DD_URL/services/buildings" -d "{\"mllib\":\"caffe\",\"description\":\"buildiings classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"gpu\":$GPU,\"gpuid\":2,\"template\":\"buildings\",\"nclasses\":185}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"../../models/buildings\"}}"` 
`{"status":{"code":201,"msg":"Created"}}`

When I call the prediction service :
`curl -XPOST "$DD_URL/predict" -d "{\"service\":\"$service\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":5}},\"mllib\":{\"gpu\":true, \"gpuid\": 2},\"data\":[\"https://static.pexels.com/photos/6548/cold-snow-winter-mountain.jpeg\"]}"` 
Error:
`{
  "status": {
    "code": 500,
    "msg": "InternalError",
    "dd_code": 1007,
    "dd_msg": "src/caffe/layers/cudnn_conv_layer.cu:28 / Check failed (custom): (status) == (CUDNN_STATUS_SUCCESS)"
  }
}
` 
On the other hand, if I doesn't use gpuid parameter, deepdetect work without problem(creation and prediction).
My CUDA version : `Cuda compilation tools, release 7.5, V7.5.17`.
I use the latest version of deepdetect and my gpu info : 
`$ nvidia-smi      
+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 352.63         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:04.0     Off |                  N/A |
| N/A   36C    P0    42W / 125W |    234MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GRID K520           Off  | 0000:00:05.0     Off |                  N/A |
| N/A   33C    P8    17W / 125W |     11MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GRID K520           Off  | 0000:00:06.0     Off |                  N/A |
| N/A   33C    P0    42W / 125W |    207MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2407    C   ./dede                                         222MiB |
|    2      2407    C   ./dede                                         195MiB |
+-----------------------------------------------------------------------------+
`
Thanks in advance.

**Comment by beniz** [comment]
Can you share the output of an `info` call or the intial log from the server, with the commit number ?

**Comment by supaggregator** [comment]
Hi beniz, I know where came from the problem. 
I didn't properly create the pre-trained model service.
My bad, sorry for bothering you...

You can close the issue, thanks.
