### ISSUE TITLE
Unable to build - Failed with CurlPP

### ISSUE THREAD

**Issue by deepakkumar1984** [beniz/deepdetect#229]
Followed all steps as mentioned in the document. Getting the following exception: 

[ 41%] Linking CXX static library libddetect.a
[ 91%] Built target ddetect
[ 95%] Linking CXX executable dede
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::OptionContainer(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/usr/include/curlpp/internal/OptionContainer.inl:38: undefined reference to `curlpp::internal::SList::SList(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::getValue()':
/usr/include/curlpp/internal/OptionContainer.inl:59: undefined reference to `curlpp::internal::SList::operator std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >[abi:cxx11]()'
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::setValue(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/usr/include/curlpp/internal/OptionContainer.inl:52: undefined reference to `curlpp::internal::SList::operator=(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
collect2: error: ld returned 1 exit status
main/CMakeFiles/dede.dir/build.make:159: recipe for target 'main/dede' failed
make[2]: *** [main/dede] Error 1
CMakeFiles/Makefile2:177: recipe for target 'main/CMakeFiles/dede.dir/all' failed
make[1]: *** [main/CMakeFiles/dede.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
deepak@deepak-linux:~/git/deepdetect/build$ 

Please let me know if you have any ideas??

**Comment by beniz** [comment]
Check #126 out if you are using 16.04.

**Comment by deepakkumar1984** [comment]
Thanks Champ.... Able to build successfully.
