### ISSUE TITLE
Train ssd_300 Message type "caffe.TransformationParameter" has no field named "distort_param" 

### ISSUE THREAD

**Issue by abhiguru** [beniz/deepdetect#233]
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 29:19: Message type "caffe.TransformationParameter" has no field named "distort_param".
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 935:9: Message type "caffe.PriorBoxParameter" has no field named "step".

ssd300 templates dir content 
deploy.prototxt - https://gist.github.com/abhiguru/9faeb243f0f023adc30af6fa50873e6b
ssd_300.prototxt - https://gist.github.com/abhiguru/cd552ea87e3245e04a630c31d6af43a3
and the solver file named ssd_300_solver.prototxt 

The service creation call does return 200

**Comment by beniz** [comment]
Prediction only at the moment, remove your ssd_300.protoxt file. If it's from our VOC tarball, it shouldn't be there.

**Comment by abhiguru** [comment]
Actually I was trying to figure out why it was not being created and when I added the train and solver it got created but with error. I removed them for now but am getting the error back again about missing model template file does the nclasses value in mllib have to be 1000 ?

**Comment by beniz** [comment]
Templates are simply a way to setup a service around an existing neural net architecture. When you already have a `deploy.prototxt` file and a pre-trained model, there's no reason to use a template since you already have a neural net architecture specified. Please follow the [object detector tutorial](https://deepdetect.com/tutorials/object-detector/) if you haven't done it yet, it should work without difficulty.

**Comment by abhiguru** [comment]
Is there a defined process for importing other models from caffe zoo to form neural nets for deepdetect in addition to what has been imported ?

**Comment by beniz** [comment]
The FAQ has a 'How to import a model from Caffe into DeepDetect' section.

**Comment by beniz** [comment]
This should now work fine, the distortion has been merged into our custom Caffe backend. Reopen if the issue persists.

**Comment by cavalleria** [comment]
@abhiguru same problem have you solved it!

**Comment by beniz** [comment]
You are very probably using an outdated version of Caffe. You can remove the distort section also.
