### ISSUE TITLE
Sparse Layer

### ISSUE THREAD

**Issue by marifnst** [beniz/deepdetect#243]
hi all

is it possible if i take your sparse layer code only to be integrated other algorithm like SSD and Faster R CNN ?
any suggestion ?

thanks

**Comment by beniz** [comment]
Hi, our customized version of Caffe (https://github.com/beniz/caffe) has support for both sparse inputs and SSD. However, I'm not sure I see how sparse inputs could benefit SSD: sparse inputs are in practice useful for encoding text and for sparse data in general. Images are plain matrices unless you are using some special format, and maybe in this case it may apply.

**Comment by marifnst** [comment]
hi @beniz 

thank you very much for your answer.
after investigating your code, i conclude that your sparse layer only support for your sparse data ? is it right ?
so if my input is image (not in sparse format), your code will forward to original innerproduct code?

thanks

**Comment by beniz** [comment]
I believe you may be confusing sparse layer and sparse weights. Our sparse layer is for sparse inputs and supports any sparse data. DD uses SVM format for sparse inputs but that's independent of the layer.
If your input is not sparse, you might be looking for sparse weights, which is an area of research of its own. We do not officially support sparse weights at the moment.
