### ISSUE TITLE
Demo imgdetect with Nginx setup does not return predict result.

### ISSUE THREAD

**Issue by liankui** [beniz/deepdetect#244]
Build DeepDetect on Jan 25th 2016 from Git.  service creation and prediction from curl works perfectly.  And prediction from the /deepdetect/demo/imgdetect demo from the web does not return any prediction result even the nginx console log is good as shown below.  The same issue can be duplicated from direct build on the Ubuntu 14.4 or from the Docker CPU image.

There is no error from Chrome or IE on the WebSite.  Classify button has clock turning all the time.

here is main.js file
=========
    var post_url = "/api/predict";
    var post_data = {
      service: $('#service_select').val(),
      parameters: {
        mllib: {gpu: false},
        output: {best: 3}
      },
      data: [$('input#url').val()]
    };

Thank you very much for your help.
==========================

INFO - 04:54:55 - 127.0.0.1 "POST /predict" 200 2

  
 curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\",\"width\":224,\"height\":224},\"mllib\":{\"nclasses\":1000}},\"model\":{\"repository\":\"/home/wxg/deepdetect/models/imgnet/\"}}"
{"status":{"code":201,"msg":"Created"}}

curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3},\"mllib\":{\"gpu\":false}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"
{"status":{"code":200,"msg":"OK"},"head":{"method":"/predict","service":"imageserv","time":1468.0},"body":{"predictions":[{"uri":"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg","classes":[{"prob":0.22551338374614716,"cat":"n03868863 oxygen mask"},{"prob":0.20917671918869019,"cat":"n03127747 crash helmet"},{"last":true,"prob":0.07399303466081619,"cat":"n03379051 football helmet"}]}]}}wsun@deeplearningdetect03:~$ curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3},\"mllib\":{\"gpu\":false}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"

I
INFO - 04:54:38 - 127.0.0.1 "GET /info" 200 0

INFO - 04:54:55 - 127.0.0.1 "POST /predict" 200 2

I

**Comment by beniz** [comment]
Hi, I don't exactly understand what your problem is and can't make sense of the mixed API calls and server output you are providing (where's the info call from?). Do you mean that your second `curl -X POST` call does not return ?

We can't debug JS for you, it is very likely you have misconfigured your nginx between your frontend and the DD server.

**Comment by liankui** [comment]
Thank you very much, Beniz. 

My second curl  "curl -X POST" returns perfectly.  And frontend nginx server is configured the exactly as demo README.md.   and DD server is working great from curl command. and DD server log also indicates correct prediction status like the curl command.   I am using the same image on the curl command and from the demo web page and tested from different images.   The DD log shows the exact message. No errors at all.   If you can point me to the right direction to debug the issue, I would greatly appreciate it. 

Thank you very much for your help.

**Comment by beniz** [comment]
We'll look it up, thanks.

**Comment by liankui** [comment]
I also did the packet capture, checked NGINX log,  they are all look good.  I also went through every link on the page and test them good so to make sure nginx is configured right.   The image displays "./images/loading.gif".   dede console log is also fine.   Thank you very much for your help.

**Comment by beniz** [comment]
Thanks for the report, this is now fixed.

**Comment by liankui** [comment]
Thank you very much for your help, Emmanuel!

Great Job!

Have a nice weekend!

William Sun
Sr. Principle, Software Arch..
CoreLogic

Direct 9492140501
wsun@corelogic.com<mailto:wsun@corelogic.com>

corelogic.com<http://www.corelogic.com/> |  Blog<http://www.corelogic.com/blog/default.aspx>
LinkedIn<http://www.linkedin.com/company/corelogic>  |  Twitter<http://twitter.com/corelogicinc> |  Facebook<http://www.facebook.com/CoreLogic>  |  Google+<https://plus.google.com/114618839782139347829>

Our Vision: Deliver unique property-level insights that power the global real estate economy
