### ISSUE TITLE
Inception network with Tensorflow - example not working

### ISSUE THREAD

**Issue by alotov-agina** [beniz/deepdetect#247]
Hi,
I'm using the GPU docker image, and tried to follow the instructions as mentioned [here](https://deepdetect.com/overview/examples/#inception-network-with-tensorflow:9ecc00cd7c4c5bc9e8febc4fe00186bf). Unfortunately, the create-service-call already fails with the following response:

`{"status":{"code":404,"msg":"NotFound","dd_code":1000,"dd_msg":"Unknown Library"}}`

Apart from exchanging the path to the inception model there is nothing else mentioned which needs configuration. "Unknown library" sounds like the server is not aware of tensorflow at all.

What could have possibly gone wrong here?

**Comment by beniz** [comment]
You need to build deepdetect with support for `tensorflow`, see the main README.md. If you are using docker, the docker builds do not support tensorflow, the pre-built AMIs do.

**Comment by alotov-agina** [comment]
Thank you for the quick reply. Will there be a docker image with tensorflow support in the near future?

**Comment by beniz** [comment]
Unfortunately this is unlikely in a near future. TF build requires hand configuration, I'd be wary to support the potential issues of TF + nvidia-docker in containers at the moment...
