### ISSUE TITLE
Up to date support of XGBOOST parameters

### ISSUE THREAD

**Issue by ArdalanM** [beniz/deepdetect#249]
Hi,

Would be good to have an up to date support of xgboost parameters:
https://github.com/dmlc/xgboost/blob/master/doc/parameter.md

- New booster: `Dart`
- Deal with unbalance dataset: `scale_pos_weight`
- etc...

**Comment by ArdalanM** [comment]
Tested couple of parameters: `booster=dart`, 'skip_drop`, `rate_drop`, `scale_pos_weight`
working.

**Comment by beniz** [comment]
Merged #252
