### ISSUE TITLE
Adding classes to existing image classifier model

### ISSUE THREAD

**Issue by redserpent7** [beniz/deepdetect#250]
Is it possible to add new classes to an already trained model? Or do I have to re-train from scratch?

**Comment by beniz** [comment]
Short answer: if you have the trained model training set (dataset), retrain from scratch or with oversampled batches (see https://www.reddit.com/r/MachineLearning/comments/5repkx/d_retraining_a_network_using_unrecognized_samples/dd6pgui/). If you don't have the training set, finetune on your application.
Please use gitter for questions, and keep issues for feature requests and bugs, thanks.
