### ISSUE TITLE
Data preparation for Character-level CNN

### ISSUE THREAD

**Issue by guruvasuraj** [beniz/deepdetect#257]
I am planning to try the  sent_en_char model to classify texts. I would like to know the data pre-processing steps. Please share me your thoughts. Any help is greatly appreciated.

**Comment by beniz** [comment]
Hi, there's no external pre-processing per se, it is the `alphabet` used to train a model and listed for every model that acts an internal preprocessor at the convolution level, see https://deepdetect.com/applications/text_model/#list-of-character-based-text-classification-models:54b61be348fc21f37c7f0cc7489f0c78
