### ISSUE TITLE
Default `localhost` does not seem to bind properly in some settings / "ERROR - empty resource"

### ISSUE THREAD

**Issue by beniz** [beniz/deepdetect#26]
Typically, starting `dede` defaults on `localhost:8080` and in some cases querying `localhost` from API returns nothing. Switching to `127.0.0.1` clears the problem.

This issue in case it is a possibility that the binding issue comes from deepdetect embedded web server (based on boost).

**Comment by codeAshu** [comment]
I am facing the same issue.

**Comment by beniz** [comment]
@codeAshu start server with:
```
./dede -host 127.0.0.1
```
Still not sure where it comes from.

**Comment by beniz** [comment]
Some progress... this is due to ipv6 binding on `localhost`. Typically, commenting out:
```
::1 localhost
```
in `/etc/hosts` fixes the issue.

Still looking for better fix.

**Comment by beniz** [comment]
More analysis reveals that this is very likely to be related to https://github.com/cpp-netlib/cpp-netlib/pull/448 and https://github.com/cpp-netlib/cpp-netlib/issues/447 for versions of cpp-netlib prior to 0.11.1. Ubuntu 14.04, which is the supported platform for dd, appears to ship with 0.11.0. In the meantime I'll commit a quick fix internal to dd that clears the issue for `::1` binding to `127.0.0.1` as `localhost`.
