### ISSUE TITLE
Build succeed with a GTX 1080 but DeepDetect is unusable

### ISSUE THREAD

**Issue by YaYaB** [beniz/deepdetect#264]
Currently when building on GPU it is not possible to use a GPU with the latest architecture (compatibility mode >=6.0), as  a GTX 1080.

The issue is related to Caffe and its `Makefile.config.*` files. Indeed the `Makefile.config.*` files from Caffe's fork downloaded during the make of DeepDetect do not contain the lines to integrate the latest architecture.

I found a way to make it work by directly modifying the `Makefile.config.*` files. You can see it here:
https://github.com/YaYaB/caffe/commit/8da3ff3d474417a9e601c7a306558344c13c0d17

However it seems  it seems that it breaks some version of cuda according to this:
https://github.com/beniz/caffe/commit/4ba16b6ccd314df552639c7acddbc6896872af63

Could you find a way to make it work?

**Comment by beniz** [comment]
Fixed by https://github.com/beniz/deepdetect/commit/1d34b93f8e3771fcd739f5c519fedf605e010ad5

See README.md and usage of `cmake .. -DCUDA_ARCH="-gencode  arch=compute_35,code=sm_35" for instance.
