### ISSUE TITLE
Error while proceeding with prediction forward pass, not enough memory?

### ISSUE THREAD

**Issue by yangboz** [beniz/deepdetect#267]
Maybe  in the https://deepdetect.com/overview/installing/ missing RAM requirement documentation,

My server with CPU model: "Linux  4.4.0-62-generic Ubuntu16.04" with 1 CPU and  4G RAM, still thrown error:
"INFO - 21:36:13 - Ignoring source layer pool5/drop_7x7_s1
I0224 21:36:13.279881  9268 caffelib.cc:2659] Net total flops=1581837312 / total params=6155712
E0224 21:36:13.632174  9268 caffelib.cc:2155] Error while proceeding with prediction forward pass, not enough memory?
INFO - 21:36:13 - Ignoring source layer loss3/loss3
ERROR - 21:36:13 - service buildings prediction call failed"

But Bags/FootWear services running well. I wonder how many RAM truly needed? Does GPU model save memory?

Thanks,

**Comment by beniz** [comment]
Very likely indeed. Please use gitter for questions and keep issues for bugs and feature requests.
