### ISSUE TITLE
TEXT n20 training crashed DD. (core dumped)

### ISSUE THREAD

**Issue by sunatthegilddotcom** [beniz/deepdetect#268]
(A Markdown syntax reminder is available here: https://guides.github.com/features/mastering-markdown/)

#### Configuration
- Version of DeepDetect:   Pulled from Docker hub with 
https://hub.docker.com/r/beniz/deepdetect_cpu/
docker pull beniz/deepdetect_cpu
   - [X ] Docker

The issue can be duplicated from pulling from 
https://github.com/beniz/deepdetect
on Azure VM Ubuntu 14.04

#### Your question / the problem you're facing:

INFO - 22:15:08 - This network produces output losst
INFO - 22:15:08 - Network initialization done.
[22:15:08] /opt/deepdetect/src/caffelib.cc:1605: filling up net prior to training

Segmentation fault (core dumped)
INFO - 22:15:08 - Solver scaffolding done.

============

=

#### Error message (if any) / steps to reproduce the problem:
- [ ] list of API calls:

Training from the following command

	 curl -X POST "http://localhost:9090/train" -d '{
       "service":"n20",
       "async":true,
       "parameters":{
         "mllib":{
           "gpu":false,
		   "db":true,
           "solver":{
             "iterations":200,
             "test_interval":20,
             "base_lr":0.05
           },
           "net":{
             "batch_size":30
           }
         },
         "input":{
           "shuffle":true,
           "test_split":0.2,
           "min_count":2,
           "min_word_length":2,
           "count":false
         },
         "output":{
           "measure":["mcll","f1"]
         }
       },
       "data":["/opt/models/n20/news20"]
     }'
	 
=====================

- [ ] Server log output:

Docker log

INFO - 22:15:08 - This network produces output losst
INFO - 22:15:08 - Network initialization done.
[22:15:08] /opt/deepdetect/src/caffelib.cc:1605: filling up net prior to training

Segmentation fault (core dumped)
INFO - 22:15:08 - Solver scaffolding done.

The issue seems to be out of memory issue, should 
           "gpu":false,
		   "db":true,
helps?

Thank you very much for your help!

**Comment by beniz** [comment]
It is very likely you do have enough RAM. Try a higher `min_count` or bump your VM up.

**Comment by sunatthegilddotcom** [comment]
This has tested on a 8 Core and 28GB memory Ubuntu 14.04 server

**Comment by sunatthegilddotcom** [comment]
Thank you very much, Beniz!  I will try a higher min_count

**Comment by sunatthegilddotcom** [comment]
Thank you very much, Beniz!  So far, using min_count to 15, still get the same error with ,\"db\":true,\ option.  

curl -X PUT "http://localhost:8080/services/n20" -d "{\"mllib\":\"caffe\",\"description\":\"newsgroup classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"txt\"},\"mllib\":{\"template\":\"mlp\",\"db\":true,\"nclasses\":20,\"layers\":[200,200],\"activation\":\"relu\"}},\"model\":{\"templates\":\"/opt/deepdetect/templates/caffe/\",\"repository\":\"/opt/models/n20\"}}"

curl -X POST "http://localhost:8080/train" -d "{\"service\":\"n20\",\"async\":true,\"parameters\":{\"mllib\":{\"gpu\":true,\"solver\":{\"iterations\":2000,\"test_interval\":200,\"base_lr\":0.05},\"net\":{\"batch_size\":300}},\"input\":{\"shuffle\":true,\"test_split\":0.2,\"min_count\":15,\"min_word_length\":3,\"count\":false,\"db\":true},\"output\":{\"measure\":[\"mcll\",\"f1\"]}},\"data\":[\"/opt/models/n20/news20\"]}"

==============

INFO - 05:27:39 - Solver scaffolding done.
INFO - 05:27:39 - Ignoring source layer inputl
E /opt/deepdetect/src/caffelib.cc:1917] Error while filling up network for testing
E /opt/deepdetect/src/services.h:425] service n20 training status call failed

E /opt/deepdetect/src/jsonapi.cc:776] {"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"./include/caffe/util/db_lmdb.hpp:15 / Check failed (custom): (mdb_status) == (0)"}

**Comment by sunatthegilddotcom** [comment]
curl -X PUT "http://localhost:8080/services/n20" -d "{\"mllib\":\"caffe\",\"description\":\"newsgroup classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"txt\"},\"mllib\":{\"template\":\"mlp\",\"db\":true,\"nclasses\":20,\"layers\":[200,200],\"activation\":\"relu\"}},\"model\":{\"templates\":\"/opt/deepdetect/templates/caffe/\",\"repository\":\"/opt/models/n20\"}}"
{"status":{"code":201,"msg":"Created"}}

**Comment by sunatthegilddotcom** [comment]
Hi Beniz!   The interesting part is that the same Docker Image and same commands work on a smaller laptop.

**Comment by sunatthegilddotcom** [comment]
curl -X GET "http://localhost:9090/train?service=n20&job=1"
{"status":{"code":200,"msg":"OK"},"head":{"method":"/train","job":1,"status":"finished","time":1603.0},"body":{"measure":{"train_loss":0.012517890892922879,"mcll":0.4733352928190408,"accp":0.9013262599469496,"recall":0.9018233652937052,"iteration":1999.0,"precision":0.8999598500459938,"f1":0.9008906439886895},"model":{"repository":"/opt/models/n20


curl -X POST 'http://localhost:9090/predict' -d '{
     "service":"n20",
     "parameters":{
       "mllib":{
         "gpu":false
       }
     },
     "data":["my computer runs linux"]
     }'
prediction got following error even the training completed correctly

INFO - 06:33:49 - Ignoring source layer drop0
[06:33:49] /opt/deepdetect/src/caffelib.cc:2129: exception while filling up network for prediction
INFO - 06:33:49 - Ignoring source layer drop1
ERROR - 06:33:49 - service n20 prediction call failed

ERROR - 06:33:49 - 172.17.0.1 "POST /predict" 500 0

**Comment by sunatthegilddotcom** [comment]
Hi Beniz!   I stopped the docker container and restart it and then create n20 service again with trained model and then the prediction is good.   You can close this case but this is a work around to get the model working
Thank you very much!

**Comment by beniz** [comment]
This is very likely to be due to your VM, not to DD.
