### ISSUE TITLE
Cannot find -lcaffe

### ISSUE THREAD

**Issue by Elaidon** [beniz/deepdetect#271]
Dear Beniz,

I am trying to make deepdetect with already installed caffe compiled with OpenCV 3.2, CUDA 8.0, cuDNN 5.1 on Ubuntu 16.04.

My .bashrc is:

# Impostazione per CUDA
export CUDA_VISIBLE_DEVICES="0"
export CUDA_HOME=/usr/local/cuda-8.0
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
# OpenCV
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
export PKG_CONFIG_PATH

export PYTHONPATH=/home/elaidon/AI/caffe/python:$PYTHONPATH
export CAFFE_HOME=/home/elaidon/AI/caffe

I already fixed the bug about curlpp making it from source.
I installed all the component you list in the installation guide.

When I launch cmake .. the settings are saved in the right way.
So finally I launch "make" command.
The first part of compilation is right, but as soon as the second part starts I get these errors:

[ 79%] Built target ddetect
Scanning dependencies of target dede
[ 83%] Building CXX object main/CMakeFiles/dede.dir/dede.cc.o
NVCC src/caffe/layers/lstm_unit_layer.cu
NVCC src/caffe/layers/smooth_L1_loss_layer.cu
NVCC src/caffe/layers/lrn_layer.cu
NVCC src/caffe/layers/prelu_layer.cu
NVCC src/caffe/layers/tanh_layer.cu
[ 87%] Linking CXX executable dede
/usr/bin/ld: cannot find -lcaffe
collect2: error: ld returned 1 exit status
main/CMakeFiles/dede.dir/build.make:135: recipe for target 'main/dede' failed
make[2]: *** [main/dede] Error 1
CMakeFiles/Makefile2:177: recipe for target 'main/CMakeFiles/dede.dir/all' failed
make[1]: *** [main/CMakeFiles/dede.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I searched between issues and I googled but I cannot find what could generate the "cannot find -lcaffe".
Any suggestions please?

Thank you
Elaidon

**Comment by beniz** [comment]
You do not appear to be following the building instructions. Why are you exporting  CAFFE_HOME exactly? As a remainder, DD automatically builds from a custom / enhanced version of Caffe, whereas you appear to be willing to build against an external Caffe repository ?

**Comment by Elaidon** [comment]
Hi,

you are right, I am using OpenCV 3.2 and Nvidia Digits, and other custom programs so I need some specific settings and the installation of standard Caffe.
So I would like to know if it is possible to install the standard Caffe release.

Thanks
Elaidon

**Comment by beniz** [comment]
it is not.

**Comment by Elaidon** [comment]
ok, thank you
