### ISSUE TITLE
make error on ubuntu

### ISSUE THREAD

**Issue by jin58611** [beniz/deepdetect#272]
I'm getting the following error when I try to build..
$ make all

...

[100%] Linking CXX executable dede
/usr/bin/ld: warning: libcudart.so.8.0,   needed by /home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.8.0,   needed by /home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcusparse.so.8.0, needed by /home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcurand.so.8.0,   needed by /home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::OptionContainer(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/usr/local/include/curlpp/internal/OptionContainer.inl:38: undefined reference to `curlpp::internal::SList::SList(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::getValue()':
/usr/local/include/curlpp/internal/OptionContainer.inl:59: undefined reference to `curlpp::internal::SList::operator std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >[abi:cxx11]()'
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::setValue(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/usr/local/include/curlpp/internal/OptionContainer.inl:52: undefined reference to `curlpp::internal::SList::operator=(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::Info<(CURLINFO)2097154, long>::get(curlpp::Easy const&)':
/usr/local/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy const&, CURLINFO, long&)'
../src/libddetect.a(caffelib.cc.o): In function `curlpp::Info<(CURLINFO)2097154, long>::get(curlpp::Easy const&)':
/usr/local/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy const&, CURLINFO, long&)'
/usr/local/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy const&, CURLINFO, long&)'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cusparseDestroyMatDescr'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cusparseDestroy'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cusparseSetMatIndexBase'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasDdot_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasDscal_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cusparseCreateMatDescr'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasDestroy_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasDasum_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cusparseCreate'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasSaxpy_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandSetGeneratorOffset'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasDgemm_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasSasum_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasCreate_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cusparseSetMatType'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandGenerateUniform'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandGenerateUniformDouble'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasDaxpy_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandCreateGenerator'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasScopy_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasSgemv_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasSdot_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandSetPseudoRandomGeneratorSeed'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandDestroyGenerator'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasDcopy_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandGenerateNormalDouble'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasSgemm_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasDgemv_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandGenerate'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `cublasSscal_v2'
/home/user/jtkim/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so: undefined reference to `curandGenerateNormal'
collect2: error: ld returned 1 exit status
main/CMakeFiles/dede.dir/build.make:123: recipe for target 'main/dede' failed
make[2]: *** [main/dede] Error 1
CMakeFiles/Makefile2:177: recipe for target 'main/CMakeFiles/dede.dir/all' failed
make[1]: *** [main/CMakeFiles/dede.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by beniz** [comment]
Please follow the issue template, state your OS, and make sure you have exported the correct LD_LIBRARY_PATH.

**Comment by sachindesh** [comment]
if you are using only for CPU (i.e. without GPU), please set CPU_ONLY=ON in CMakeLists.txt
