### ISSUE TITLE
libcurlpp.so.1 not found in latest Docker build

### ISSUE THREAD

**Issue by EricTendian** [beniz/deepdetect#280]
#### Configuration
- Version of DeepDetect:
    - [ ] Locally compiled on:
        - [ ] Ubuntu 14.04 LTS
        - [ ] Mac OSX
        - [ ] Other:
    - [x] Docker
    - [ ] Amazon AMI
- Commit (shown by the server when starting): Whatever is the `latest` tag

#### Your question / the problem you're facing:

I'm a new user of DeepDetect and am trying to set it setup. I'm on an Azure machine running Ubuntu 16.04. I have done the following steps for the CPU version, as well as the GPU version of the Docker image.

1. `docker pull beniz/deepdetect_cpu`
2. `docker run -d -p 8080:8080 beniz/deepdetect_cpu`
3. `docker ps` (no containers running)
4. `docker logs {container_id}`

*For the output of step 4, I get the error:*

    ./dede: error while loading shared libraries: libcurlpp.so.1: cannot open shared object file: No such file or directory

It appears that this may be related to recent commit https://github.com/beniz/deepdetect/commit/39bd4a0706cc61a03ed8361f096d946099eb0b02 which compiles `libcurlpp` instead of using the `libcurlpp-dev` package.

Am I running the container incorrectly, or is this an issue with the newest version? I don't see any version tags so I'm unable to test on an older version from Docker Hub.

Thanks!

**Comment by beniz** [comment]
Hi, thanks for reporting this. Updated containers have been rolled out, and they work fine for us, let me know if the issue does persist. We haven't looked into container versioning yet.

**Comment by EricTendian** [comment]
Much appreciated @beniz, I just pulled the latest version and things are working smoothly. Looks like your fix did the trick.
