### ISSUE TITLE
Object detection demo openCV returns error

### ISSUE THREAD

**Issue by UristIronblood** [beniz/deepdetect#283]
Before creating a new issue, please make sure that:
- [x] the problem isn't already identified in the in the [FAQ page](http://www.deepdetect.com/overview/faq/ "DeepDetect FAQ page"),
- [x] your problem isn't listed in an existing issue ([open](https://github.com/beniz/deepdetect/issues) or [closed](https://github.com/beniz/deepdetect/issues?q=is%3Aissue+is%3Aclosed) one),
- [x] [all prerequisite tools](http://www.deepdetect.com/overview/installing/ "DeepDetect installation page") and [dependencies](https://github.com/beniz/deepdetect#user-content-dependencies "DeepDetect README page on Github") are installed.

If Ok, please give as many details as possible to help us solve the problem more efficiently.
#### Configuration
- Version of DeepDetect:
    - [ ] Locally compiled on:
        - [ ] Ubuntu 14.04 LTS
        - [ ] Mac OSX
        - [x] Other: Kubuntu 16.04 LTS
    - [ ] Docker
    - [ ] Amazon AMI
- Commit (shown by the server when starting):

#### Your question / the problem you're facing:
When running object detection I encountered error described below. DeepDetect runs properly but for some reason python scripts refuse to cooperate.
Tried installing  from different repo's, compiling with various flags etc. to no avail. All dependencies are met, conflicts resolved and links properly set.

#### Error message (if any) / steps to reproduce the problem:
```
jakub@jakub-ThinkPad-E560:~/deepdetect/demo/objdetect$ python objdetect.py --image /home/jakub/deepdetect/demo/objdetect/stock-sell-434x280.jpg --confidence-threshold 0.1
{u'status': {u'msg': u'OK', u'code': 200}, u'body': {u'predictions': [{u'classes': [{u'cat': u'person', u'prob': 0.944989025592804, u'bbox': {u'xmin': 129.89230346679688, u'ymin': 261.107666015625, u'ymax': 0.3795480728149414, u'xmax': 420.6220397949219}}, {u'cat': u'person', u'prob': 0.9271784424781799, u'bbox': {u'xmin': 2.5067012310028076, u'ymin': 280.1105041503906, u'ymax': 29.021333694458008, u'xmax': 192.4145050048828}}, {u'cat': u'dog', u'last': True, u'prob': 0.6394034624099731, u'bbox': {u'xmin': 5.106114864349365, u'ymin': 274.4620666503906, u'ymax': 18.04043197631836, u'xmax': 184.2908935546875}}], u'uri': u'/home/jakub/deepdetect/demo/objdetect/stock-sell-434x280.jpg'}]}, u'head': {u'method': u'/predict', u'service': u'imgserv', u'time': 1233.0}}
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /io/opencv/modules/highgui/src/window.cpp, line 583
Traceback (most recent call last):
  File "objdetect.py", line 47, in <module>
    cv2.imshow('img',img)
cv2.error: /io/opencv/modules/highgui/src/window.cpp:583: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage
```

**Comment by beniz** [comment]
This is not a DD error. DD works fine and the object detection as well, as seen from the JSON output that returns the bounding boxes for the detected objects.

What fails is the Python OpenCV `imshow` that opens a window and screen the image along with bounding boxes. Either you are on a remote shell and the window cannot be created, either you are missing GTK or something like this on your KDE (Kubuntu) setup.

Unrelated to DD, check your setup, e.g. http://stackoverflow.com/questions/28776053/opencv-gtk2-x-error
