### ISSUE TITLE
OpenImages TF model update to use a sigmoid instead of softmax layer

### ISSUE THREAD

**Issue by cchadowitz-pf** [beniz/deepdetect#286]
Based on a long series of discussion with @beniz, I managed to produce a `.pb` model file based on the original OpenImages Inception v3 model that works with DeepDetect and outputs confidences from a sigmoid layer (as the original model used) rather than a softmax.
A lot of info was inspired by this comment: https://github.com/openimages/dataset/issues/21#issuecomment-276107322

and other helpful information from: https://github.com/openimages/dataset/issues/3#issuecomment-259552328

A very rough how-to is available here: https://gist.github.com/cchadowitz-pf/f1c3e781c125813f9976f6e69c06fec2

**Comment by beniz** [comment]
Thank you, I've checked the model and it appears to work very nicely. Model link has been updated.
