### ISSUE TITLE
Run on OSX 10.12.4

### ISSUE THREAD

**Issue by hanbim520** [beniz/deepdetect#294]
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   iostreams
--   chrono
--   date_time
--   atomic
--   regex
-- CUDA detected: 8.0
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50 sm_61
CMake Error at cmake/Cuda.cmake:264 (deepdetect_detect_darwin_version):
  Unknown CMake command "deepdetect_detect_darwin_version".
Call Stack (most recent call first):
  CMakeLists.txt:69 (include)

-- Configuring incomplete, errors occurred!

**Comment by beniz** [comment]
Hi, there's no support for OSX, see #70 for some tips. I have no information on whether anyone has built DD on OSX. It's certainly possible though...
