### ISSUE TITLE
i just run quickstart in ubuntu 16.10.

### ISSUE THREAD

**Issue by hushunda** [beniz/deepdetect#301]
i finish `docker pull deepdetect_cpu
docker run -d -p 8080:8080 beniz/deepdetect_cpu`.

run `curl http://localhost:8080/info`,
show **{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"11adce0366d367fd16c5ac5233c8a6118a24f8ad","services":[{"mllib":"caffe","description":"image classification service","name":"imageserv"}]}}**

but wheni run `curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":{\"connector\":\"image\"},\"mllib\":{\"nclasses\":1000}},\"model\":{\"repository\":\"/opt/models/ggnet/\"}}"`,
i meet the problem **{"status":{"code":403,"msg":"Forbidden"}**

**Comment by beniz** [comment]
First, the call you are posting is missing a piece, maybe this is due to your copy/paste. The correct call is 
```
curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"nclasses\":1000}},\"model\":{\"repository\":\"/opt/models/ggnet/\"}}"
```
which yields:
```
{"status":{"code":201,"msg":"Created"}}
````
`Forbidden` in general means you already have created the service, and it is already active. You can check with an `info` call.

**Comment by hushunda** [comment]
thank you for you answer,i had sovle the problem.
