### ISSUE TITLE
Cannot turn json output using custom format

### ISSUE THREAD

**Issue by wsutong** [beniz/deepdetect#304]
While using a custom template to run the demo of Image Classification, It can't return the result as I supposed. Here is my code:

`
```
from dd_client import DD
model_repo = '/home/sut/code/clothing/models'
height = width = 224
nclasses = 304
host = '127.0.0.1'
sname = 'clothing'
description = 'clothes classification'
mllib = 'caffe'

host = '127.0.0.1'
sname = 'clothing'
description = 'clothes classification'
mllib = 'caffe'
dd = DD(host)
dd.set_return_format(dd.RETURN_PYTHON)
model = {'repository':model_repo}
parameters_input = {'connector':'image','width':width,'height':height}
parameters_mllib = {'nclasses':nclasses}
parameters_output = {'best':3,"templete":"{{#body}}{{#predictions}}:\n{{#classes}}{{cat}}->{{prob}}\n{{/classes}}{{/predictions}}{{/body}}"}

data = ["/home/sut/code/clothing/testimg/002.jpg"]
classif = dd.post_predict(sname,data,parameters_input,parameters_mllib,parameters_output)
print classif
```
`
and the result is 

`
{u'status': {u'msg': u'OK', u'code': 200}, u'body': {u'predictions': [{u'classes': [{u'prob': 0.48492196202278137, u'cat': u'blouse'}, {u'prob': 0.33585208654403687, u'cat': u'chemise, sack, shift'}, {u'last': True, u'prob': 0.0651431679725647, u'cat': u'attire, garb, dress'}], u'uri': u'/home/sut/code/clothing/testimg/002.jpg'}]}, u'head': {u'method': u'/predict', u'service': u'clothing', u'time': 1734.0}}
`

But I just defined the template output to print just the body part. And there are in one line ignoring the "\n" command. So how can I do ?
Is there anything wrong with my installation?

**Comment by beniz** [comment]
Use `template`, there's a typo in your call.
