### ISSUE TITLE
info.labels.size error on xgboost

### ISSUE THREAD

**Issue by marcstein** [beniz/deepdetect#305]
I realize that this is more a xgboost issue, but perhaps someone has already solved it within the context of DeepDetect.

The error is this:
Check failed: info.labels.size() != 0U (0 vs. 0) label set cannot be empty

It occurs in response to a training attempt.

The sequence of events that I'm running are:

1)

curl -X PUT "http://192.168.1.190:8080/services/fair" -d '{
       "mllib":"xgboost",
       "description":"FS",
       "type":"supervised",
       "parameters":{
         "input":{
           "connector":"csv"
         },
         "mllib":{
           "nclasses":2
         }
       },
       "model":{
         "repository":"models/fair"
       }
     }'

2)

curl -X POST "http://192.168.1.190:8080/train" -d '{
       "service":"fair",
       "async":true,
       "parameters":{
         "mllib":{
           "iterations":100,
           "test_interval":10,
           "objective":"binary:logistic"
         },
         "input":{
           "label_offset":-1,
           "label":"outcome",
           "id":"Id",
           "separator":",",
           "shuffle":true,
           "test_split":0.1
         },
         "output":{
           "measure":["acc","mcll","f1"]
         }
       },
       "data":["models/fair/2ktrain.csv"]
     }'

3)

 curl -X POST "http://192.168.1.190:8080/predict" -d '{
       "service":"fair",
       "parameters":{
         "input":{
           "id":"Id",
           "separator":","
         }
       },
       "data":["models/fair/test1.csv"]
     }'

The error occurs after step 2

The training file has a large number of attributes, 3620 to be specific. The label is 'outcome' which is a binary outcome defined as 0 or 1.

The test file retains the Id attribute but deletes the outcome attribute. 

I want the probability of the binary outcome as a result.

I've tried all the various options for the objective parameter, but always get the same error.

Any ideas as to what I'm doing wrong?

Attached are the training and test files used.

Thanks in advance for any assistance!

Best,

Marc

[2kTRAIN.csv.zip](https://github.com/beniz/deepdetect/files/987961/2kTRAIN.csv.zip)

[test1.csv.zip](https://github.com/beniz/deepdetect/files/987962/test1.csv.zip)

**Comment by beniz** [comment]
I can't look at the files right now, but you should not need the `label_offset` if your outcome variable is already 0 or 1 in your `2ktrain.csv` file. Look at the API if unsure.

**Comment by marcstein** [comment]
Hi Emmanuel,

Thanks so much for the quick response!

I took out that parameter and that did change the error message to

/home/marc/deepdetect/main/xgboost/src/xgboost/src/objective/regression_obj.cc:89:
Check failed: info.labels.size() != 0U (0 vs. 0) label set cannot be empty

Not sure what this refers to since I've tried it both without listing the
output label in the test file and with the label. I get the same response
in both cases.

I guess that the new error message is a bit of an improvement.

Many thanks and Best Regards,

Marc

**Comment by beniz** [comment]
I'm not sure I see how the error message is now different that the initial one ?

**Comment by marcstein** [comment]
Sorry, it's the same message, it just comes at a different line in the code.

Any other ideas as to how to approach this? My next step will be to see if
it's related the the number of attributes in the data, by dumbing down the
problem and seeing if I can get a simplified model to run.

The goal is to use GPU accelerated Gradient Boosting on our data sets via
an API. Your solution seems like it would be perfect, if I can get it to
work.

Best,

Marc

On Wed, May 10, 2017 at 5:53 AM, Emmanuel Benazera <notifications@github.com

**Comment by beniz** [comment]
Removing the `label_offset` as initially suggested works fine for me.

**Comment by marcstein** [comment]
Thanks!

Are you running something like this:

curl -X POST "http://192.168.1.190:8080/train" -d '{
       "service":"fair",
       "async":true,
       "parameters":{
         "mllib":{
           "iterations":100,
           "test_interval":10,
           "objective":"binary:logistic"
         },
         "input":{
           "label":"outcome",
           "id":"Id",
           "separator":",",
           "shuffle":true,
           "test_split":0.1
         },
         "output":{
           "measure":["acc","mcll","f1"]
         }
       },
       "data":["models/fair/2ktrain.csv"]
     }'

I'm still getting the error.

**Comment by beniz** [comment]
```
curl -X PUT "http://localhost:8080/services/fair" -d '{
"mllib":"xgboost",
"description":"FS",
"type":"supervised",
"parameters":{
"input":{
"connector":"csv"
},                            
"mllib":{                                    
"nclasses":2
}                 
},        
"model":{
"repository":"/path/to/fair/"
}               
}'
```

```
curl -X POST "http://localhost:8080/train" -d '{
"service":"fair",
"async":false,
"parameters":{
"mllib":{
"iterations":100,
"test_interval":10,
"objective":"binary:logistic",
"booster_params":{"scale_pos_weight":100.0}},
"input":{
"label":"outcome",
"id":"Id",
"separator":",",
"shuffle":true,
"test_split":0.1
},
"output":{
"measure":["acc","mcll","f1"]
}
},
"data":["/path/to/2kTRAIN.csv"]
}'
```
