### ISSUE TITLE
When i am trying to test the age library i get error: "Check failed (custom): (height) <= (datum_height)"}

### ISSUE THREAD

**Issue by roysG** [beniz/deepdetect#306]
curl -X PUT "http://run.selfiecash.me:8080/services/ages1" -d '{
       "mllib":"caffe",
       "description":"ages classification",
       "type":"supervised",
       "parameters":{
         "input":{
           "connector":"image",
           "height":224,                                                                                                     "width":224
         },
         "mllib":{
           "nclasses":8
         }
       },
       "model":{
         "repository":"/home/xxx/models/ages/age_model"
       }
     }'

-----------------------------------------------

curl -X POST "http://run.selfiecash.me:8080/predict" -d '{
       "service":"ages1",
       "parameters":{
         "output":{
           "best":5
         }
       },
       "data":["https://instagram.fhfa2-1.fna.fbcdn.net/t51.2885-15/e35/18380284_1288601544589941_8975502825593241600_n.jpg"]
     }'

result:
{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"src/caffe/data_transformer.cpp:196 / Check failed (custom): (height) <= (datum_height)"}}

What is wrong?

**Comment by beniz** [comment]
Look at the `model.json` file that comes with the model, the input image size is likely to be 227x227.

**Comment by roysG** [comment]
Yes i found it, 
but now it seems that the result are not good for the woman age in the image.

{"status":{"code":200,"msg":"OK"},"head":{"method":"/predict","service":"clothing13","time":575.0},"body":{"predictions":[{"uri":"http://4.bp.blogspot.com/-uwu7SmTbBXI/VD_NNJc4Y-I/AAAAAAAAK1I/rt9de3mWXJo/s1600/faux-fur-coat-winter-2014-big-trend-10.jpg","classes":[{"prob":0.9803997278213501,"cat":"60+"},{"prob":0.018859026953577997,"cat":"48_53"},{"prob":0.0003014336107298732,"cat":"0_2"},{"prob":0.0002030321629717946,"cat":"38_43"},{"prob":0.00010166339052375406,"last":true,"cat":"8_13"}]}]}}

Why?

**Comment by roysG** [comment]
Maybe, the define of the image size in mode.json is too tiny?

**Comment by beniz** [comment]
See the related page, these models are for testing. Though they are quite good, they have their own error rate. Try passing face crops to the age model. Good luck with your application.

**Comment by roysG** [comment]
Thank you, i tried to looked foe the crops to the age model, can you tell me please how can i do it?

**Comment by beniz** [comment]
You'd need a face detector (deep model or other). We have one but it's customers only.

**Comment by dgtlmoon** [comment]
Check your prediction call `height` and `width` also match the training calls
