### ISSUE TITLE
What does this warning says?

### ISSUE THREAD

**Issue by roysG** [beniz/deepdetect#310]
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 538700290

How can i stop it?

**Comment by beniz** [comment]
Please stop opening issues for non bugs / non feature request, as already explained and google around instead + use gitter, thanks.
