### ISSUE TITLE
Minor typo in README

### ISSUE THREAD

**Issue by arnaudmiribel** [beniz/deepdetect#311]
Just a small typo to announce on `objdetect`'s [README](https://github.com/beniz/deepdetect/blob/master/demo/objdetect/README.md)

That line 

```
tar xvzf voc01712_dd.tar.gz
```

Should be replaced with

```
tar xvzf voc0712_dd.tar.gz
```

**Comment by beniz** [comment]
Would you like to PR the change ? Thanks.

**Comment by beniz** [comment]
Fixed.
