### ISSUE TITLE
Build is failed, i get error

### ISSUE THREAD

**Issue by roysG** [beniz/deepdetect#317]
CXX src/caffe/layers/recurrent_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/input_layer.cpp
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp: In member function ‘Dtype caffe::SigmoidCrossEntropyLossLayer<Dtype>::get_normalizer(caffe::LossParameter_NormalizationMode, int) [with Dtype = float]’:
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:75:41: warning: ‘normalizer’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return std::max(Dtype(1.0), normalizer);
                                         ^
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp: In member function ‘Dtype caffe::SigmoidCrossEntropyLossLayer<Dtype>::get_normalizer(caffe::LossParameter_NormalizationMode, int) [with Dtype = double]’:
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:75:41: warning: ‘normalizer’ may be used uninitialized in this function [-Wmaybe-uninitialized]
CXX src/caffe/layers/prior_box_layer.cpp
CXX src/caffe/layers/silence_layer.cpp
/tmp/ccnlOamf.s: Assembler messages:
/tmp/ccnlOamf.s:28477: Error: unknown pseudo-op: `.lbb374'
/tmp/ccnlOamf.s:157781: Error: can't resolve `.text._ZNK5caffe4BlobIfE6offsetEiiii' {.text._ZNK5caffe4BlobIfE6offsetEiiii section} - `.LBB37435' {*UND* section}
Makefile:576: recipe for target '.build_release/src/caffe/layers/prior_box_layer.o' failed
make[3]: *** [.build_release/src/caffe/layers/prior_box_layer.o] Error 1
make[3]: *** Waiting for unfinished jobs....
CMakeFiles/caffe_dd.dir/build.make:108: recipe for target 'caffe_dd/src/caffe_dd-stamp/caffe_dd-configure' failed
make[2]: *** [caffe_dd/src/caffe_dd-stamp/caffe_dd-configure] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caffe_dd.dir/all' failed
make[1]: *** [CMakeFiles/caffe_dd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by beniz** [comment]
Damn boy, for the xth time now, please fill out the template!

**Comment by roysG** [comment]
Operation : ubuntu 16.04

I followed your instructions, the error happened when i made the command "make".

If there are more info i can give you, tell me, thanks.

**Comment by roysG** [comment]
Any update?
