### ISSUE TITLE
Mobile Backend as Service

### ISSUE THREAD

**Issue by pribadihcr** [beniz/deepdetect#32]
Hi @beniz 

Is it possible to implement deepdetect in mobile backend as service?

**Comment by beniz** [comment]
@pribadihcr can you be more precise ? Client on the mobile or server on the mobile ?

**Comment by pribadihcr** [comment]
I means client on the mobile. Example of MBaaS like kinvey.com or parse
facebook.

**Comment by beniz** [comment]
So the answer is yes. The server better stays on the backend side, and the API can be relayed up to the mobile client library. For connection to storage backend, see the tutorial on doing it with ElasticSearch (http://www.deepdetect.com/tutorials/es-image-classifier/), it is applicable to many other storage commodity without effort (e.g. MongoDB, ...).

For connecting to a particular SDK (e.g. Parse Open Source SDK), work is likely to go through as sponsored features. Contact me directly for discussing things like this.
