### ISSUE TITLE
I have enough memory but i still get memory issue 

### ISSUE THREAD

**Issue by roysG** [beniz/deepdetect#322]
#### Configuration
- Version of DeepDetect:
    - [ ] Locally compiled on:
        - [x ] Ubuntu 16.04 LTS
- Commit (shown by the server when starting):
DeepDetect [ commit 1f2d49041656fd0aabcd2d2db44bfc001bf6dbd5 ]

#### Your question / the problem you're facing:
I get error looks like a memory issue, but this is not sense, cause i have 10GB of free ram:
free -m
              total        used        free      shared  buff/cache   available
Mem:          15977        5965        9033          47         978        9644
Swap:             0           0           0

The error happen when i iterate more than one images, i tried to reduce the batches number to 10 and still got the error/ 

#### Error message (if any) / steps to reproduce the problem:

INFO - 04:26:17 - Device id:                     0
INFO - 04:26:17 - Major revision number:         6
INFO - 04:26:17 - Minor revision number:         1
INFO - 04:26:17 - Name:                          GeForce GTX 1070
INFO - 04:26:17 - Total global memory:           8504868864
INFO - 04:26:17 - Total shared memory per block: 49152
INFO - 04:26:17 - Total registers per block:     65536
INFO - 04:26:17 - Warp size:                     32
INFO - 04:26:17 - Maximum memory pitch:          2147483647
INFO - 04:26:17 - Maximum threads per block:     1024
INFO - 04:26:17 - Maximum dimension of block:    1024, 1024, 64
INFO - 04:26:17 - Maximum dimension of grid:     2147483647, 65535, 65535
INFO - 04:26:17 - Clock rate:                    1683000
INFO - 04:26:17 - Total constant memory:         65536
INFO - 04:26:17 - Texture alignment:             512
INFO - 04:26:17 - Concurrent copy and execution: Yes
INFO - 04:26:17 - Number of multiprocessors:     15
E0601 04:26:17.072597   930 caffelib.cc:1204] Error while proceeding with supervised prediction forward pass, not enough memory? src/caffe/layers/pooling_layer.cu:212 / Check failed (custom): (error) == (cudaSuccess)
INFO - 04:26:17 - Kernel execution timeout:      Yes
ERROR - 04:26:17 - service getage prediction call failed

**Comment by beniz** [comment]
You dont have enough gpu memory. please use gitter instead of opening issues for personal questions.

**Comment by roysG** [comment]
ok
