### ISSUE TITLE
CPU Docker XGBoost Error

### ISSUE THREAD

**Issue by fredvollmer** [beniz/deepdetect#324]
In trying to build the CPU Docker image, I encounter the following error in step `19/25: RUN cmake .. -DUSE_XGBOOST=ON`

```[ 12%] Performing configure step for 'xgboost'
checking file CMakeLists.txt
Unreversed patch detected!  Ignore -R? [n]
Apply anyway? [n]
Skipping patch.
2 out of 2 hunks ignored
patching file CMakeLists.txt
Hunk #1 succeeded at 73 (offset 7 lines).
Hunk #2 FAILED at 112.
1 out of 2 hunks FAILED -- saving rejects to file CMakeLists.txt.rej
make[2]: *** [xgboost/src/xgboost-stamp/xgboost-configure] Error 1
make[1]: *** [CMakeFiles/xgboost.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/xgboost.dir/build.make:105: recipe for target 'xgboost/src/xgboost-stamp/xgboost-configure' failed
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xgboost.dir/all' failed
Makefile:83: recipe for target 'all' failed
The command '/bin/sh -c make' returned a non-zero code: 2
```

Let me know if you need any more details, hopefully I'm not missing something obvious here. Thanks for such a great library.

**Comment by beniz** [comment]
Thanks for catching this one. This appears to be from XGBoost itself, and the fix above for DD should do the trick.

As a side-note and FTR, GPU support for XGBoost appears to be broken similarly to https://github.com/dmlc/xgboost/pull/2390

**Comment by fredvollmer** [comment]
Thanks, worked like a charm!

**Comment by beniz** [comment]
Xgboost has fixed its GPU build by merging https://github.com/dmlc/xgboost/pull/2390 and DD build is now fixed as well. Closing.
