### ISSUE TITLE
`weights` parameter seems not to be used

### ISSUE THREAD

**Issue by YaYaB** [beniz/deepdetect#330]
I have an issue trying to do predictions with a GPU that has the id 1.

#### Configuration
- Version of DeepDetect:
    - Locally compiled on Ubuntu 16.04 LTS
- Commit (shown by the server when starting):
    - Branch `Master`, 971eadb202cd7f892dad6a42b2993d6a6ce54128
- GPUS:
    - 2 x Nvidia GTX Titan X (Maxwell)

#### Your question / the problem you're facing:
I am trying to make prediction using a trained model. To do so I have a repository containing regular files from a training done in DeepDetect.
```
-model_iter_60000.caffemodel
-model_iter_60000.solverstate
-model_iter_120000.caffemodel
-model_iter_120000.solverstate
-model_iter_180000.caffemodel
-model_iter_180000.solverstate
-model_iter_240000.caffemodel
-model_iter_240000.solverstate
-train.log
-train.lmdb
-test.lmdb 
-mlp_solver.prototxt
-mlp.prototxt
-deploy.prototxt
-class_weights.binaryproto
-vocab.dat
-model_iter_300000.caffemodel
-model_iter_300000.solverstate
-model.json
```

Here I have a 300k trained model and a 240k model. I want to do prediction from both to compare the results.
I saw that it was possible to use the parameters `finetuning` and `weights` in the service creation to load weights.

First I try without putting those arguments. Here is what I obtained:
INPUT
```
curl -X PUT "http://localhost:8082/services/test" -d "{\"mllib\":\"caffe\",\"description\":\"classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"svm\"},\"mllib\":{\"nclasses\":2,}},\"model\":{\"repository\":\"/home/test/models/exp1\"}}"
```

OUTPUT
```
I0703 13:27:00.972220  3506 caffelib.cc:397] Using pre-trained weights from /home/test/models/exp1/model_iter_300000.caffemodel
```

DD loads the last modified file, it's the best thing to do.

But now if I try putting the following arguments: `"finetuning":true, weights: "/home/test/models/exp1/model_iter_240000.caffemodel"`; here is what I obtained:
INPUT
```
curl -X PUT "http://localhost:8082/services/test" -d "{\"mllib\":\"caffe\",\"description\":\"classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"svm\"},\"mllib\":{\"nclasses\":2, \"finetuning\":true, \"weights\": \"/home/test/models/exp1/model_iter_240000.caffemodel\"}},\"model\":{\"repository\":\"/home/test/models/exp1\"}}"
```

OUTPUT
```
I0703 13:35:00.121591  3506 caffelib.cc:397] Using pre-trained weights from /home/test/models/exp1/model_iter_300000.caffemodel
```

I obtained the same results as before. It's mainly because the parameter `weights` does not seem to be used.
The function that reads model repository is available in here [https://github.com/beniz/deepdetect/blob/34c20176fdfad284226c41aaca216eee25b10a80/src/caffemodel.cc] (line 55) and is called `read_from_repository` always uses the last modified file.
```
	else if ((*hit).find(weights)!=std::string::npos)
	  {
	    // stat file to pick the latest one
	    long int wt = fileops::file_last_modif((*hit));
	    if (wt > weight_t)
	      {
		weightsf = (*hit);
		weight_t = wt;
	      }
}
```

One quick fix would be to add a parameter in the parameter `repository` of the creation service call to DD that we could call `weights`. That would be something like that.
INPUT
```
curl -X PUT "http://localhost:8082/services/test" -d "{\"mllib\":\"caffe\",\"description\":\"classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"svm\"},\"mllib\":{\"nclasses\":2}},\"model\":{\"repository\":\"/home/test/models/exp1\", \"weights\": \"/home/test/models/exp1/model_iter_240000.caffemodel\"}}"
```

After a bit of code modification I was able to obtain the following:
```
I0703 15:22:12.981254  3506 caffelib.cc:397] Using pre-trained weights from /home/test/models/exp1/model_iter_240000.caffemodel
```

Even for finetuning the parameters `weights` is not used. Finetuning is allowed when a template is indicated and it only takes the template of an existing models and modify the prototxt files to do modification on the structure of the network.
See function `instantiate_template` in [`https://github.com/beniz/deepdetect/blob/1f2d49041656fd0aabcd2d2db44bfc001bf6dbd5/src/caffelib.cc`)]

Then a quick modification to the code can make it possible to load a specified `caffemodel`. I will make a pull request ASAP. But I finally obtained t

**Comment by beniz** [comment]
Thanks! The commit above should fix this issue. If it does, you can close this ticket and the PR #331.

**Comment by YaYaB** [comment]
Ok perfect that works!
