### ISSUE TITLE
make error on ubuntu  failed

### ISSUE THREAD

**Issue by xxqcheers** [beniz/deepdetect#335]
I'm getting the following error when I try to build..

1) My OS is : Linux version 4.4.0-57-generic (buildd@lgw01-54) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016
2) my OS no CUDA, beacuse there is no Directory lib64 ,so  I use mkdir command
||
/usr/local/cuda/lib64

then input the command: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

3) then following the Installing DeepDetect document
$ git clone https://github.com/beniz/deepdetect.git
$ cd deepdetect
$ mkdir build
$ cd build
$ cmake ..
$ make

...

xuxiaoqiang@yh142:/data3/tensor/deepdetect-demo/deepdetect/build$ cd ..
xuxiaoqiang@yh142:/data3/tensor/deepdetect-demo/deepdetect$ rm -rf build/
xuxiaoqiang@yh142:/data3/tensor/deepdetect-demo/deepdetect$ mkdir build
xuxiaoqiang@yh142:/data3/tensor/deepdetect-demo/deepdetect$ cd build/
xuxiaoqiang@yh142:/data3/tensor/deepdetect-demo/deepdetect/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'eigen3'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   iostreams
--   chrono
--   date_time
--   atomic
--   regex
-- OpenCV 2 (2.4.9.1) found (/usr/share/OpenCV)
-- Configuring customized caffe
-- Build Tests          : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /data3/tensor/deepdetect-demo/deepdetect/build
xuxiaoqiang@yh142:/data3/tensor/deepdetect-demo/deepdetect/build$ make
Scanning dependencies of target caffe_dd
[  3%] Creating directories for 'caffe_dd'
[  7%] Performing download step (download, verify and extract) for 'caffe_dd'
-- downloading...
     src='https://github.com/beniz/caffe/archive/master.tar.gz'
     dst='/data3/tensor/deepdetect-demo/deepdetect/build/caffe_dd/src/master.tar.gz'
     timeout='none'
-- downloading... done
-- verifying file...
     file='/data3/tensor/deepdetect-demo/deepdetect/build/caffe_dd/src/master.tar.gz'
-- verifying file... warning: did not verify file - no URL_HASH specified?
-- extracting...
     src='/data3/tensor/deepdetect-demo/deepdetect/build/caffe_dd/src/master.tar.gz'
     dst='/data3/tensor/deepdetect-demo/deepdetect/build/caffe_dd/src/caffe_dd'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 10%] No patch step for 'caffe_dd'
[ 14%] No update step for 'caffe_dd'
[ 17%] Performing configure step for 'caffe_dd'
PROTOC src/caffe/proto/caffe.proto
CXX src/caffe/net.cpp
CXX src/caffe/solver.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/solvers/rmsprop_solver.cpp
CXX src/caffe/solvers/adam_solver.cpp
CXX src/caffe/solvers/nesterov_solver.cpp
CXX src/caffe/solvers/adadelta_solver.cpp
CXX src/caffe/solvers/sgd_solver.cpp
CXX src/caffe/solvers/adagrad_solver.cpp
CXX src/caffe/parallel.cpp
CXX src/caffe/util/hdf5.cpp
CXX src/caffe/util/db.cpp
CXX src/caffe/util/io.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/bbox_util.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/im_transforms.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/cudnn.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/db_lmdb.cpp
CXX src/caffe/util/benchmark.cpp
CXX src/caffe/util/im2col.cpp
CXX src/caffe/util/db_leveldb.cpp
CXX src/caffe/util/sampler.cpp
CXX src/caffe/common.cpp
CXX src/caffe/data_reader.cpp
CXX src/caffe/sparse_blob.cpp
CXX src/caffe/blob.cpp
CXX src/caffe/layers/accuracy_layer.cpp
CXX src/caffe/layers/sparse_inner_product_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/annotated_data_layer.cpp
CXX src/caffe/layers/tile_layer.cpp
src/caffe/util/upgrade_proto.cpp: In function ‘bool caffe::UpgradeV1LayerParameter(const caffe::V1LayerParameter&, caffe::LayerParameter*)’:
src/caffe/util/upgrade_proto.cpp:721:26: warning: ‘mode’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   ParamSpec_DimCheckMode mode;
                          ^
CXX src/caffe/layers/hdf5_output_layer.cpp
CXX src/caffe/layers/inner_product_layer.cpp
CXX src/caffe/layers/cudnn_conv_layer.cpp
CXX src/caffe/layers/cudnn_lcn_layer.cpp
CXX src/caffe/layers/scale_layer.cpp
CXX src/caffe/layers/permute_layer.cpp
CXX src/caffe/layers/threshold_layer.cpp
CXX src/caffe/layers/silence_layer.cpp
CXX src/caffe/layers/memory_data_layer.cpp
CXX src/caffe/layers/cross_entropy_loss.cpp
src/caffe/solvers/sgd_solver.cpp: In member function ‘Dtype caffe::SGDSolver<Dtype>::GetLearningRate() [with Dtype = float]’:
src/caffe/solvers/sgd_solver.cpp:92:10: warning: ‘rate’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return rate;
          ^
src/caffe/solvers/sgd_solver.cpp: In member function ‘Dtype caffe::SGDSolver<Dtype>::GetLearningRate() [with Dtype = double]’:
src/caffe/solvers/sgd_solver.cpp:92:10: warning: ‘rate’ may be used uninitialized in this function [-Wmaybe-uninitialized]
CXX src/caffe/layers/loss_layer.cpp
CXX src/caffe/layers/spp_layer.cpp
CXX src/caffe/layers/rnn_layer.cpp
CXX src/caffe/layers/roi_pooling_layer.cpp
CXX src/caffe/layers/memory_sparse_data_layer.cpp
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/cudnn_lrn_layer.cpp
CXX src/caffe/layers/smooth_l1_loss_layer.cpp
CXX src/caffe/layers/cudnn_softmax_layer.cpp
CXX src/caffe/layers/window_data_layer.cpp
CXX src/caffe/layers/data_layer.cpp
CXX src/caffe/layers/deconv_layer.cpp
CXX src/caffe/layers/hdf5_data_layer.cpp
CXX src/caffe/layers/multinomial_logistic_loss_layer.cpp
CXX src/caffe/layers/mvn_layer.cpp
CXX src/caffe/layers/crop_layer.cpp
src/caffe/layers/loss_layer.cpp: In member function ‘Dtype caffe::LossLayer<Dtype>::GetNormalizer(caffe::LossParameter_NormalizationMode, int, int, int) [with Dtype = float]’:
src/caffe/layers/loss_layer.cpp:54:41: warning: ‘normalizer’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return std::max(Dtype(1.0), normalizer);
                                         ^
src/caffe/layers/loss_layer.cpp: In member function ‘Dtype caffe::LossLayer<Dtype>::GetNormalizer(caffe::LossParameter_NormalizationMode, int, int, int) [with Dtype = double]’:
src/caffe/layers/loss_layer.cpp:54:41: warning: ‘normalizer’ may be used uninitialized in this function [-Wmaybe-uninitialized]
CXX src/caffe/layers/image_data_layer.cpp
CXX src/caffe/layers/prelu_layer.cpp
CXX src/caffe/layers/infogain_loss_layer.cpp
CXX src/caffe/layers/sparse_data_layer.cpp
CXX src/caffe/layers/euclidean_loss_layer.cpp
CXX src/caffe/layers/reshape_layer.cpp
CXX src/caffe/layers/slice_layer.cpp
CXX src/caffe/layers/eltwise_layer.cpp
src/caffe/blob.cpp: In member function ‘Dtype caffe::Blob<Dtype>::sumsq_data() const [with Dtype = float]’:
src/caffe/blob.cpp:290:9: warning: ‘sumsq’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   Dtype sumsq;
         ^
src/caffe/blob.cpp: In member function ‘Dtype caffe::Blob<Dtype>::sumsq_diff() const [with Dtype = float]’:
src/caffe/blob.cpp:333:9: warning: ‘sumsq’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   Dtype sumsq;
         ^
src/caffe/blob.cpp: In member function ‘Dtype caffe::Blob<Dtype>::sumsq_data() const [with Dtype = double]’:
src/caffe/blob.cpp:290:9: warning: ‘sumsq’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   Dtype sumsq;
         ^
src/caffe/blob.cpp: In member function ‘Dtype caffe::Blob<Dtype>::sumsq_diff() const [with Dtype = double]’:
src/caffe/blob.cpp:333:9: warning: ‘sumsq’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   Dtype sumsq;
         ^
CXX src/caffe/layers/detection_output_layer.cpp
CXX src/caffe/layers/multibox_loss_layer.cpp
CXX src/caffe/layers/filter_layer.cpp
CXX src/caffe/layers/cudnn_relu_layer.cpp
CXX src/caffe/layers/softmax_infogain_loss_layer.cpp
CXX src/caffe/layers/recurrent_layer.cpp
CXX src/caffe/layers/bias_layer.cpp
CXX src/caffe/layers/neuron_layer.cpp
CXX src/caffe/layers/elu_layer.cpp
CXX src/caffe/layers/lrn_layer.cpp
CXX src/caffe/layers/lstm_unit_layer.cpp
CXX src/caffe/layers/contrastive_loss_layer.cpp
CXX src/caffe/layers/base_conv_layer.cpp
CXX src/caffe/layers/relu_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/im2col_layer.cpp
CXX src/caffe/layers/softmax_layer.cpp
CXX src/caffe/layers/power_layer.cpp
CXX src/caffe/layers/video_data_layer.cpp
CXX src/caffe/layers/parameter_layer.cpp
CXX src/caffe/layers/softmax_loss_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
CXX src/caffe/layers/lstm_layer.cpp
CXX src/caffe/layers/prior_box_layer.cpp
CXX src/caffe/layers/sigmoid_layer.cpp
CXX src/caffe/layers/bnll_layer.cpp
CXX src/caffe/layers/flatten_layer.cpp
CXX src/caffe/layers/reduction_layer.cpp
CXX src/caffe/layers/batch_reindex_layer.cpp
CXX src/caffe/layers/dropout_layer.cpp
CXX src/caffe/layers/conv_layer.cpp
CXX src/caffe/layers/hinge_loss_layer.cpp
CXX src/caffe/layers/exp_layer.cpp
src/caffe/layers/softmax_infogain_loss_layer.cpp: In member function ‘Dtype caffe::SoftmaxWithInfogainLossLayer<Dtype>::get_normalizer(caffe::LossParameter_NormalizationMode, int) [with Dtype = float]’:
src/caffe/layers/softmax_infogain_loss_layer.cpp:111:43: warning: ‘normalizer’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     return std::max(Dtype(1.0), normalizer);
                                           ^
src/caffe/layers/softmax_infogain_loss_layer.cpp: In member function ‘Dtype caffe::SoftmaxWithInfogainLossLayer<Dtype>::get_normalizer(caffe::LossParameter_NormalizationMode, int) [with Dtype = double]’:
src/caffe/layers/softmax_infogain_loss_layer.cpp:111:43: warning: ‘normalizer’ may be used uninitialized in this function [-Wmaybe-uninitialized]
CXX src/caffe/layers/absval_layer.cpp
CXX src/caffe/layers/batch_norm_layer.cpp
CXX src/caffe/layers/argmax_layer.cpp
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp: In member function ‘Dtype caffe::SigmoidCrossEntropyLossLayer<Dtype>::get_normalizer(caffe::LossParameter_NormalizationMode, int) [with Dtype = float]’:
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:75:41: warning: ‘normalizer’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return std::max(Dtype(1.0), normalizer);
                                         ^
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp: In member function ‘Dtype caffe::SigmoidCrossEntropyLossLayer<Dtype>::get_normalizer(caffe::LossParameter_NormalizationMode, int) [with Dtype = double]’:
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:75:41: warning: ‘normalizer’ may be used uninitialized in this function [-Wmaybe-uninitialized]
CXX src/caffe/layers/embed_layer.cpp
CXX src/caffe/layers/input_layer.cpp
CXX src/caffe/layers/cudnn_pooling_layer.cpp
CXX src/caffe/layers/split_layer.cpp
CXX src/caffe/layers/dummy_data_layer.cpp
CXX src/caffe/layers/normalize_layer.cpp
CXX src/caffe/layers/log_layer.cpp
CXX src/caffe/layers/base_data_layer.cpp
CXX src/caffe/layers/pooling_layer.cpp
CXX src/caffe/layers/tanh_layer.cpp
CXX src/caffe/layers/detection_evaluate_layer.cpp
CXX src/caffe/internal_thread.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/layer.cpp
CXX src/caffe/syncedmem.cpp
CXX tools/finetune_net.cpp
CXX tools/train_net.cpp
CXX tools/caffe.cpp
CXX tools/compute_image_mean.cpp
CXX tools/convert_annoset.cpp
CXX tools/device_query.cpp
CXX tools/get_image_size.cpp
CXX tools/upgrade_net_proto_binary.cpp
CXX tools/upgrade_net_proto_text.cpp
CXX tools/create_label_map.cpp
CXX tools/net_speed_benchmark.cpp
CXX tools/extract_features.cpp
CXX tools/test_net.cpp
CXX tools/convert_imageset.cpp
CXX tools/upgrade_solver_proto_text.cpp
CXX examples/mnist/convert_mnist_data.cpp
CXX examples/cifar10/convert_cifar_data.cpp
CXX examples/cpp_classification/classification.cpp
CXX examples/ssd/ssd_detect.cpp
CXX examples/siamese/convert_mnist_siamese_data.cpp
CXX .build_release/src/caffe/proto/caffe.pb.cc
tools/caffe.cpp: In function ‘caffe::SolverAction::Enum GetRequestedAction(const string&)’:
tools/caffe.cpp:177:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
CXX/LD -o .build_release/tools/finetune_net.bin
CXX/LD -o .build_release/tools/train_net.bin
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/tools/convert_annoset.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/device_query.bin
CXX/LD -o .build_release/tools/get_image_size.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/create_label_map.bin
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
CXX/LD -o .build_release/tools/test_net.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
CXX/LD -o .build_release/examples/ssd/ssd_detect.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
[ 21%] Performing build step for 'caffe_dd'
[ 25%] No install step for 'caffe_dd'
[ 28%] Completed 'caffe_dd'
[ 28%] Built target caffe_dd
Scanning dependencies of target ddetect
[ 32%] Building CXX object src/CMakeFiles/ddetect.dir/deepdetect.cc.o
[ 35%] Building CXX object src/CMakeFiles/ddetect.dir/caffelib.cc.o
[ 39%] Building CXX object src/CMakeFiles/ddetect.dir/caffemodel.cc.o
[ 42%] Building CXX object src/CMakeFiles/ddetect.dir/csvinputfileconn.cc.o
[ 46%] Building CXX object src/CMakeFiles/ddetect.dir/svminputfileconn.cc.o
[ 50%] Building CXX object src/CMakeFiles/ddetect.dir/txtinputfileconn.cc.o
[ 53%] Building CXX object src/CMakeFiles/ddetect.dir/caffeinputconns.cc.o
/data3/tensor/deepdetect-demo/deepdetect/src/caffeinputconns.cc:684:27: warning: unused parameter ‘ad_input’ [-Wunused-parameter]
            const APIData &ad_input,
                           ^
[ 57%] Building CXX object src/CMakeFiles/ddetect.dir/commandlineapi.cc.o
[ 60%] Building CXX object src/CMakeFiles/ddetect.dir/commandlinejsonapi.cc.o
[ 64%] Building CXX object src/CMakeFiles/ddetect.dir/apidata.cc.o
[ 67%] Building CXX object src/CMakeFiles/ddetect.dir/jsonapi.cc.o
[ 71%] Building CXX object src/CMakeFiles/ddetect.dir/httpjsonapi.cc.o
[ 75%] Building CXX object src/CMakeFiles/ddetect.dir/ext/rmustache/mustache.cc.o
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc: In function ‘void mustache::FindJsonPathComponents(const string&, std::vector<std::__cxx11::basic_string<char> >*)’:
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:97:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = start; i < path.size(); ++i) {
                         ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc: In function ‘int mustache::FindNextTag(const string&, int, mustache::TagOperator*, std::__cxx11::string*, std::__cxx11::string*, bool*, std::stringstream*)’:
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:154:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (idx < document.size()) {
              ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:155:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (document[idx] == '{' && idx < (document.size() - 3) && document[idx + 1] == '{') {
                                     ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:164:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       while (idx < document.size()) {
                  ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:169:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (!*is_triple && idx < document.size() - 1 && document[idx + 1] == '}') {
                                  ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:172:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           } else if (*is_triple && idx < document.size() - 2 && document[idx + 1] == '}'
                                        ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc: In function ‘int mustache::EvaluateSection(const string&, const string&, int, const Value*, mustache::TagOperator, const string&, const string&, std::stringstream*)’:
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:252:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < context->Size(); ++i) {
                       ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:266:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     while (idx < document.size()) {
                ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:274:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (idx > document.size()) return idx;
               ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc: At global scope:
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:291:40: warning: unused parameter ‘document’ [-Wunused-parameter]
 int EvaluateSubstitution(const string& document, const int idx,
                                        ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:316:34: warning: unused parameter ‘document’ [-Wunused-parameter]
 int EvaluateLength(const string& document, const int idx, const Value* parent_context,
                                  ^
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc: In function ‘void mustache::RenderTemplate(const string&, const string&, const Value&, std::stringstream*)’:
/data3/tensor/deepdetect-demo/deepdetect/src/ext/rmustache/mustache.cc:385:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (idx < document.size() && idx != -1) {
              ^
[ 78%] Building CXX object src/CMakeFiles/ddetect.dir/generators/net_caffe.cc.o
[ 82%] Building CXX object src/CMakeFiles/ddetect.dir/generators/net_caffe_mlp.cc.o
[ 85%] Building CXX object src/CMakeFiles/ddetect.dir/generators/net_caffe_convnet.cc.o
[ 89%] Building CXX object src/CMakeFiles/ddetect.dir/generators/net_caffe_resnet.cc.o
[ 92%] Linking CXX static library libddetect.a
[ 92%] Built target ddetect
Scanning dependencies of target dede
[ 96%] Building CXX object main/CMakeFiles/dede.dir/dede.cc.o
[100%] Linking CXX executable dede
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::OptionContainer(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/usr/local/include/curlpp/internal/OptionContainer.inl:38: undefined reference to `curlpp::internal::SList::SList(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::getValue()':
/usr/local/include/curlpp/internal/OptionContainer.inl:59: undefined reference to `curlpp::internal::SList::operator std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >[abi:cxx11]()'
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::internal::OptionContainer<std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::setValue(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/usr/local/include/curlpp/internal/OptionContainer.inl:52: undefined reference to `curlpp::internal::SList::operator=(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
../src/libddetect.a(httpjsonapi.cc.o): In function `curlpp::Info<(CURLINFO)2097154, long>::get(curlpp::Easy const&)':
/usr/local/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy const&, CURLINFO, long&)'
../src/libddetect.a(caffelib.cc.o): In function `curlpp::Info<(CURLINFO)2097154, long>::get(curlpp::Easy const&)':
/usr/local/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy const&, CURLINFO, long&)'
collect2: error: ld returned 1 exit status
main/CMakeFiles/dede.dir/build.make:122: recipe for target 'main/dede' failed
make[2]: *** [main/dede] Error 1
CMakeFiles/Makefile2:177: recipe for target 'main/CMakeFiles/dede.dir/all' failed
make[1]: *** [main/CMakeFiles/dede.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by beniz** [comment]
Look at #126
