### ISSUE TITLE
Service Bad Request Error

### ISSUE THREAD

**Issue by xxqcheers** [beniz/deepdetect#336]
I'm getting the following error when I try to build..

My OS is : Linux version 4.4.0-57-generic (buildd@lgw01-54) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016

following the document: https://www.deepdetect.com/tutorials/csv-training/

1)at one terminal use the command 
xuxiaoqiang@yh142:/data3/tensor/test-deepdetect/deepdetect/build/main$ ./dede -port 8081
DeepDetect [ commit 644dc5fddc61367685237408c6653b5108135573 ]

INFO - 11:33:09 - Running DeepDetect HTTP server on localhost:8081

2)at other terminal use the command:
curl -X PUT "http://localhost:8081/services/covert" -d '{"mllib":"caffe","description":"forest classification service","type":"supervised","parameters":{"input":{"connector":"csv"},"mllib":{"template":"mlp","nclasses":7,"layers":[150,150,150],"activation":"prelu"}},"model":{"templates":"../templates/caffe/","repository":"models/covert"}}'

at the current terminal  I get the respone : {"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}

the server terminal print message:  ERROR - 14:26:22 - Sat Jul 15 14:26:22 2017 CST - 127.0.0.1 "PUT /services/covert" 400 0

I want know what's the reason why "Service Bad Request Error"

**Comment by beniz** [comment]
Use an absolute path as `repository`.

Issues are for bugs and feature requests, please use gitter https://gitter.im/beniz/deepdetect for questions.

**Comment by xxqcheers** [comment]
@beniz Thanks
