### ISSUE TITLE
Support for customized  Layer in caffe?

### ISSUE THREAD

**Issue by coocoky** [beniz/deepdetect#338]
I  write customized  Layer in caffe, how to support for in deepdetect?

**Comment by beniz** [comment]
Hi you need to merge into our custom fork of Caffe. We already support many customized layers, and some more are to be merged by us soon, but if it's not already in there, just fork and merge your layer yourself.

**Comment by coocoky** [comment]
thank you @beniz , if I merge into the caffe in the deepdect project, which files I need to update? caffelib.cc? caffelib.h?   caffeinputconns.h? caffeinputconns.cc?

**Comment by beniz** [comment]
None if your new layer is not an input or output layer.

**Comment by coocoky** [comment]
if i changed input or output layer? @beniz

**Comment by beniz** [comment]
Then it's for you to figure it out.
