### ISSUE TITLE
Parameter `shuffle` should not be set to False for txt and image connectors

### ISSUE THREAD

**Issue by YaYaB** [beniz/deepdetect#347]
I have an issue with th parameter ```Shuffle``` of the connectors txt and images.
By default ```Shuffle``` is set to false, that seems in a generic point of view correct but knowing how Deep Detect createe the lmdb it seems to be an issue.

#### Configuration
- Version of DeepDetect:
    - Locally compiled on Ubuntu 16.04 LTS
- Commit (shown by the server when starting):
    - Branch `Master`, 62ea2f4c84fe2f10ea9f1ed465139e7a1fc0ef8b
- GPUS:
    - 1 x Nvidia GTX Titan X (Maxwell)

#### Your question / the problem you're facing:
I tested the txt connector and I saw that I can decide to shuffle or not my data.
The data indicated to Deep Detect for training purposes is clustered by class. 
It is compounded of one folder for each class. When the request for training is launched, Deep Detect reads sequentially through those folders.

Let us imagine that we have 10k examples uniformly distributed among 4 classes.
Then we will have 4 folders: 1, 2,3 and 4. We want to train without shuffling so we do not indicate ```Shuffle``` letting it to be `False` by default.

At training time, Deep Detect will read sequentially each folder (not necessarily beginning from the folder 1). Then it creates the LMDB using those examples. The issue is that the major part of the batches will contain examples from the same class. Then the training will fail as the neural network will `always` predict the first class that it saw.

It seems to me necessary to shuffle the data in some way so that we have batches with different labels. That might be as other people do with Caffe: having a file containing names of examples in the order we can define.

**Comment by beniz** [comment]
Thanks, can you check PR #349 and report on whether this fixes the issue ? Thanks.

**Comment by YaYaB** [comment]
It does not work for me.
I think you should modify the following files where `shuffle` is hardcoded.
- https://github.com/beniz/deepdetect/blob/5067658a69deeda46e06f14b0527180f59d018a1/src/txtinputfileconn.h (line 335)
- https://github.com/beniz/deepdetect/blob/5067658a69deeda46e06f14b0527180f59d018a1/src/imginputfileconn.h (line 406)

**Comment by YaYaB** [comment]
After testing it properly, my previous comment is still true. It does not work yet.
Either you can do the modifications I gave you (I tested it and it works). Or you can do the following modifications (I tested it as well and it works).

Modify the following file https://github.com/beniz/deepdetect/blob/5067658a69deeda46e06f14b0527180f59d018a1/src/caffeinputconns.h by adding in the second constructor `shuffle = true;` as well:
- line 102:
```
:ImgInputFileConn(i),CaffeInputInterface(i) { _db = true;  _shuffle = true;}
```
- line 652:
```
:TxtInputFileConn(i),CaffeInputInterface(i) {_shuffle = true;}

Do you want me to make that PR?

**Comment by beniz** [comment]
Thanks, I've favored making the change from within the `transform()` call. PR #349 has been updated and is working for me. Let me know how it works for you.

**Comment by YaYaB** [comment]
It works well for me!
Nicely done :)

**Comment by beniz** [comment]
Thanks, merged.
