### ISSUE TITLE
problem using the pretrained model 

### ISSUE THREAD

**Issue by Vgandhi9** [beniz/deepdetect#35]
I was trying to build a system using the pretrained model available here: http://www.deepdetect.com/applications/model/

I downloaded the .tar.gz2 files for the clothing class. I then tried to build a simple python script using caffe to use the files provided with the pretrained model. But when I was creating the caffe Classifier class I faced a very strange error.

This is how I created the classifier class in caffe using Python, 
<code>
network_model = "./deploy.prototxt"
pretrained_network = "./model_iter_300000.caffemodel"
net = caffe.Classifier(network_model,pretrained_network,mean=np.load("mean.npy"), raw_scale=255, channel_swap=(2, 1, 0), image_dims=(256,256))</code>

The deploy.prototxt and the model_iter_300000.caffemodel are the files which are present inside the .tar.gz2 file
The mean.npy file is created using the mean.binaryproto file present inside the .tar.gz2 file.

and the error that I was getting was

<code>
I1130 08:07:26.102867  4413 net.cpp:248] Memory required for data: 1764597888
Traceback (most recent call last):
  File "predict.py", line 32, in <module>
    mean=np.load("mean.npy"), raw_scale=256, channel_swap=(2, 1, 0), image_dims=(256,256))
  File "/home/caffe/python/caffe/classifier.py", line 29, in __init__
    in_ = self.inputs[0]
IndexError: list index out of range
</code>

Can any one help me with this strange error?

Thanks

**Comment by beniz** [comment]
hi @Vgandhi9 unfortunately I cannot provide support for straight Caffe. That said, in the present case I believe you need to pass a 224x224 image instead of a a 256x256. DeepDetect does the conversion automatically for you, but with Caffe, you may need to do this yourself.

**Comment by Vgandhi9** [comment]
Hi @beniz  I changed  the image size to 224X224 but still I am facing the same error.

**Comment by beniz** [comment]
The mean should be 224x224 also I believe. You next best bet is to quick run DD instead and check that it works fine before getting back to vanilla Caffe if you really need to.

**Comment by Vgandhi9** [comment]
My mean is also 224X224 and yes I think i'll shift to DD instead of vanilla caffe.
Thanks @beniz

**Comment by Vgandhi9** [comment]
Hello @beniz  a small query what is the raw scale of the image to be given. I mean what is the range of pixel values of the input image should it be in the range of [0,256) or [0,1]?

**Comment by beniz** [comment]
It should be [0,256], internally the image is decoded with opencv, so this deals pretty naturally with a range of formats (but .gif).

**Comment by Vgandhi9** [comment]
Thanks @beniz

**Comment by Vgandhi9** [comment]
Helllo @beniz  I have modified the deploy.prototxt file and the pretrained model worked for me very well.
I am attaching the modified deploy.prototxt file below.
[deploy.prototxt.txt](https://github.com/beniz/deepdetect/files/48220/deploy.prototxt.txt)

**Comment by beniz** [comment]
@Vgandhi9 I guess you mean working with straight Caffe, right ? This might be useful to others.

**Comment by Vgandhi9** [comment]
Yes thats correct @beniz.
