### ISSUE TITLE
some suggestions to construct a mnist demo to classify

### ISSUE THREAD

**Issue by BT123** [beniz/deepdetect#352]
I found that there is a demo for mnist, but it's a autoencoder.
I want to construct a mnist demo for classify handwritten digit .
Can you give  me some suggestions to do that?

I  try it, but I never succeed.
My attempt is as follows:
# create service
curl -X PUT 'http://localhost:8080/services/mnist' -d '{"mllib":"caffe","description":"mnist classfier","type":"supervised","parameters":{"input":{"connector":"csv"},"mllib":{"template":"mlp","nclasses":10,"layers":[500,250,30,250,500],"activation":"sigmoid"}},"model":{"repository":"/home/aaa/deepdetect/models/mnist/mnist"}}'

And this will return ok.

# prediction
curl -X POST 'http://localhost:8080/predict' -d '{"service":"mnist","parameters":{"mllib":{"gpu":false},"input":{"ignore":["label"],"id":"ID","separator":",","scale":true},"output":{"measure":["eucll"]}},"data":["./1.csv"]}'

Looking forward to your reply!

**Comment by beniz** [comment]
Hi, if you look at the unit tests, e.g. https://github.com/beniz/deepdetect/blob/master/tests/ut-caffeapi.cc#L230 you'll find a good example of training + predicting out of MNIST dataset.

The tutorials provide easy ways to setup a demo service for image tagging models that we usually find more useful than MNIST. Maybe this is something you can look at as well.
