### ISSUE TITLE
Print estimated time of training

### ISSUE THREAD

**Issue by EBazarov** [beniz/deepdetect#355]
That will be useful to see estimated time of training in a logs of DeepDetect or estimation of rest training time. It can be computed by using `iter_time` measure value.

**Comment by beniz** [comment]
This has been worked on in PR #380 as follows in the JSON output from `GET /train`:

- `remain_time` reports the remaining time in seconds
- `remain_time_str` reports the remaining time as days, hours, minutes and seconds as a human readable string.
