### ISSUE TITLE
another trained model

### ISSUE THREAD

**Issue by skirak** [beniz/deepdetect#357]
I have my already trained model that classify objects of 4 classes (blood cells). How can I use it to detect objects (drawing bounding boxes) on an input image with your code? What I have to change?

**Comment by beniz** [comment]
Hi, you'd need to train an object detector with SSD for it to be compatible with DD. SSD can be found here: https://github.com/weiliu89/caffe/tree/ssd that has the instructions for training (or using our own custom Caffe, https://github.com/beniz/caffe). You'll have to put your dataset into the proper format as well.
