### ISSUE TITLE
Using pip-installed TensorFlow

### ISSUE THREAD

**Issue by mattiasarro** [beniz/deepdetect#359]
I am considering using deepdetect (DD) for building TensorFlow (TF) classifiers, whose input comes from and output goes to ElasticSearch. I am developing on macOS, which is [not supported](https://github.com/beniz/deepdetect/issues/70), so I'm considering just developing my TF models locally, but deploying them with DD on Ubuntu. I need to deploy to GCP, so can't use the AWS AMIs. So I'm building DD on a ubuntu 16.04 Docker container with TF support, following the steps in README.

Compiling TensorFlow is time-consuming and brittle, while installing TF with pip is fast and reliable. Also the current installation uses TF 1.0, while 1.4 will be released soon.

So my quetion is: does TF need to be compiled from source or would it be possible to remove the TF-specific parts from the makefile so that I could manually manage my TF installation?

**Comment by beniz** [comment]
> Also the current installation uses TF 1.0, while 1.4 will be released soon.

1.4 is on our todolist but TF is a pain to build and 1.3 broke the building process that was working for us (and others), and we couldn't find a quick fix, thus we stayed with 1.0.

We're contemplating using https://github.com/FloopCZ/tensorflow_cc in order to avoid some of the bazel hell.

> what does TF eed to be compiled from source

Unfortunately, AFAIK it does in order to properly expose the C++ API.

**Comment by SebScoFr** [comment]
I'm building a Dockerfile to try and make a custom Docker image of Deepdetect with TF support.
Here is the content of my Dockerfile
```
FROM ubuntu:16.04
MAINTAINER Sebastien <seb.esquevin@octer.com>

RUN apt-get update && \
    apt-get install -y build-essential libgoogle-glog-dev libgflags-dev libeigen3-dev libopencv-dev libcppnetlib-dev libboost-dev libboost-iostreams-dev libcurlpp-dev libcurl4-openssl-dev protobuf-compiler libopenblas-dev libhdf5-dev libprotobuf-dev libleveldb-dev libsnappy-dev liblmdb-dev libutfcpp-dev cmake autoconf autogen libgoogle-perftools-dev unzip git htop vim && \
    apt-get remove -y libcurlpp0

RUN apt-get install -y openjdk-8-jdk && \
    echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \
    curl https://bazel.build/bazel-release.pub.gpg | apt-key add - && \
    apt-get update && apt-get install -y bazel && \
    apt-get upgrade -y bazel

RUN mkdir -p /var && \
    cd /var && \
    git clone https://github.com/beniz/deepdetect.git

RUN mkdir -p /usr/local/bin && \
    cd /usr/local/bin && \
    git clone https://github.com/jpbarrette/curlpp.git && \
    cd curlpp && \
    cmake . && \
    make install

RUN mkdir /var/deepdetect/build && \
    cd /var/deepdetect/build && \
    cmake .. -DUSE_TF=ON -DUSE_TF_CPU_ONLY=ON && \
    make clean && \
    make
```

It gets to the last `make`, but fails with:

```
...
Scanning dependencies of target tensorflow
[  2%] Creating directories for 'tensorflow'
[  5%] Performing download step for 'tensorflow'
Cloning into 'tensorflow'...
[  7%] No patch step for 'tensorflow'
[ 10%] No update step for 'tensorflow'
[ 13%] Performing configure step for 'tensorflow'
Note: checking out 'v1.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e895d5c... Fixing 2 minor issues as suggested by Gunan.
checking file tensorflow/BUILD
Unreversed patch detected!  Ignore -R? [n]
Apply anyway? [n]
Skipping patch.
3 out of 3 hunks ignored
patching file tensorflow/BUILD
Hunk #1 succeeded at 242 (offset 36 lines).
Hunk #2 succeeded at 252 (offset 36 lines).
Hunk #3 succeeded at 263 (offset 36 lines).
checking file tensorflow/python/BUILD
Hunk #1 succeeded at 2413 (offset 572 lines).
make[2]: *** [tensorflow/src/tensorflow-stamp/tensorflow-configure] Error 1
make[1]: *** [CMakeFiles/tensorflow.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/tensorflow.dir/build.make:105: recipe for target 'tensorflow/src/tensorflow-stamp/tensorflow-configure' failed
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tensorflow.dir/all' failed
Makefile:83: recipe for target 'all' failed
The command '/bin/sh -c cd /var/deepdetect/build && make' returned a non-zero code: 2
```
Any clue what I might be missing?

**Comment by cchadowitz-pf** [comment]
Not sure what versions you're using for all the bits and pieces, but check out the following Dockerfile: https://github.com/beniz/deepdetect/blob/master/docker/cpu-caffe-tf/Dockerfile

There is also a similar one that includes GPU support, but I haven't tested that one as thoroughly.

**Comment by SebScoFr** [comment]
Thanks @cchadowitz-pf, using that Dockerfile the build works fine. I wish I could have found that before!
@beniz Just out of curiosity, what's currently stoping you from building an official beniz/deepdetect:tf image from that Dockerfile.

**Comment by beniz** [comment]
@SebScoFr not much besides the cuda compute numbers that depend on hardware configuration. The TF build needs to be refactored in order to cope with new versions.

**Comment by SebScoFr** [comment]
Looking forward to a TF build with 1.4 and above.
Anyway, thanks for the help on this guys.
