### ISSUE TITLE
Custom input data from mobile robot

### ISSUE THREAD

**Issue by nikfio** [beniz/deepdetect#362]
I am very interested in deepdetect application and purpose. 
I have a question, could it be implemented in a runtime program where a mobile robot communicates with a server responsible for the learning calculation?
I'll explain better, my idea is to use a desktop pc with a powerful gpu as a server. Meanwhile, a raspberry or a laptop are placed on the moving robot, send sourrounding informations to the network as a flattened vector and collect the outcome as the next direction to go.
Could this be feasible with deepdetect or do i have to build my own server client model for sending and receiving data across the nework?

Best regards.

**Comment by beniz** [comment]
Hi, the prediction phase could use the DD server on your desktop yes.

**Comment by nikfio** [comment]
Thank you for your reply.
Is it because during training output cannot be requested at each step?

**Comment by beniz** [comment]
Sort of. Unless you really know what you're doing, you should do the training offline.

**Comment by nikfio** [comment]
During training, the robot is moved by an proved algorithm working as supervisor, output would be needed to calculate the precision, however it's not really necessary to know this value by the mobile robot.

**Comment by beniz** [comment]
Not sure I understand. Use the gitter channel if you'd like to discuss as issues are for features and bugs mostly. Thanks!
