### ISSUE TITLE
I have just installed deepdetect on ubuntu 14.04. when I run the server I get an error message "DeepDetect [ commit 12468b9faef12cdb0e0423959aba50095cf15667 ]  INFO - 13:26:47 - Running DeepDetect HTTP server on localhost:8080 terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >'   what():  Error binding to socket. Aborted (core dumped)". How to resolve this? Thanks in advance.

### ISSUE THREAD

**Issue by KrishnaGapileswar** [beniz/deepdetect#370]
(A Markdown syntax reminder is available here: https://guides.github.com/features/mastering-markdown/)

Before creating a new issue, please make sure that:
- [ ] the problem isn't already identified in the in the [FAQ page](http://www.deepdetect.com/overview/faq/ "DeepDetect FAQ page"),
- [ ] your problem isn't listed in an existing issue ([open](https://github.com/beniz/deepdetect/issues) or [closed](https://github.com/beniz/deepdetect/issues?q=is%3Aissue+is%3Aclosed) one),
- [ ] [all prerequisite tools](http://www.deepdetect.com/overview/installing/ "DeepDetect installation page") and [dependencies](https://github.com/beniz/deepdetect#user-content-dependencies "DeepDetect README page on Github") are installed.

If Ok, please give as many details as possible to help us solve the problem more efficiently.
#### Configuration
- Version of DeepDetect:
    - [ ] Locally compiled on:
        - [ ] Ubuntu 14.04 LTS
        - [ ] Mac OSX
        - [ ] Other:
    - [ ] Docker
    - [ ] Amazon AMI
- Commit (shown by the server when starting):

#### Error message (if any) / steps to reproduce the problem:
- [ ] list of API calls:

- [ ] Server log output:

**Comment by beniz** [comment]
Your port is already binderd.  Please fill out the form next time.
