### ISSUE TITLE
Training data with docker deepdetect

### ISSUE THREAD

**Issue by taiwotman** [beniz/deepdetect#375]
I am get an error on the server with docker deepdetect setup:

> ERROR - 18:59:41 - couldn't write to model.json file in model repository /opt/models/ggnet/ 

This was after creating a service and training a data.
My data is of this form

> train data director
>    ->dogs folder
>        dog image files(jpg).
>    -> cat folder
>        cat image files(jpg)

But I am not quite sure what is the root cause of the error.

**Comment by beniz** [comment]
Hi, this is very likely a docker issue. Make sure you have mounted the external folder with data to the running docker. Look at the docker readme and docker documentation in general. Also please follow the form and post all API calls etc...

**Comment by taiwotman** [comment]
Actually, I have mounted the external folder  and on the command line after running the POST REST command
```
curl -X POST "http://localhost:8080/train" -d '{
       "service":"imageserv",
       "async":true,
       "parameters":{
         "mllib":{
           "gpu":true,
           "net":{
             "batch_size":32
           },
           "solver":{
             "test_interval":500,
             "iterations":30000,
             "base_lr":0.001,
             "stepsize":1000,
             "gamma":0.9
           }
         },
         "input":{
           "connector":
           "image",
           "test_split":0.1,
           "shuffle":true,
           "width":224,
           "height":224},
         "output":{
           "measure":["acc","mcll","f1"]
         }
       },
       "data":["data/congestion_train"]}'
```

I get the following on the command line:

> {"status":{"code":201,"msg":"Created"},"head":{"method":"/train","job":3,"status":"running"}}

But I was expecting to see the following on the server 
```
...
INFO - Processed 1000 files.
INFO - Processed 2000 files.
INFO - Processed 3000 files.
INFO - Processed 4000 files.
INFO - Processed 4198 files.
...
```
but I got the aforementioned error.

**Comment by beniz** [comment]
The server may not have the rights to write in `/opt`, so either make that writable or move the model directory somewhere it can be written to, like your mounted drive.

**Comment by taiwotman** [comment]
I thought as much. Thank you.

**Comment by taiwotman** [comment]
I also think it is ok to assume that training cannot be done on the docker deepdetect for now due to the write issue with `/opt/models/ggnet/`

**Comment by beniz** [comment]
You can train fine with DD docker by using any user writable directory, or changing the rights as you do do on any system I guess.
