### ISSUE TITLE
Error while converting to TensorFlow model

### ISSUE THREAD

**Issue by nishantprateek** [beniz/deepdetect#38]
I am trying to convert the clothing dataset to a model compatible wth TensorFlow using https://github.com/ethereon/caffe-tensorflow. 

I am getting the following error:
"Error encountered: Cannot determine dimensions of data layer.
See comments in function shape_identity for more info."

The comment on the shape_identity function says:
 # We most likely have a data layer on our hands. The problem is,
    # Caffe infers the dimensions of the data from the source (eg: LMDB).
    # We want to avoid reading datasets here. Fail for now.
    # This can be temporarily fixed by transforming the data layer to
    # Caffe's "input" layer (as is usually used in the "deploy" version).
    # TODO: Find a better solution for this.

Can someone suggest the necessary changes in deploy.prototxt file?

**Comment by beniz** [comment]
Might help to take a look at the conversation in https://github.com/beniz/deepdetect/issues/35

**Comment by nishantprateek** [comment]
Hi,
I changed the input layer to: 
input: "data"
input_shape {
  dim: 32
  dim: 3
  dim: 224
  dim: 224
}

But now, I get the following error: "Error encountered: Layer not found: loss1/conv". I am running deploy.prototxt with model_iter_300000.caffemodel

**Comment by beniz** [comment]
This is not really related to dd, and you should ask on the caffe-tensorflow repo and the tf mailing list.
