### ISSUE TITLE
Fail To Link gflag

### ISSUE THREAD

**Issue by whs2k** [beniz/deepdetect#386]
Hello,

Excited to use this service with elasticsearch but running into and issue at the end of compilation: 

> Linking CXX executable dede
> /bin/ld: warning: libgflags.so.2, needed by /data/wsolomon/workspace/workspace/packages/deepdetect/build/caffe_dd/src/caffe_dd/build/lib/libcaffe.so, may conflict with libgflags.so.2.1
> /bin/ld: CMakeFiles/dede.dir/dede.cc.o: undefined reference to symbol '_ZN6google21ParseCommandLineFlagsEPiPPPcb'
> /usr/local/lib/libgflags.so.2: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: *** [main/dede] Error 1
> make[1]: *** [main/CMakeFiles/dede.dir/all] Error 2
> make: *** [all] Error 2

The issue seems to be with the flags in Caffe. I was able to cmake and compile Caffe independantly on its own as a check.

- Running Linux RedHat Centos 7
- Used the [greate guidance by @Isaacpm for installing all the dependencies in Centos](https://github.com/beniz/deepdetect/issues/71)
- Attempted to troubleshoot with guidance from [this closed Caffe issue](https://github.com/BVLC/caffe/issues/2852)

Any ideas appreciated!

**Comment by beniz** [comment]
Hi, it seems you have two versions of libgflags and somehow caffe is built with one and DD with another.  Not sure how this has happened but I recommebd you get rid of one of the two.

Please post the full building log. If you know what you are doing, you may want to add a `-lgflags` at the end of the linker GCC line to see whether this changes anything.

This is not an issue with caffe but with the final linking of DD.

**Comment by whs2k** [comment]
That's it!
```
Sudo yum search gflags

> gflags-devel.x86_64 : Development files for gflags
> gflags.x86_64 : Library for commandline flag processing
> python2-gflags.noarch : Commandline flags module for Python 2

sudo yum remove gflags-devel.x86_64
```
And it builds and links successfully. Thanks!

**Comment by lrakesh24** [comment]
hello i am building caffe using opencv 2.4, while building i am getting these Errors.

AR -o .build_release/lib/libcaffe.a
CXX tools/upgrade_solver_proto_text.cpp
CXX tools/convert_imageset.cpp
CXX tools/extract_features.cpp
CXX tools/upgrade_net_proto_text.cpp
CXX tools/caffe.cpp
CXX tools/upgrade_net_proto_binary.cpp
CXX tools/compute_image_mean.cpp
CXX examples/siamese/convert_mnist_siamese_data.cpp
CXX examples/mnist/convert_mnist_data.cpp
CXX examples/cifar10/convert_cifar_data.cpp
CXX examples/cpp_classification/classification.cpp
CXX/LD -I/usr/local/include/opencv -I/usr/local/include /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -latomic -ltbb /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libGLU.so -lrt -lpthread -lm -ldl -o .build_release/tools/convert_imageset.bin
CXX/LD -I/usr/local/include/opencv -I/usr/local/include /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -latomic -ltbb /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libGLU.so -lrt -lpthread -lm -ldl -o .build_release/tools/compute_image_mean.bin
/usr/bin/ld: warning: libgflags.so.2, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libglog.so, may conflict with libgflags.so.2.2
.build_release/lib/libcaffe.so: undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `vtable for cv::_InputArray'
collect2: error: ld returned 1 exit status
Makefile:634: recipe for target '.build_release/tools/convert_imageset.bin' failed
make: *** [.build_release/tools/convert_imageset.bin] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: warning: libgflags.so.2, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libglog.so, may conflict with libgflags.so.2.2
.build_release/lib/libcaffe.so: undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `vtable for cv::_InputArray'
collect2: error: ld returned 1 exit status
Makefile:634: recipe for target '.build_release/tools/compute_image_mean.bin' failed
make: *** [.build_release/tools/compute_image_mean.bin] Error 1

**Comment by beniz** [comment]
@lrakesh24  Hi, this issue is closed and was for a much earlier version of the code. Can you open a new issue and fill the form up with your Ubuntu version, hardware platform, initial `cmake` output etc.., thanks!
