### ISSUE TITLE
No able to run DEDE server

### ISSUE THREAD

**Issue by s348ankit** [beniz/deepdetect#402]
![capture](https://user-images.githubusercontent.com/29064603/39424548-ded8d958-4c94-11e8-9768-59eb2debc01e.PNG)

ubuntu@BigData-Practice:~/.local/install/deepdetect/deepdetect/build$ make
[ 19%] Built target caffe_dd
[ 61%] Built target ddetect
[ 66%] Built target dede
[ 71%] Built target ut_httpapi
[ 76%] Built target ut_caffeapi
[ 80%] Built target ut_caffe_mlp
[ 85%] Built target ut_apidata
[ 90%] Built target ut_jsonapi
[ 95%] Built target ut_conn
[100%] Built target test_server
ubuntu@BigData-Practice:~/.local/install/deepdetect/deepdetect/build$ ^C
ubuntu@BigData-Practice:~/.local/install/deepdetect/deepdetect/build$ cd main
ubuntu@BigData-Practice:~/.local/install/deepdetect/deepdetect/build/main$ dede
dede: command not found

What could be solution of this problem

**Comment by xoolive** [comment]
Try `./dede`
