### ISSUE TITLE
building error on ubuntu 14.04.

### ISSUE THREAD

**Issue by zyyang** [beniz/deepdetect#42]
Error happens when making by following the official building steps:
(Titan X, with drivers and cuda 7.5, cudnn 3 properly installed)

```shell
git clone https://github.com/beniz/deepdetect.git
cd deepdetect
mkdir build
cd build 
cmake .. -DUSE_CUDNN=ON
make
```

error messages:

```shell
......
NVCC src/caffe/layers/batch_reindex_layer.cu
NVCC src/caffe/layers/contrastive_loss_layer.cu
NVCC src/caffe/layers/slice_layer.cu
NVCC src/caffe/layers/tile_layer.cu
NVCC src/caffe/layers/elu_layer.cu
NVCC src/caffe/layers/silence_layer.cu
NVCC src/caffe/layers/softmax_layer.cu
NVCC src/caffe/layers/cudnn_softmax_layer.cu
NVCC src/caffe/layers/sigmoid_layer.cu
NVCC src/caffe/layers/im2col_layer.cu
NVCC src/caffe/layers/cudnn_conv_layer.cu
NVCC src/caffe/layers/eltwise_layer.cu
NVCC src/caffe/layers/exp_layer.cu
NVCC src/caffe/layers/prelu_layer.cu
NVCC src/caffe/layers/absval_layer.cu
NVCC src/caffe/layers/dropout_layer.cu
NVCC src/caffe/util/math_functions.cu
NVCC src/caffe/util/im2col.cu
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
make[3]: *** [.build_release/lib/libcaffe.so] Error 1
make[2]: *** [caffe_dd/src/caffe_dd-stamp/caffe_dd-configure] Error 2
make[1]: *** [CMakeFiles/caffe_dd.dir/all] Error 2
make: *** [all] Error 2

```
It seems like caffe is not compiled successfully.

**Comment by zyyang** [comment]
problem solved: lack of libopenblas-dev

**Comment by lovableLavz** [comment]
While am running the same command

> git clone https://github.com/beniz/deepdetect.git
cd deepdetect
mkdir build
cd build 
cmake .. -DUSE_CUDNN=ON
make

 , it showing like this 
`~/deepdetect/build$ make
[  2%] Performing download step for 'tensorflow'
Cloning into 'tensorflow'...
remote: Counting objects: 245034, done.
fatal: write error: **No space left on device78 MiB | 929.00 KiB/s**    
fatal: index-pack failed
CMakeFiles/tensorflow.dir/build.make:88: recipe for target 'tensorflow/src/tensorflow-stamp/tensorflow-download' failed
make[2]: *** [tensorflow/src/tensorflow-stamp/tensorflow-download] Error 128
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tensorflow.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`


Even i increased the disk space upto 2TB .. i dono why it showing "No space left on device78 MiB | 929.00 KiB/s"

please anyone help me ...
