### ISSUE TITLE
Potential error in googlenet example in documentation ("setup of an image classifier")

### ISSUE THREAD

**Issue by revilokeb** [beniz/deepdetect#44]
I have tried the step-by-step example in the doc for setting up an image classifier (http://www.deepdetect.com/tutorials/imagenet-classifier/) based on googlenet (successfull dede installation incl run test on commit 66ff4afaf743a77d53b63564207e644f161a1ac6). I am successfull in setting up the service ({"status":{"code":201,"msg":"Created"}}), but I am failing in tests as follows:

In: curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"

Out: {"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"./include/caffe/layer.hpp:389 / Check failed (custom): (ExactNumTopBlobs()) == (top.size())"}}

Comments:
1. Error code seems to hint at mismatch of some blob size in bvlc_googlenet.caffemodel vs. deploy.prototxt, however the trained model is coming directly from caffe model zoo and deploy.prototxt from ~/deepdetect/build/templates/caffe/googlenet/ is untouched (and copied by dede to ~/deepdetect/models/imgnet)
2. A comparison of deploy.prototxt with the original deploy.prototxt from caffe (without MemoryData layer) looks identical
3. When running the same code with alexnet (instead of googlenet, and after adjusting image size to 227) it is working

Any ideas why I am failing the googlenet example?

**Comment by beniz** [comment]
I can reproduce so there must be a regression somewhere.  Thanks for reporting this. Will keep you posted for fix.

**Comment by beniz** [comment]
Thanks again for reporting, this does the trick for me: caffe requires the label to be mentioned in deploy file as the input's top is 2D from the training phase = data + label.

**Comment by revilokeb** [comment]
Many thanks for your quick help, now it is working perfectly.
