### ISSUE TITLE
Deepdetect crashes often without any warning

### ISSUE THREAD

**Issue by shashi-netra** [beniz/deepdetect#45]
I get an `aborted (core dumped)` message every so often and Deepdetect stops. I am using it to tag images with the imagenet model

Sometimes the issue is obvious such as a very large image or a dead link, but often it is just a normal image for no discernible reason.

**Comment by beniz** [comment]
Can you post the typical server log that leads to such a crash, along with the `predict` POST single or batch call ?
Also, if you are not running the currrent `master` branch, it would be useful if you could specify which commit you're on.

**Comment by shashi-netra** [comment]
Thanks for your reply.
I pulled from the master about 1 month ago for my current install (commit: bda863348dac73c60ef279b09ca1b321587025df)
After looking into the issue some more, it seems the issue is with throwing errors leading to unhandled exceptions and causing the OS to call terminate()

This happens with image formats not supported by OpenCV (such as .gif):

    curl -X POST "http://xxx.com:8080/predict" -d "{\"service\":\"imgnet\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":5}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"

works fine, but:

    curl -X POST "http://xxx.com:8080/predict" -d "{\"service\":\"imgnet\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":5}},\"data\":[\"https://upload.wikimedia.org/wikipedia/en/3/39/Specialist_Science_Logo.gif\"]}"
    terminate called after throwing an instance of 'dd::InputConnectorBadParamException'
    what():  no data for image https://upload.wikimedia.org/wikipedia/en/3/39/Specialist_Science_Logo.gif
    curl: (52) Empty reply from server
    [1]+  Aborted                 (core dumped) ./deepdetect/build/main/dede -stderrthreshold 0 --host xxx.com > dede.txt

Similarly, broken links cause a crash:

    terminate called after throwing an instance of 'dd::InputConnectorBadParamException'
    what():  no data for image http://i.ytimg.com/not_a_real_link.jpg
    curl: (52) Empty reply from server
    [1]+  Aborted                 (core dumped) ./deepdetect/build/main/dede -stderrthreshold 0 --host xxx.com > dede.txt


Thanks in advance for your help.

**Comment by beniz** [comment]
Thanks for the thorough report. The crash with `.gif` can be reproduced so I'll clear this asap. 

Note that the `.gif` are not handled at the moment (nor for training or prediction) since they are made of multiple frames. What do you expect from classifying a `.gif`, getting a prediction over the first frame or a prediction of each of the frame ?

**Comment by beniz** [comment]
Commit above fixes the regression following parallelized image reading. Thanks for reporting this one.
