### ISSUE TITLE
Create Deepdetect server on 0.0.0.0:80 on AWS EC2

### ISSUE THREAD

**Issue by masakinakada** [beniz/deepdetect#48]
Dear community
I am trying to create deepdetect server on aws ec2. 
When I type this command, ./main/dede -host 0.0.0.0 -port 80

I get this following 
DeepDetect [ commit 8080e7b80i999ba444e671780a80fa4d1afdai0 ]
Running DeepDetect HTTP server on 0.0.0.0:80
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >'
  what():  Error binding to socket.
Aborted (core dumped)

Does anyone know how to solve this issue?
I want to allow HTTP access. 

Thank you very much for your kind help in advance.

**Comment by beniz** [comment]
Two things here:

- you may need root privileges to bind on port 80, try
```
sudo ./main/dede -host 0.0.0.0 -port 80
```
- or you may have something else already listening on port 80, typically nginx, apache or related.

**Comment by masakinakada** [comment]
Thank you so much for your quick response Beniz!
I tried your solution and tried to change the security group on ec2. However, it still did not work. 
I decided to use completely different port and it worked. 
I am sorry that I am not very good at backend. Like you said, something else should be running on port 80..
