### ISSUE TITLE
Error using gpu while prediction

### ISSUE THREAD

**Issue by skeeph** [beniz/deepdetect#53]
Hello.
I've built DeepDetect docker image using `kaixhin/cuda` (https://hub.docker.com/r/kaixhin/cuda/~/dockerfile/ ) as base image. Here https://gist.github.com/skeeph/a1722053872552c62594 is my Dockerfile. I've built it without any errors.
After that, I create image classification service from tutorial. It works properly, with `gpu=false`.
But if i try to use gpu on prediction stage, by stating `gpu=true` in service creating api call, i have next situation. Trying to classificate any image, i have error
`{
"status": {
"code": 500,
"dd_code": 1007,
"dd_msg": "src/caffe/common.cpp:142 / Check failed (custom): (error) == (cudaSuccess)",
"msg": "InternalError"
}
}`
I have server with installed NVidia Tesla K80.

What is my error? Is it possible to use gpu on prediction?
Thanks.

**Comment by beniz** [comment]
This is very likely to be a Cuda installation problem, so let's check on this. What does `nvidia-smi` report on your system ?
