### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [beniz/deepdetect#54]
[An extra null pointer check is not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") in the function "[`CaffeLib<TInputConnectorStrategy,TOutputConnectorStrategy,TMLModel>::create_model`](https://github.com/beniz/deepdetect/blob/5ac6e9b61d404a80ec2e9d6ca1878004f9c1fe23/src/caffelib.cc#L1163 "CaffeLib<TInputConnectorStrategy,TOutputConnectorStrategy,TMLModel>::create_model function")".

**Comment by beniz** [comment]
Ah thanks! This definitely smells fear, bad habit I reckon.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/beniz/deepdetect/commit/22d6864f967ab01fd9f73a6ab9fb1f3acc3774a8 "Deletion of a few unnecessary checks").

**Comment by beniz** [comment]
Thanks for being such a watcher! I'm curious, do you have some tool that compiles random github project and then let know authors of potential improvements ?

**Comment by elfring** [comment]
How do you think about to try a search interface out like it is provided by GitHub for any more use cases?

Are you looking for higher level tools which would support such software fine-tuning?

**Comment by beniz** [comment]
I'm always looking for tools that can automate anything, including the quality of code, but time being scarce, to succeed with me I've observed they need to be rather simple to setup and maintain.

**Comment by elfring** [comment]
Would you like to help in the support for developments around software which can transform source code in a programming language like "C" in a way so that advanced data processing could also be better handled for C++?

**Comment by beniz** [comment]
I guess I get a rough idea of the concept. I'd be happy to look and bookmark a repository for potential later use. Current time is a bit scarce to make promises...

**Comment by elfring** [comment]
Should I wait with further tool suggestions until you feel a bit more ready to continue a corresponding discussion?

**Comment by beniz** [comment]
Can you paste links ? I will check them, it is unlikely I would be able to participate in support or development of these tools.

**Comment by elfring** [comment]
[The programming language "C++"](https://en.wikipedia.org/wiki/C%2B%2B "Description for the C++ programming language") belongs to [the category of context-dependent languages](https://en.wikipedia.org/wiki/Context-sensitive_language "Description for context-sensitive languages"). This fact results in various software development challenges, doesn't it?

* I am occasionally working with [the semantic patch language](https://en.wikipedia.org/wiki/Coccinelle_%28software%29 "Semantic patching approaches") which can be evaluated by [the Coccinelle software](http://coccinelle.lip6.fr/ "Source code analysis and transformation"). This approach supports the programming language "C" to some degree.
* There are also tools evolving for [model-driven engineering](https://en.wikipedia.org/wiki/Model-driven_engineering "Description for model-driven engineering") and [dynamic system reconfiguration](https://en.wikipedia.org/wiki/Reconfigurable_computing#High-performance_computing "Description for ").

Do you get ideas to improve evolution around such application domains?

**Comment by beniz** [comment]
Sort of. My bias is obviously toward machine learning. This recent news is close to a series of small projects I've had in mind for a while, you might find this interesting: http://news.mit.edu/2016/faster-automatic-bug-repair-code-errors-0129

**Comment by elfring** [comment]
Are you interested to integrate the knowledge about unnecessary null pointer checks into any evolving machine learning systems?

**Comment by beniz** [comment]
If you mean that you have some sort of dataset, I'd look at it.

**Comment by elfring** [comment]
Are any more software developers and machine learning researchers interested to create a database similar to [the approach "Automatic Patch Generation by Learning Correct Code" by Fan Long and Martin Rinard](http://people.csail.mit.edu/fanl/papers/prophet-popl16.pdf "Learning update candidates?") for advanced source code queries?

**Comment by beniz** [comment]
That would put you on permanent vacation. I think I like permanent vacation.

**Comment by elfring** [comment]
Would you like to train your software to find any more update candidates in specific application domains?

**Comment by beniz** [comment]
I think I'd like permanent vacation :)

**Comment by elfring** [comment]
Does such a vacation prevent you from further experiments with your evolving software?

**Comment by beniz** [comment]
Definitely!

**Comment by beniz** [comment]
But to answer your earlier question, this software is not fully equiped to deal with such a dataset, as I it may require using recurrent neural nets / LSTM, which dd does not support for now. If you make a dataset public, I'll look at it. I am certain many researchers would be interested as well. Code cleanup has a high cost and it is legitimate to believe that code should get automated, rapidly.

**Comment by elfring** [comment]
How are the chances to discuss corresponding software evolution any further after your holiday was eventually long enough?   ;-)

**Comment by beniz** [comment]
Let's keep the discussion open. A good place where to wrap up your questions regarding feasibility of something like this is https://reddit.com/r/machinelearning

**Comment by elfring** [comment]
I prefer other communication interfaces so far. Would you like to look at any additional tools for this purpose?
