### ISSUE TITLE
Building of a binary hash code image similarity search application

### ISSUE THREAD

**Issue by masakinakada** [beniz/deepdetect#55]
Hi community, 

I would like to implement binary hash code search application as it is written in this paper,  'Deep Learning of Binary Hash Code' to enable fast image similarity match.  Specifically, I want to use googlenet and achieve the similarity search with elasticsearch on aws EC2. 

Since we need to take the feature vector from the network as the hash code, I believe we need to output value from the hidden layer (One layer before the final output softmax layer) in convolutional network, but deepdetect library currently does not support the output of the values. 

Please kindly help me if anyone have done this before. 
I appreciate any kind of supports. 

Thank you very much for providing this awesome library. 
Masaki

**Comment by beniz** [comment]
Good initiative! Link to the paper: http://www.iis.sinica.edu.tw/~kevinlin311.tw/cvprw15.pdf

 I believe this can be achieved in a few steps:

- [ ] Setup the appropriate `.prototxt` file with added latent layer, see https://gist.github.com/kevinlin311tw/266d4150a1db5810398e for replicate of the original on CIFAR
- [ ] Getting access to the net's inner layers through the API, and this is already on our todolist so a ticket will created very shortly
- [ ] Implement thresholding into dd for creating the binary features out of any layer. I believe that it makes sense to have this right into deepdetect, typically with a boolean `binarized` passed to the `output` connector
- [ ] Figure out what proper format is needed for indexing into ES: Hamming distance is a comparison metric of choise, I am not sure yet how ES can be configured to appropriately compute the nearest neighbors based on Hamming (or any other non-textual) distance
- [ ] Optionally, create a simple Web interface for looking at the results. An example to start from lies in the `demo/imgdetect` repository

Note that some other works like [visual search from Pinterest](http://arxiv.org/abs/1505.07647) do not rely on an additional latent layer but use binarized features from the existing net's layers directly. This means that an intermediary step for testing the whole pipeline does not forcely require the additional latent layer.

I understand that getting access to Caffe's inner layer is a blocker here. Depending on your C++ skills you can dig into the [`caffelib::predict` function](https://github.com/beniz/deepdetect/blob/master/src/caffelib.cc#L1664) and gather preliminary thoughts and/or code, or let that to me, but I won't be able to work on it till after the week-end.

**Comment by beniz** [comment]
@masakinakada PR #59 implements most of #56 and you should now be able to move forward. Visual search should not be far. Please let me know of any progress and difficulties, if any.

**Comment by masakinakada** [comment]
Hi Em,

Thank you so much for this update. You are my life saver. I was trying to modify other part of the code but was a bit struggling.

I will try to complete it with your awesome update! 
Thank you very much. I will give you update on my progress.

Masaki

**Comment by beniz** [comment]
PR #73 gives a full example of both indexing and searching of similar images with good performances.

**Comment by masakinakada** [comment]
Awesome! Thanks a lot Ema!

**Comment by beniz** [comment]
Given that there's now a demo provided for image similarity search, I am closing this issue. Any further development may reopen it.
