### ISSUE TITLE
Bad request on the web demo

### ISSUE THREAD

**Issue by anguoyang** [beniz/deepdetect#65]
I have compiled and run `deepdetect/demo/imagedetect` successfully, but when I try to classify a image, it always returns "bad request".

My OS is Ubuntu 14.04 LTS, and there is no error on compiling deepdetect, and I followed all the instructions on deepdetect and  web demo except:

changing these 2 lines
```
server {
  listen 80 default_server; 
  listen [::]:80 default_server;
```
-----------------------------------------

to the default value of nginx.conf
```
server {
listen       80;
 server_name  localhost;
```
-------------------------------

If NOT, it will generate "IPV6 is not supported ......" errors, so I have to modify these lines to its default value(for other lines, I use the value provided by deepdetect demo )

But if I do so, it always returns "bad request"

**Comment by anguoyang** [comment]
Further more, my image for classification is in 224x224 pixels, which is same with tutorial on deepdetect's website

**Comment by anguoyang** [comment]
{"status":{"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error"}}

**Comment by anguoyang** [comment]
BadRequest is because the image url is not found,  sorry for my silly mistake:)
Now it worked, please close the issue, thank you.

**Comment by beniz** [comment]
@anguoyang this should be a minor mis-configuration somewhere, so let's check that the server works without `nginx` first.

Can you report what happens with `curl` for both the service creation `PUT` call and the `POST predict` call for an image, as in the tutorial on http://www.deepdetect.com/tutorials/imagenet-classifier/:
- the log on the server side
- the exact `PUT` and `POST` calls

Once this works fine, we can look whether it works with `nginx`: there's a known issue with IPV6, see #26 and you can look at this comment: https://github.com/beniz/deepdetect/issues/26#issuecomment-161918301

**Comment by anguoyang** [comment]
nginx is fine, I made a silly mistake as the image URL I used is not available anymore, so it generated the BadRequest error.
Thanks for your excellent work! it works fine right now.

**Comment by beniz** [comment]
OK, great :)
