### ISSUE TITLE
Out of memory for training ResNet-50

### ISSUE THREAD

**Issue by thuhuwei** [beniz/deepdetect#66]
Hi, I tried to train ResNet-50 on ImageNet dataset, but got the following error

F0217 22:21:14.935607 24606 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7fea9e483daa  (unknown)
    @     0x7fea9e483ce4  (unknown)
    @     0x7fea9e4836e6  (unknown)
    @     0x7fea9e486687  (unknown)
    @     0x7fea9eaeca61  caffe::SyncedMemory::to_gpu()
    @     0x7fea9eaebdc9  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7fea9eaeda63  caffe::Blob<>::mutable_gpu_diff()
    @     0x7fea9ec116d3  caffe::PoolingLayer<>::Backward_gpu()
    @     0x7fea9eaab737  caffe::Net<>::BackwardFromTo()
    @     0x7fea9eaab8a1  caffe::Net<>::Backward()
    @     0x7fea9ea876ed  caffe::Solver<>::Step()
    @     0x7fea9ea87fe9  caffe::Solver<>::Solve()
    @     0x7fea9ebeada5  caffe::P2PSync<>::run()
    @           0x407c9b  train()
    @           0x4059dc  main
    @     0x7fea9d791ec5  (unknown)
    @           0x406111  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

I just modified the data layer in resnet_50.prototxt, as
 
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    #mean_file: "/data/lmdb/imagenet/imagenet_mean.binaryproto"
    mirror: true
    crop_size: 224
    mean_value: 104
    mean_value: 117
    mean_value: 123
  }
  data_param {
    source: "/data/lmdb/imagenet/ilsvrc14_train_lmdb"
    batch_size: 32
    backend: LMDB
  }
}

8 GTX Titan GPUs (with 12G Memory) are used. Did you train this net before? and could you give me some suggestions on memory consuming problems? Thanks

**Comment by beniz** [comment]
Yes I did train it on a 12GB K40. Can you share your training call, and most especially the `batch_size` ? Note that you can use `test_batch_size` to reduce the size of the testing net batch, which is useful in reducing memory trace.

A side note here, Caffe is annoying as it loads both the testing and training net into memory, whereas we would like to switch from one to the other as needed. This is a planned improvement of `deepdetect` over Caffe, but not available yet.

**Comment by beniz** [comment]
@thuhuwei have you looked at the calls here: https://github.com/beniz/deepdetect/pull/60

**Comment by beniz** [comment]
FTR, after another run, `batch_size:32` and `test_batch_size:2` get the net within the 12GB boundary and training proceeds flawlessly.

**Comment by thuhuwei** [comment]
@beniz , It's very strange. Could you give me the Makefile.config file for compiling the Caffe? I only change one place: uncomment USE_CUDNN := 1, and keep other default configurations. The used Caffe was cloned from BVLC/caffe just yesterday.

**Comment by beniz** [comment]
There's only support for dd here. You'll find the custom version of Caffe in `build/caffe_dd/src/caffe_dd/`. Not using CUDNN may very well affect the memory requirement. My report above is with CUDNNN (v3 or v4, doesn't matter).
