### ISSUE TITLE
Request on docker build

### ISSUE THREAD

**Issue by anguoyang** [beniz/deepdetect#72]
Hi all, could you please build a docker image/package for deepdetect? It would be much more convenient for installation on different OS, thank you.

**Comment by Isaacpm** [comment]
Hi guys,
I've got a docker container with deepdetect running inside a centos 7 OS and these are the steps I followed:

- Install docker in Centos:
yum install docker

- Start the docker service
systemctl start docker

- Get latest ubuntu image
docker pull ubuntu

- Access the ubuntu image
docker run -t -i ubuntu /bin/bash
(this gets you into the container bash shell, from now they are ubuntu commands)

- Enable multiverse repos:
edit /etc/apt/sources.list
Uncomment the multiverse lines (should be last two, they end in multiverse)

- Install git and cmake:
apt-get install git cmake

- Follow deepdetect installation instructions:
http://www.deepdetect.com/overview/installing/

**Comment by anguoyang** [comment]
hi, thanks a lot for your sharing! it did work for me.
ps: I need to do "apt-get update && apt-get upgrade" before the deepdetect installation process.
and after I build deepdetect successfully, I need to "sudo ln /dev/null /dev/raw1394"  before running ./main/dede, otherwise, it will generate a 1394 error.

**Comment by Isaacpm** [comment]
Hi,

you are welcome :-), that's weird, i didn't have to do the symlink... But you are right, forgot the apt-get update and update.
I'm creating a docker container to upload to docker hub, but being my first time, I've run into some beginner problems. Will post here once it's there.

**Comment by Isaacpm** [comment]
Hi,
I've build a docker container that has deepdetect in /deepedetect, built following the instructions you can see in my previous answer.
You just need to pull it using docker:
docker pull isaacpm/deepdetect

**Comment by beniz** [comment]
Thanks @Isaacpm.
Do you think you could share the full list of steps from pulling the docker image to running `dede` by any chance ?
Three steps I'd like to help achieve are:
- get step by step doc that can be put on the site for using the docker image without effort
- setup some ready-for-use image classification models right into the image similarly to https://github.com/beniz/deepdetect/issues/5#issuecomment-188464262
- automate the docker image creation out of every new commit on `master`

**Comment by Isaacpm** [comment]
Hi @beniz 
I think I need to do a couple of changes to make it even easier to use.
So you download the image, assign an IP, and then connect from the host OS to the REST API. I'll get the changes done and upload a new image, will post here the steps, or send by email, whatever you prefer.
I'll get those models loaded into the image, should be simple enough.

For the automation, I need to research a bit more on it, and will probably have some questions for you. But let me do steps 1 and 2 first, then we can see the automations.

Cheers,
Isaac

**Comment by beniz** [comment]
So I've been able to use @Isaacpm's image, here is how:
```
apt-get install docker.io
docker pull isaacpm/deepdetect
docker run -t -i isaacpm/deepdetect /bin/bash
cd /deepdetect/build/main
./dede -host 0.0.0.0
```
From another shell on the same machine:
```
curl -X GET "http://172.17.0.1:8080/info"
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"c8556f0b3e7d970bcd9861b910f9eae87cfd4b0c","services":[]}}
```

Notes:
- the image is ~1.3GB in size, which I guess is due to having the full Ubuntu image with it
- the image runs and yield a `root` user command line, which means `dede` then executes as `root` from within the image. I'm not sure this is the right thing to do, but at this stage I can't tell whether this is the normal way of doing things
- the image does not contain CUDA nor support for GPU, so it is CPU only

My understanding is that there'd be a need for a GPU-ready docker image, and I'll be able to help with that once the image generation process is stabilized. See http://stackoverflow.com/questions/25185405/using-gpu-from-a-docker-container for GPU support and docker.

**Comment by Isaacpm** [comment]
HI Beniz,
would that be enough to cover point one?
If it is, I've added the image classification models in the image and was going to install nginx to get the front end

**Comment by beniz** [comment]
@Isaacpm I think so yes for points 1& 2. 
I'm not sure about nginx + front immediately for two reasons;
- modifying the default `nginx` config might harm some usages
- the front only works for ImageNet-based models, as it links to the synsets, and we should get a slightly more generic version that can accomodate any image model.

As you suggested on IRC, 3 can be accomodated with https://docs.docker.com/docker-hub/github/ and I should be able to deal with the GPU build.

**Comment by Isaacpm** [comment]
Ok, cool.
I will leave this for now, if you need any more help with it, just shout :-)

**Comment by beniz** [comment]
@Isaacpm thanks for the very useful work again. Will keep news posted here, until everything is fine and docker images are automated and made available.

**Comment by beniz** [comment]
Hi, I've spent some time on polishing the docker image. There's an official one that is a CPU-only build here now: https://hub.docker.com/r/beniz/deepdetect_cpu/.

Here is how to use it:
```
docker pull beniz/deepdetect_cpu
docker run -d -p 8080:8080 beniz/deepdetect_cpu
curl http://localhost:8080/info
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"c8556f0b3e7d970bcd9861b910f9eae87cfd4b0c","services":[]}}
```

Difference with the initial build by @Isaacpm:
- `dede` runs by default and listens on `0.0.0.0` + binds on host: this means it is like if `dede` were running on the host
- images for `googlenet` and `resnet_50` are available in the container's `/opt/models/` repository
- the repository `/data` in the container is a `VOLUME` in docker jargon, that can mount any repository from the host, see https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-directory-as-a-data-volume for how to use this feature. In our case this is expected to be useful to share training sets for instance.

The GPU container version in on its way.

@Isaacpm @anguoyang I'd appreciate if you can test the image above and report any problem.

**Comment by Isaacpm** [comment]
@beniz works well, it's awesome, much easier to use now :-)

**Comment by beniz** [comment]
OK, docker GPU image is ready here: https://hub.docker.com/r/beniz/deepdetect_gpu/

This requires `nvidia-docker`, steps to run are below:
- install `nvidia-docker`: https://github.com/NVIDIA/nvidia-docker
- get the image: docker pull beniz/deepdetect_gpu
- run with nvidia-docker run -d -p 8080:8080 beniz/deepdetect_gpu

To test on image classification on GPU:
```
curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"nclasses\":1000,\"template\":\"googlenet\"}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"/opt/models/ggnet/\"}}"
{"status":{"code":201,"msg":"Created"}}
```
and
```
curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3},\"mllib\":{\"gpu\":true}},\"data\":[\"http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg\"]}"
```

Try the `POST` call twice: first time loads the net so it takes slightly below a second, then second call should yield a `time` around 100ms as reported in the output JSON.

Please post any issue and difficulties here, including anything about installing `nvidia-docker` as it'd be nice to gather full set of reproducible steps.

Notes:
- `nvidia-docker` requires docker >= 1.9
- `nvidia-docker` can be a bit tricky to install

**Comment by anguoyang** [comment]
Hi, guys, sorry for the late response, I was busy on a project these days:)
Thank you all for your kind help, I am trying to pull the CPU version, the bandwidth to the docker hub is a little bit slow in my area -:).  
my NoteBook has  GPU, but the OS is Windows, it is the only PC of mine that support CUDA, I was told that vmware or other virtual machines does not support GPU emulation, so maybe I have to re-install the OS.

**Comment by beniz** [comment]
Docker images are now available from https://hub.docker.com/u/beniz/ and will be rebuilt as needed when codebase evolves. Dockerfile are now in https://github.com/beniz/deepdetect/tree/master/docker
Thanks for the help everyone.

In case of difficulties, use this issue to report them.
