### ISSUE TITLE
Support for SqueezeNet architecture

### ISSUE THREAD

**Issue by beniz** [beniz/deepdetect#74]
Kindly made available by the authors here: https://github.com/DeepScale/SqueezeNet

**Comment by wasim888555** [comment]
hey @beniz  how do you convert other pretrained models like https://github.com/DeepScale/SqueezeNet  or https://github.com/BVLC/caffe/wiki/Model-Zoo to work with deepdetect

**Comment by beniz** [comment]
Take a look at https://github.com/beniz/deepdetect/tree/master/templates/caffe/googlenet and simply change the pretrained model `deploy.prototxt` first layer to be of type `MemoryData`. If you do it for SqueezeNet, please share the resulting file(s), as it's been sitting here too long already.

**Comment by wasim888555** [comment]
yes i did and it is working 
[deploy.prototxt.txt](https://github.com/beniz/deepdetect/files/228486/deploy.prototxt.txt)

**Comment by beniz** [comment]
Great. Any report on the true performances of SqueezeNet if this is one of the models you are using, is welcome.

**Comment by wasim888555** [comment]
I have not tested much but the accuracy seems to be close to caffenet
[Here ](https://github.com/DeepScale/SqueezeNet/issues/3)is a benchmark tests on this net

**Comment by beniz** [comment]
Added. Tested in both training & prediction.
