### ISSUE TITLE
Labels to other languages

### ISSUE THREAD

**Issue by anguoyang** [beniz/deepdetect#77]
Hi, the labels in modes are always in English language, when I upload a image(with a rabbit) from the webdemo, it detect and describe it as, e.g. "rabbit 99%",  my question is, how to translate the description string into other languages, such as Chinese, Japanese,etc. Do I need to use "google translation" or similar functions to convert it into other languages after the detection process? thanks

**Comment by beniz** [comment]
There's a `corresp.txt` file created by deepdetect in any supervised Caffe model. It is also provided with the models from http://www.deepdetect.com/applications/model/ and http://www.deepdetect.com/applications/text_model/. You can translate the words in this `corresp.txt` file, restart the service and it should work fine. Let me know if you have issue, possible caveats include utf-8 nightmares.
