### ISSUE TITLE
Binary classifier experiment.

### ISSUE THREAD

**Issue by andrewcz** [beniz/deepdetect#81]
Hi,
Fantastic Library, so clear!
I was just wondering, i am trying to use the library for a binary classifier experiment using the log loss error function to train the model. This is for a university experiment around benchmarking different models. Would you have time to provide an example of how to use the library to achieve the above goal.
Many thanks,
Best,
Andrew

**Comment by beniz** [comment]
The tutorials contain everything you need http://www.deepdetect.com/tutorials/tutorials/, happy homework!
