### ISSUE TITLE
Python client post_train needs service name as lowercase

### ISSUE THREAD

**Issue by Isaacpm** [beniz/deepdetect#87]
Hi,

I was trying to create and train a service with python and the following happened:
put_service works
get_service works but shows name in lowercase
post_train fails with service not found unless I lowercase the service name. Once I lowercase the service name, it works fine.

Couldn't find anything in the documentation relating to service names should be lowercase. But not sure if should always be.

Thanks,
Isaac

**Comment by beniz** [comment]
Good catch, thanks! The service name is automatically turned into lowercase, which is common practice in REST API because URLs are themselves case-insensitive, so lowercase becomes the default. Commit above fixes the issue, which was server-side.
