### ISSUE TITLE
Using Deepdetect for personal / face data image search

### ISSUE THREAD

**Issue by kyrs** [beniz/deepdetect#92]
I am working on a project to use deepdetect to search personal images and text from an unorganized database.And as a part of the project, I want to search images of similar people from a big personal image database. I am following https://github.com/beniz/deepdetect/tree/imgsearch/demo/imgsearch for the above purpose. But I guess, the model used in it is not trained for such purpose. Any idea on how to proceed for the same.

**Comment by beniz** [comment]
You could try using the VGG face descriptors from http://www.robots.ox.ac.uk/~vgg/software/vgg_face/. This should be easy to make the `.prototxt` files compatible with dd. Then you should be able to test how features various layers do affect search accuracy. I'm interested in both the minor model tweaks as well as in results if you can share.

**Comment by kyrs** [comment]
I am trying to run the above mentioned model but each time I run the modified imgsearch.py  https://gist.github.com/kyrs/7e26016c45fa788d2d44   with the given .prototxt file https://gist.github.com/kyrs/729f1744351fb98351c3 . I am getting following error 
![deepdetect](https://cloud.githubusercontent.com/assets/10322195/14076489/bffbef5a-f4ff-11e5-8494-4382dd5cc56a.png). how to sought out this error ??

**Comment by beniz** [comment]
I believe you need a memorydata layer to use the prototxt with dd. Look at the existing googlenet and resnet templates.

**Comment by kyrs** [comment]
`.prototxt` file mentioned in the above files was based on older version of caffee. I have modified it to suit the dd architecture  https://gist.github.com/kyrs/03eb513f89577e599973 . Presently, it is working fine with smaller database but let me check its performance with bigger database. Will let you know about it's performance.

**Comment by beniz** [comment]
Over 15 days with activity, closing.
