### ISSUE TITLE
Image search similary demo error

### ISSUE THREAD

**Issue by pribadihcr** [beniz/deepdetect#94]
Hi @beniz 

When tried $python imgsearch.py --index databaseImages --index-batch-size 2
I got the following error:
0/10Traceback (most recent call last):
  File "imgsearch.py", line 78, in <module>
    for p in classif['body']['predictions']:
KeyError: 'body'

many thanks for help

**Comment by kyrs** [comment]
hi @pribadihcr I guess your service haven't been launched properly.  I would suggest you to print the response of launching the service to see the error.

**Comment by pribadihcr** [comment]
hi @kyrs 

The response is here:
ERROR - service clothing prediction call failed

**Comment by pribadihcr** [comment]
hi @kyrs 

yes my model repository is wrong. And I need to restart ./dede service. It's work now

Thanks
