### ISSUE TITLE
Service creation Error

### ISSUE THREAD

**Issue by anguoyang** [beniz/deepdetect#99]
Hi, @beniz , I tried to create the age classification service with:

curl -X PUT "http://localhost:8080/services/ageserv" -d "{\"mllib\":\"caffe\",\"description\":\"age classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"nclasses\":2,\"template\":\"age_model\"}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"/opt/models/age_model/\"}}"

and got these errors:
{"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}

Thanks.

**Comment by beniz** [comment]
There is no `age_model` template, and you shouldn't need a template for a pre-trained model.

**Comment by anguoyang** [comment]
Is it correct that I delete the template section? as this:
curl -X PUT "http://localhost:8080/services/ageserv" -d "{\"mllib\":\"caffe\",\"description\":\"age classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"nclasses\":2}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"/opt/models/age_model/\"}}"

**Comment by beniz** [comment]
Let me know if the documentation in http://www.deepdetect.com/applications/model/ does not answer your questions. Also many examples to copy from can be found in http://www.deepdetect.com/overview/examples/

**Comment by anguoyang** [comment]
Yes, the documentation is good, however, it would be better if there are more examples on creating services and predicting, as there are differences among different service creation process.

**Comment by anguoyang** [comment]
I create the age service(ageserv) successfully, however, it did not predict properly:
curl -X POST "http://123.56.191.136:8080/predict" -d "{\"serv
ice\":\"ageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"out
put\":{\"best\":1}},\"data\":[\"http://www.deepdetect.com/img/ambulance.jpg\"]}"

there is no response from the server.

**Comment by beniz** [comment]
Look at the error on the server, and you should receive an error through JSON as well. In all cases, look at the `model.json` file in the model repository, it is possible that the input size is not 224.

**Comment by anguoyang** [comment]
OK, thanks, I check it

**Comment by anguoyang** [comment]
It is strange that the service creation was successful, after I deleted the "age_model template" section, as the input size in service creation is also 224

**Comment by beniz** [comment]
The input is checked when the input `connector` starts dealing with data, which is either when starting `predict` or `train`. There would be ways to have a check done earlier, but this is not the case at the moment, so the error is raised when starting to use the model.

**Comment by anguoyang** [comment]
OK, I see. Yes, the size is 227, I will try to use the model.json description to re-create the service.

**Comment by anguoyang** [comment]
I refer to the model.json:
curl -X PUT "http://localhost:8080/services/ageserv" -d "{\"mllib\":\"caffe\",\"description\":\"age classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\"},\"mllib\":{\"nclasses\":2}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"/opt/models/age_model/\"}}"

curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"ageserv\",\"parameters\":{\"input\":{\"width\":227,\"height\":227},\"output\":{\"best\":1},\"mllib\":{\"gpu\":false}},\"data\":[\"http://img3.imgtn.bdimg.com/it/u=538620931,966366482&fm=11&gp=0.jpg\"]}"

However, got this error:
{"status":{"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error"}}

**Comment by beniz** [comment]
what does the server say ?

**Comment by anguoyang** [comment]
The json output from server is : {"status":{"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error"}}

**Comment by anguoyang** [comment]
However, the service creation is correct.

**Comment by beniz** [comment]
You'd need to look at the server log

**Comment by anguoyang** [comment]
Is it in /var/log or somewhere in the dede directory?

**Comment by beniz** [comment]
Server output is within the terminal where you did start dede

**Comment by anguoyang** [comment]
I used the cpu/docker version by: 
docker run -d -p 8080:8080 --net=host beniz/deepdetect_cpu
it seems there is no output

**Comment by beniz** [comment]
Yes, good point, I'm not sure it can be accessed then. We should definitely modify the docker build so that it becomes accessible. However, in the meantime I'd check that your image can be correctly accessed, and also, can you test on a publicly accessible image so that we can try to reproduce ? thanks.

**Comment by anguoyang** [comment]
Yes, I tested it on a public IP, I would be glad to send the information to you by email.

**Comment by beniz** [comment]
OK, but the prediction result on a public image, so we can test here.

**Comment by anguoyang** [comment]
The ip is: 123.56.191.136 
this is also the host ip, maybe you could login with dede default uid/pwd?

**Comment by beniz** [comment]
@anguoyang Please do not share private information in these public forums. Please delete your above message.

Also, you are misunderstanding me: the image you are using is not accessible (Forbidden), please provide prediction result or error on publicly accessible image.

**Comment by anguoyang** [comment]
OK, I deleted it. thanks.
All the prediction result and error above are on this publicly accessible IP, do you mean that the docker image is not accessible (Forbidden)?

**Comment by anguoyang** [comment]
What I have done with docker image:
1.pull beniz/deepdetect_gpu
2. run this docker image
3. download all the model files and extract into /opt/models
4.docker commit container-id angoyang/deserver:v5
5.stop deepdetect_gpu and run the new docker image(angoyang/deserver:v5)

I dont know why it is not accessible, actually, my docker account and rep are all publicly

**Comment by anguoyang** [comment]
sorry, pull beniz/deepdetect_cpu, not pull beniz/deepdetect_gpu

**Comment by anguoyang** [comment]
Hi, @beniz , I found the reason eventually:)
{"status":{"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error"}}

this error resulted from "unknow image url", for example:
http://img3.imgtn.bdimg.com/it/u=538620931,966366482&fm=11&gp=0.jpg

but actually, it is a correct URL, from my understanding, it is a minor fault, I would like to modify on it and PR it if necessary.

**Comment by beniz** [comment]
The URL http://img3.imgtn.bdimg.com/it/u=538620931,966366482&fm=11&gp=0.jpg yields a 'Forbidden', which means the image content cannot be accessed. The return error is correct AFAIK.

FYI, server says:

```
ERROR - no data for image http://img3.imgtn.bdimg.com/it/u=538620931,966366482&fm=11&gp=0.jpg
ERROR - service gender mllib bad param: no image could be found
```

In general, the question of whether a problem or fault is minor is handled at application level, not server level.

Also, tested the `age_model` and it appears to work fine. I am closing this for now, let me know if there are still problems.
